-- Read-only evidence for the files of database/migrations whose effect the
-- catalog fingerprint cannot show (scripts/db/baseline-verify.sh reports them
-- as "unverifiable"): data, customer-role grants, storage parameters. One row,
-- one JSON object; every value is a count or a boolean, never row content.
--
--   PGOPTIONS='-c default_transaction_read_only=on' \
--     psql "$TARGET_DATABASE_URL" -qAtX -f scripts/db/baseline-evidence.sql
--
-- What each value means, and the decision it supports, is in
-- docs/AUTO_MIGRATIONS.md ("The unverifiable files").
SELECT jsonb_pretty(jsonb_build_object(
 '000 default grants to customer roles in public (0 = revoked)', (SELECT count(*) FROM pg_default_acl d CROSS JOIN LATERAL aclexplode(d.defaclacl) x WHERE d.defaclnamespace = 'public'::regnamespace AND x.grantee IN (SELECT oid FROM pg_roles WHERE rolname IN ('anon','authenticated','service_role'))),
 '004 global feature flags (6 keys, 6 rows = seeded once)', (SELECT count(DISTINCT key) || ' keys / ' || count(*) || ' rows' FROM public.feature_flags WHERE workspace_id IS NULL AND key IN ('widget','knowledge_base','visitor_tracking','ai_assistant','email_campaigns','billing')),
 '012 AI-KB functions open to customers or closed to service_role', (SELECT count(*) FROM unnest(ARRAY['public._ai_kb_apply_generated(uuid, uuid, uuid, text, text, text, text)','public.accept_ai_kb_generated_article(uuid, uuid, uuid)','public.publish_ai_kb_generated_article(uuid, uuid, uuid)','public.reject_ai_kb_generated_article(uuid, uuid, uuid)']) s WHERE to_regprocedure(s) IS NOT NULL AND (has_function_privilege('public', to_regprocedure(s)::oid, 'EXECUTE') OR has_function_privilege('anon', to_regprocedure(s)::oid, 'EXECUTE') OR has_function_privilege('authenticated', to_regprocedure(s)::oid, 'EXECUTE') OR NOT has_function_privilege('service_role', to_regprocedure(s)::oid, 'EXECUTE'))),
 '013 CREATE on public for PUBLIC/anon/authenticated (all false = locked)', jsonb_build_array(has_schema_privilege('public','public','CREATE'), has_schema_privilege('anon','public','CREATE'), has_schema_privilege('authenticated','public','CREATE')),
 '014 SECURITY DEFINER functions executable by PUBLIC (0)', (SELECT count(*) FROM pg_proc p WHERE p.pronamespace = 'public'::regnamespace AND p.prosecdef AND has_function_privilege('public', p.oid, 'EXECUTE')),
 '016/223 operator_activity_samples gone', (to_regclass('public.operator_activity_samples') IS NULL AND to_regclass('public.operator_activity_samples_legacy') IS NULL),
 '018 calls not yet linked to their queue entry''s visitor session (0)', (SELECT count(*) FROM public.call_sessions cs JOIN public.call_queue_entries q ON q.call_session_id = cs.id WHERE cs.visitor_session_id IS NULL AND q.visitor_session_id IS NOT NULL),
 '029 confirmed auth.users emails not verified in user_credentials (0)', CASE WHEN to_regclass('auth.users') IS NULL THEN NULL ELSE (SELECT count(*) FROM public.profiles p JOIN auth.users au ON au.id = p.id LEFT JOIN public.user_credentials uc ON uc.user_id = p.id WHERE au.email_confirmed_at IS NOT NULL AND (uc.user_id IS NULL OR uc.email_verified_at IS NULL)) END,
 '032 profiles email index definition', pg_get_indexdef(to_regclass('public.profiles_email_normalized_unique_idx')),
 '037 legacy auth.users signup trigger (0)', (SELECT count(*) FROM pg_trigger t WHERE t.tgrelid = to_regclass('auth.users') AND t.tgname = 'on_auth_user_created' AND NOT t.tgisinternal),
 '045/046 widget_platform_settings readable by customer roles (false)', (has_table_privilege('anon','public.widget_platform_settings','SELECT,INSERT,UPDATE,DELETE') OR has_table_privilege('authenticated','public.widget_platform_settings','SELECT,INSERT,UPDATE,DELETE')),
 '047 plans with legacy limit keys (0)', (SELECT count(*) FROM public.billing_plans WHERE limits ?| array['contacts','conversations','conversations_monthly','team_members','agents','ai_credits','ai_requests_monthly','ai_kb_monthly_credits','ai_kb_max_articles','ai_kb_max_chars','kb_articles','storage_mb','file_storage_mb'] OR entitlements ?| array['advanced_analytics','ai_enabled']),
 '064 plans without widget_powered_by (0)', (SELECT count(*) FROM public.billing_plans WHERE entitlements IS NOT NULL AND NOT (entitlements ? 'widget_powered_by')),
 '067 widget_prechat_settings.prechat_timing exists', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='widget_prechat_settings' AND column_name='prechat_timing'),
 '069 brand_name/reply_time_text nullable without default (2)', (SELECT count(*) FROM information_schema.columns WHERE table_schema='public' AND table_name='widget_settings' AND column_name IN ('brand_name','reply_time_text') AND is_nullable='YES' AND column_default IS NULL),
 '093 invitation tables open to customer roles (false)', (has_table_privilege('anon','public.workspace_invitations','SELECT,INSERT,UPDATE,DELETE') OR has_table_privilege('authenticated','public.workspace_invitations','SELECT,INSERT,UPDATE,DELETE')),
 '109 money functions executable by customer roles (0)', (SELECT count(*) FROM pg_proc p WHERE p.pronamespace = 'public'::regnamespace AND p.prosecdef AND p.proname IN ('billing_apply_subscription_payment','ai_purchase_credit','ai_grant_allowance','ai_adjust_balance','ai_refund_run','ai_settle_run','ai_reserve','ai_release_reservation','ai_topup_reservation','ai_begin_run','ai_open_step','ai_expire_lots','ai_reconcile_wallet','ai_ingest_usage_event','ai_publish_rate_card','ai_publish_sell_policy','ai_publish_exchange_rate') AND (has_function_privilege('public', p.oid, 'EXECUTE') OR has_function_privilege('anon', p.oid, 'EXECUTE') OR has_function_privilege('authenticated', p.oid, 'EXECUTE'))),
 '116 V2 backfill: legacy_migration periods / live subs without period / subs without anchor / workspaces without wallet', (SELECT count(*) FROM public.billing_subscription_periods WHERE source = 'legacy_migration') || ' / ' || (SELECT count(*) FROM public.workspace_subscriptions WHERE status IN ('active','trialing','past_due','free_fallback') AND current_period_id IS NULL) || ' / ' || (SELECT count(*) FROM public.workspace_subscriptions WHERE billing_anchor_at IS NULL) || ' / ' || (SELECT count(*) FROM public.workspaces w WHERE NOT EXISTS (SELECT 1 FROM public.billing_wallet_accounts a WHERE a.workspace_id = w.id)),
 '124/125/131/193 dropped functions, tables and indexes gone', (to_regprocedure('public.evaluate_alert_rules()') IS NULL AND to_regclass('public.realtime_metric_events') IS NULL AND to_regclass('public.perf_request_samples') IS NULL AND to_regclass('public.idx_operator_presence_live_ws_seen') IS NULL AND to_regclass('public.channel_worker_heartbeats_seen_idx') IS NULL),
 '138 active openai/text-embedding-3-small rate cards (1)', (SELECT count(*) FROM public.ai_rate_cards WHERE provider = 'openai' AND model_key = 'text-embedding-3-small' AND effective_to IS NULL),
 '191 messages still carrying agent_logo_url (false)', EXISTS (SELECT 1 FROM public.conversation_messages WHERE metadata ? 'agent_logo_url'),
 '194 lease tables tuned', (SELECT count(*) FILTER (WHERE coalesce(c.reloptions @> ARRAY['autovacuum_vacuum_threshold=1000','autovacuum_vacuum_scale_factor=0','autovacuum_analyze_threshold=1000','autovacuum_analyze_scale_factor=0','fillfactor=70'], false)) || '/' || count(*) FROM pg_class c WHERE c.relnamespace = 'public'::regnamespace AND c.relkind = 'r' AND c.relname IN ('observability_ticker_lease','channel_worker_heartbeats','billing_v2_worker_health','operator_presence_live','ai_billing_recovery_lease','realtime_failover_state')),
 '197 retired platform_domains URL shadows still set (0: none left of the legacy values 197 clears) / deprecation comment', (SELECT count(*) FROM public.platform_domains WHERE widget_base_url IS NOT NULL OR asset_base_url IS NOT NULL) || ' / ' || coalesce(col_description('public.workspace_branding'::regclass, (SELECT attnum::int FROM pg_attribute WHERE attrelid = 'public.workspace_branding'::regclass AND attname = 'canonical_base_url')) LIKE 'DEPRECATED%', false),
 '210/213 admin inventory RPCs or desktop settings open to customer roles (false)', (has_function_privilege('anon','public.admin_database_inventory(uuid)','EXECUTE') OR has_function_privilege('authenticated','public.admin_database_inventory(uuid)','EXECUTE') OR has_table_privilege('authenticated','public.desktop_app_settings','SELECT')),
 '217 definer functions open to customers outside the allow-list (0)', (SELECT count(*) FROM pg_proc p CROSS JOIN unnest(ARRAY['anon','authenticated']) AS g(r) WHERE p.pronamespace = 'public'::regnamespace AND p.prosecdef AND has_function_privilege(g.r, p.oid, 'EXECUTE') AND NOT EXISTS (SELECT 1 FROM (VALUES ('public.get_widget_platform_settings()', true, true), ('public.has_role(uuid, public.app_role)', false, true), ('public.is_workspace_member(uuid, uuid)', false, true), ('public.get_workspace_role(uuid, uuid)', false, true), ('public.is_account_member(uuid, uuid)', false, true), ('public.get_account_role(uuid, uuid)', false, true), ('public.workspace_owner_phone_verified(uuid)', false, true)) AS a(sig, anon_ok, auth_ok) WHERE to_regprocedure(a.sig) = p.oid AND CASE g.r WHEN 'anon' THEN a.anon_ok ELSE a.auth_ok END)),
 '244 legacy platform-support tickets still open (0)', (SELECT count(*) FROM public.conversations c JOIN public.platform_support_threads t ON t.conversation_id = c.id WHERE c.status IN ('open','pending') AND (c.metadata->>'platform_support_kind' = 'ticket' OR c.metadata->>'channel_thread_key' LIKE 'platform_support:ticket:%'))
));
