// GENERATED by scripts/ios/write-ios-config.mjs — do not edit by hand.
//
// Source of truth: platform_domains.api_base_url (Super Admin → Branding) of
// each brand's own platform, resolved at generation time: WebYar's from
// config/mobile-runtime.json, RESPOK's (BRAND_RESPOK, the `Respok` target)
// from config/mobile-runtime.respok.json. This is only the BOOTSTRAP the app
// uses for its very first request; see PlatformOrigin.swift, which replaces
// it with the platform's own answer and remembers that instead.

import Foundation

enum GeneratedConfig {
    #if BRAND_RESPOK
    /// Origin the app sends every API request to.
    static let apiBaseURL = URL(string: "https://api.respok.app")!

    /// Opened from Delete Account, for an owner who has to ask for help.
    static let supportURL = URL?.none

    /// Language a first launch starts in, before the operator picks one.
    static let defaultLanguage = Language.en
    #else
    /// Origin the app sends every API request to.
    static let apiBaseURL = URL(string: "https://api.webyar.ai")!

    /// Opened from Delete Account, for an owner who has to ask for help.
    static let supportURL = URL?.none

    /// Language a first launch starts in, before the operator picks one.
    static let defaultLanguage = Language.en
    #endif
}
