package com.webyar.ai.i18n

// GENERATED by scripts/android/strings-from-ios.mjs — do not edit by hand.
// Source of truth: ios/WebyarNative/Sources/Localization/Strings.swift
//
// A `when` rather than strings.xml, for the reason the Swift original is a
// `switch` rather than .strings files: the compiler refuses to build if a
// language is missing, so a key can never ship translated in one and blank in
// another. strings.xml would silently fall back to English instead. And the
// product never reads the device language — the operator picks one and it
// sticks — so locale resolution is not wanted here either.
//
// 399 of 415 strings are generated.
// These are hand-written in StringsManual.kt because they are logic rather
// than copy:
//   resetSentDetail — takes more than a language
//   deleteAccountOwnsBody — takes more than a language
//   conversationsCount — takes more than a language
//   activeFilters — takes more than a language
//   sysTransferred — takes more than a language
//   sysUnassigned — takes more than a language
//   sysAgentJoined — takes more than a language
//   sysCallInviteAudioFrom — takes more than a language
//   sysCallInviteVideoFrom — takes more than a language
//   callEndedByOperator — takes more than a language
//   callEndedByVisitor — takes more than a language
//   callEndedBySystem — takes more than a language
//   previewSentByImage — takes more than a language
//   previewSentByAudio — takes more than a language
//   previewSentByVideo — takes more than a language
//   previewSentByFile — takes more than a language

@Suppress("LargeClass", "TooManyFunctions")
object Str {
    fun appName(l: Language): String = when (l) {
        Language.EN -> "Webyar"
        Language.FA -> "وب‌یار"
        Language.TR -> "Webyar"
    }

    fun cancel(l: Language): String = when (l) {
        Language.EN -> "Cancel"
        Language.FA -> "انصراف"
        Language.TR -> "İptal"
    }

    fun retry(l: Language): String = when (l) {
        Language.EN -> "Try again"
        Language.FA -> "تلاش دوباره"
        Language.TR -> "Tekrar dene"
    }

    fun search(l: Language): String = when (l) {
        Language.EN -> "Search"
        Language.FA -> "جست‌وجو"
        Language.TR -> "Ara"
    }

    fun loginTitle(l: Language): String = when (l) {
        Language.EN -> "Welcome back"
        Language.FA -> "خوش آمدید"
        Language.TR -> "Tekrar hoş geldiniz"
    }

    fun loginSubtitle(l: Language): String = when (l) {
        Language.EN -> "Sign in to your account"
        Language.FA -> "وارد حساب کاربری خود شوید"
        Language.TR -> "Hesabınıza giriş yapın"
    }

    fun emailLabel(l: Language): String = when (l) {
        Language.EN -> "Email"
        Language.FA -> "ایمیل"
        Language.TR -> "E-posta"
    }

    fun passwordLabel(l: Language): String = when (l) {
        Language.EN -> "Password"
        Language.FA -> "رمز عبور"
        Language.TR -> "Parola"
    }

    fun logIn(l: Language): String = when (l) {
        Language.EN -> "Log in"
        Language.FA -> "ورود"
        Language.TR -> "Giriş yap"
    }

    fun forgotPassword(l: Language): String = when (l) {
        Language.EN -> "Forgot password?"
        Language.FA -> "رمز عبور را فراموش کرده‌اید؟"
        Language.TR -> "Parolanızı mı unuttunuz?"
    }

    fun resetSentTitle(l: Language): String = when (l) {
        Language.EN -> "Check your email"
        Language.FA -> "ایمیل خود را بررسی کنید"
        Language.TR -> "E-postanızı kontrol edin"
    }

    fun resetTitle(l: Language): String = when (l) {
        Language.EN -> "Reset your password"
        Language.FA -> "بازنشانی رمز عبور"
        Language.TR -> "Parolanızı sıfırlayın"
    }

    fun resetSubtitle(l: Language): String = when (l) {
        Language.EN -> "Enter the email address you sign in with. We will send you a link to choose a new password."
        Language.FA -> "نشانی ایمیلی که با آن وارد می‌شوید را بنویسید. پیوندی برایتان می‌فرستیم تا رمز تازه‌ای انتخاب کنید."
        Language.TR -> "Giriş yaptığınız e-posta adresini yazın. Yeni bir parola seçmeniz için size bir bağlantı göndereceğiz."
    }

    fun sendResetLink(l: Language): String = when (l) {
        Language.EN -> "Send the link"
        Language.FA -> "ارسال پیوند"
        Language.TR -> "Bağlantıyı gönder"
    }

    fun backToLogin(l: Language): String = when (l) {
        Language.EN -> "Back to sign in"
        Language.FA -> "بازگشت به ورود"
        Language.TR -> "Girişe dön"
    }

    /**
     * The nudge under the confirmation. People look in the inbox, find
     * nothing, and conclude it is broken — which is what the spam folder
     * usually is.
     */
    fun resetCheckSpam(l: Language): String = when (l) {
        Language.EN -> "Not there? Check your spam folder."
        Language.FA -> "نیامد؟ پوشه‌ی هرزنامه را هم ببینید."
        Language.TR -> "Gelmedi mi? Spam klasörünü de kontrol edin."
    }

    fun ok(l: Language): String = when (l) {
        Language.EN -> "OK"
        Language.FA -> "باشه"
        Language.TR -> "Tamam"
    }

    fun loginFailed(l: Language): String = when (l) {
        Language.EN -> "Could not sign you in. Check your email and password."
        Language.FA -> "ورود انجام نشد. ایمیل و رمز عبور را بررسی کنید."
        Language.TR -> "Giriş yapılamadı. E-posta ve parolanızı kontrol edin."
    }

    fun notifications(l: Language): String = when (l) {
        Language.EN -> "Notifications"
        Language.FA -> "اعلان‌ها"
        Language.TR -> "Bildirimler"
    }

    fun pushReply(l: Language): String = when (l) {
        Language.EN -> "Reply"
        Language.FA -> "پاسخ"
        Language.TR -> "Yanıtla"
    }

    fun pushReplyPlaceholder(l: Language): String = when (l) {
        Language.EN -> "Reply…"
        Language.FA -> "پاسخ…"
        Language.TR -> "Yanıt…"
    }

    fun pushMarkRead(l: Language): String = when (l) {
        Language.EN -> "Mark as read"
        Language.FA -> "خوانده شد"
        Language.TR -> "Okundu işaretle"
    }

    fun pushOpen(l: Language): String = when (l) {
        Language.EN -> "Open"
        Language.FA -> "باز کردن"
        Language.TR -> "Aç"
    }

    fun pushPrimerTitle(l: Language): String = when (l) {
        Language.EN -> "Know when a customer writes"
        Language.FA -> "وقتی مشتری پیام می‌دهد باخبر شوید"
        Language.TR -> "Bir müşteri yazdığında haberiniz olsun"
    }

    fun pushPrimerBody(l: Language): String = when (l) {
        Language.EN -> "Webyar can tell you about new messages, mentions and internal notes — even when the app is closed. You choose exactly which, and you can change it any time in Settings."
        Language.FA -> "وب‌یار می‌تواند پیام‌های تازه، نام‌بردن‌ها و یادداشت‌های داخلی را به شما خبر دهد — حتی وقتی برنامه بسته است. خودتان انتخاب می‌کنید کدام‌ها، و هر وقت خواستید از تنظیمات عوضش می‌کنید."
        Language.TR -> "Webyar yeni mesajları, bahsetmeleri ve dahili notları — uygulama kapalıyken bile — size bildirebilir. Hangilerini istediğinizi siz seçersiniz ve istediğiniz zaman Ayarlar'dan değiştirebilirsiniz."
    }

    fun pushTurnOn(l: Language): String = when (l) {
        Language.EN -> "Turn on notifications"
        Language.FA -> "روشن کردن اعلان‌ها"
        Language.TR -> "Bildirimleri aç"
    }

    fun pushNotNow(l: Language): String = when (l) {
        Language.EN -> "Not now"
        Language.FA -> "الان نه"
        Language.TR -> "Şimdi değil"
    }

    fun pushDeniedTitle(l: Language): String = when (l) {
        Language.EN -> "Notifications are off for Webyar"
        Language.FA -> "اعلان‌های وب‌یار خاموش است"
        Language.TR -> "Webyar için bildirimler kapalı"
    }

    /**
     * iOS only ever asks once, so after a refusal the only way back is the
     * system's own settings. Saying so is better than a switch that does
     * nothing when tapped.
     */
    fun pushDeniedBody(l: Language): String = when (l) {
        Language.EN -> "iOS asks only once. Turn them back on in the Settings app to be told about new messages."
        Language.FA -> "iOS فقط یک‌بار می‌پرسد. برای باخبر شدن از پیام‌های تازه، آن‌ها را در برنامه‌ی تنظیمات دوباره روشن کنید."
        Language.TR -> "iOS yalnızca bir kez sorar. Yeni mesajlardan haberdar olmak için Ayarlar uygulamasından yeniden açın."
    }

    fun pushOpenSettings(l: Language): String = when (l) {
        Language.EN -> "Open Settings"
        Language.FA -> "باز کردن تنظیمات"
        Language.TR -> "Ayarları aç"
    }

    fun pushUnavailable(l: Language): String = when (l) {
        Language.EN -> "This workspace has no notification service configured, so nothing will arrive on this phone yet."
        Language.FA -> "برای این فضای کاری سرویس اعلان تنظیم نشده، پس فعلاً چیزی به این تلفن نمی‌رسد."
        Language.TR -> "Bu çalışma alanı için bildirim servisi yapılandırılmamış, bu yüzden bu telefona henüz bir şey ulaşmayacak."
    }

    fun pushMuteAll(l: Language): String = when (l) {
        Language.EN -> "Pause all notifications"
        Language.FA -> "توقف همه‌ی اعلان‌ها"
        Language.TR -> "Tüm bildirimleri duraklat"
    }

    fun pushMuteAllFooter(l: Language): String = when (l) {
        Language.EN -> "Nothing is sent to any of your devices while this is on."
        Language.FA -> "تا وقتی این روشن است، چیزی به هیچ‌کدام از دستگاه‌های شما فرستاده نمی‌شود."
        Language.TR -> "Bu açıkken hiçbir cihazınıza bir şey gönderilmez."
    }

    fun pushScopeTitle(l: Language): String = when (l) {
        Language.EN -> "Tell me about"
        Language.FA -> "خبرم کن درباره‌ی"
        Language.TR -> "Şunları bildir"
    }

    fun pushScopeAll(l: Language): String = when (l) {
        Language.EN -> "Every conversation"
        Language.FA -> "همه‌ی گفتگوها"
        Language.TR -> "Her konuşma"
    }

    fun pushScopeAssigned(l: Language): String = when (l) {
        Language.EN -> "Conversations assigned to me"
        Language.FA -> "گفتگوهایی که به من سپرده شده"
        Language.TR -> "Bana atanan konuşmalar"
    }

    fun pushScopeMentions(l: Language): String = when (l) {
        Language.EN -> "Only when I am mentioned"
        Language.FA -> "فقط وقتی نام مرا می‌برند"
        Language.TR -> "Yalnızca benden bahsedildiğinde"
    }

    fun pushScopeNone(l: Language): String = when (l) {
        Language.EN -> "Nothing"
        Language.FA -> "هیچ‌کدام"
        Language.TR -> "Hiçbiri"
    }

    /**
     * An @mention always gets through the two narrower scopes; saying so
     * stops "assigned to me" reading as "and nothing else, ever".
     */
    fun pushScopeFooter(l: Language): String = when (l) {
        Language.EN -> "Someone mentioning you by name always gets through."
        Language.FA -> "اگر کسی نام شما را ببرد، همیشه به شما می‌رسد."
        Language.TR -> "Biri adınızı anarsa her durumda size ulaşır."
    }

    fun pushInternalNotes(l: Language): String = when (l) {
        Language.EN -> "Internal notes"
        Language.FA -> "یادداشت‌های داخلی"
        Language.TR -> "Dahili notlar"
    }

    /**
     * The kinds of event beyond a customer's message, each with its own
     * switch on the server.
     */
    fun pushEventsTitle(l: Language): String = when (l) {
        Language.EN -> "Also tell me about"
        Language.FA -> "اعلان این موارد هم بیاید"
        Language.TR -> "Bunları da bildir"
    }

    fun pushTeamChat(l: Language): String = when (l) {
        Language.EN -> "Messages from colleagues"
        Language.FA -> "پیام‌های همکاران"
        Language.TR -> "Ekip arkadaşlarından mesajlar"
    }

    fun pushAssignments(l: Language): String = when (l) {
        Language.EN -> "Conversations handed to me"
        Language.FA -> "گفتگوهایی که به من سپرده می‌شود"
        Language.TR -> "Bana devredilen konuşmalar"
    }

    fun pushEmail(l: Language): String = when (l) {
        Language.EN -> "New emails"
        Language.FA -> "ایمیل‌های جدید"
        Language.TR -> "Yeni e-postalar"
    }

    /**
     * "Handed to me" covers three different hands, and the AI's is the one
     * nobody would guess.
     */
    fun pushAssignmentsFooter(l: Language): String = when (l) {
        Language.EN -> "By a colleague, by automatic routing, or by the AI when a customer needs a person."
        Language.FA -> "توسط همکار، تخصیص خودکار، یا هوش مصنوعی وقتی مشتری به اپراتور نیاز دارد."
        Language.TR -> "Bir ekip arkadaşı, otomatik yönlendirme ya da müşteri bir temsilciye ihtiyaç duyduğunda yapay zekâ tarafından."
    }

    fun pushPrefsLoadFailed(l: Language): String = when (l) {
        Language.EN -> "Your notification settings could not be loaded."
        Language.FA -> "تنظیمات اعلان بارگذاری نشد."
        Language.TR -> "Bildirim ayarlarınız yüklenemedi."
    }

    fun pushShowPreview(l: Language): String = when (l) {
        Language.EN -> "Show the message"
        Language.FA -> "نمایش متن پیام"
        Language.TR -> "Mesajı göster"
    }

    /**
     * The preview is withheld by the SERVER when this is off, which is the
     * only way it can be withheld from a locked screen.
     */
    fun pushShowPreviewFooter(l: Language): String = when (l) {
        Language.EN -> "When this is off, the text never leaves the server — the notification only says a message arrived."
        Language.FA -> "وقتی خاموش باشد، متن پیام اصلاً از سرور بیرون نمی‌آید — اعلان فقط می‌گوید پیامی رسیده است."
        Language.TR -> "Bu kapalıyken metin sunucudan hiç çıkmaz — bildirim yalnızca bir mesaj geldiğini söyler."
    }

    fun pushSound(l: Language): String = when (l) {
        Language.EN -> "Sound"
        Language.FA -> "صدا"
        Language.TR -> "Ses"
    }

    /**
     * The two presence switches. Phrased as what the operator wants, not as
     * the state being tested: "while I am at my desk" is a thing somebody
     * recognises about their own day; "push when online" is a column name.
     */
    fun pushWhenOnline(l: Language): String = when (l) {
        Language.EN -> "While I am at my desk"
        Language.FA -> "وقتی پشت میزم هستم"
        Language.TR -> "Masamdayken"
    }

    fun pushWhenOffline(l: Language): String = when (l) {
        Language.EN -> "While I am away"
        Language.FA -> "وقتی دور از میزم هستم"
        Language.TR -> "Uzaktayken"
    }

    fun pushPresenceFooter(l: Language): String = when (l) {
        Language.EN -> "Webyar knows you are at your desk while the web console is open. Turn the first off to keep the phone quiet while you are already answering there."
        Language.FA -> "وب‌یار وقتی کنسول وب باز است می‌داند پشت میزتان هستید. اولی را خاموش کنید تا وقتی همان‌جا پاسخ می‌دهید، گوشی ساکت بماند."
        Language.TR -> "Web konsolu açıkken masanızda olduğunuz bilinir. Orada zaten yanıtlarken telefonun sessiz kalması için ilkini kapatın."
    }

    fun pushQuietHours(l: Language): String = when (l) {
        Language.EN -> "Quiet hours"
        Language.FA -> "ساعت‌های سکوت"
        Language.TR -> "Sessiz saatler"
    }

    fun pushQuietFrom(l: Language): String = when (l) {
        Language.EN -> "From"
        Language.FA -> "از"
        Language.TR -> "Başlangıç"
    }

    fun pushQuietTo(l: Language): String = when (l) {
        Language.EN -> "Until"
        Language.FA -> "تا"
        Language.TR -> "Bitiş"
    }

    fun pushQuietFooter(l: Language): String = when (l) {
        Language.EN -> "Nothing arrives inside this window, except someone mentioning you by name."
        Language.FA -> "در این بازه چیزی نمی‌رسد، مگر اینکه کسی نام شما را ببرد."
        Language.TR -> "Bu aralıkta, biri adınızı anmadıkça hiçbir şey ulaşmaz."
    }

    fun pushThisDevice(l: Language): String = when (l) {
        Language.EN -> "This phone"
        Language.FA -> "همین تلفن"
        Language.TR -> "Bu telefon"
    }

    fun pushDeviceRegistered(l: Language): String = when (l) {
        Language.EN -> "Registered and able to receive notifications."
        Language.FA -> "ثبت شده و آماده‌ی دریافت اعلان است."
        Language.TR -> "Kayıtlı ve bildirim alabilir durumda."
    }

    fun pushDeviceNotRegistered(l: Language): String = when (l) {
        Language.EN -> "Not registered yet."
        Language.FA -> "هنوز ثبت نشده است."
        Language.TR -> "Henüz kayıtlı değil."
    }

    fun deleteAccount(l: Language): String = when (l) {
        Language.EN -> "Delete account"
        Language.FA -> "حذف حساب"
        Language.TR -> "Hesabı sil"
    }

    fun deleteAccountBody(l: Language): String = when (l) {
        Language.EN -> "Your profile, your password, your workspace memberships, your notification preferences and every device you have signed in on are removed. This cannot be undone."
        Language.FA -> "نمایه، رمز عبور، عضویت‌هایتان در فضاهای کاری، تنظیمات اعلان و همه‌ی دستگاه‌هایی که با آن‌ها وارد شده‌اید پاک می‌شوند. این کار برگشت‌پذیر نیست."
        Language.TR -> "Profiliniz, parolanız, çalışma alanı üyelikleriniz, bildirim tercihleriniz ve giriş yaptığınız her cihaz kaldırılır. Bu işlem geri alınamaz."
    }

    /**
     * Said plainly, because it is the part people worry about and the part
     * that is genuinely reassuring.
     */
    fun deleteAccountKeeps(l: Language): String = when (l) {
        Language.EN -> "Conversations you handled stay with the workspace — they belong to the customer, not to you — but they stop being attributed to you."
        Language.FA -> "گفتگوهایی که رسیدگی کرده‌اید در فضای کاری می‌مانند — آن‌ها مال مشتری‌اند، نه شما — ولی دیگر به نام شما ثبت نمی‌شوند."
        Language.TR -> "İlgilendiğiniz konuşmalar çalışma alanında kalır — müşteriye aittir, size değil — ancak artık size atfedilmez."
    }

    fun deleteAccountConfirmPassword(l: Language): String = when (l) {
        Language.EN -> "Enter your password to confirm"
        Language.FA -> "برای تأیید، رمز عبورتان را وارد کنید"
        Language.TR -> "Onaylamak için parolanızı girin"
    }

    fun deleteAccountFinal(l: Language): String = when (l) {
        Language.EN -> "Delete my account"
        Language.FA -> "حساب من را حذف کن"
        Language.TR -> "Hesabımı sil"
    }

    fun deleteAccountWrongPassword(l: Language): String = when (l) {
        Language.EN -> "That password is not right."
        Language.FA -> "این رمز عبور درست نیست."
        Language.TR -> "Bu parola doğru değil."
    }

    /**
     * The one case the server refuses, and the only one worth a screen of
     * its own: an owner's profile cascades to their workspaces.
     */
    fun deleteAccountOwnsTitle(l: Language): String = when (l) {
        Language.EN -> "Hand these over first"
        Language.FA -> "اول این‌ها را واگذار کنید"
        Language.TR -> "Önce bunları devredin"
    }

    fun accountDeleted(l: Language): String = when (l) {
        Language.EN -> "Your account has been deleted."
        Language.FA -> "حساب شما حذف شد."
        Language.TR -> "Hesabınız silindi."
    }

    fun tabInbox(l: Language): String = when (l) {
        Language.EN -> "Inbox"
        Language.FA -> "صندوق"
        Language.TR -> "Gelen kutusu"
    }

    /**
     * What VoiceOver says of the dot on the Inbox tab. A template: `{count}`
     * is replaced with the number in the reader's digits.
     */
    fun tabUnread(l: Language): String = when (l) {
        Language.EN -> "{count} unread"
        Language.FA -> "{count} خوانده‌نشده"
        Language.TR -> "{count} okunmamış"
    }

    fun tabContacts(l: Language): String = when (l) {
        Language.EN -> "Contacts"
        Language.FA -> "مخاطبین"
        Language.TR -> "Kişiler"
    }

    fun tabSettings(l: Language): String = when (l) {
        Language.EN -> "Settings"
        Language.FA -> "تنظیمات"
        Language.TR -> "Ayarlar"
    }

    fun filterOpen(l: Language): String = when (l) {
        Language.EN -> "Open"
        Language.FA -> "باز"
        Language.TR -> "Açık"
    }

    /**
     * The AI queue. In full in Persian — "هوش" alone read as "intelligence"
     * rather than as the AI — which the strip has room for now that it holds
     * three segments, not four. "Yapay zekâ" is still too long for a third
     * of the control with a count, so Turkish keeps its usual "YZ".
     */
    fun filterAI(l: Language): String = when (l) {
        Language.EN -> "AI"
        Language.FA -> "هوش مصنوعی"
        Language.TR -> "YZ"
    }

    /**
     * The main queue narrowed to threads waiting on the customer, not on us.
     *
     * Named for who is being waited on rather than for the status word:
     * "Pending" alone leaves an operator guessing whose move it is, and the
     * whole point of the queue is that it is not theirs.
     */
    fun filterPending(l: Language): String = when (l) {
        Language.EN -> "Awaiting customer"
        Language.FA -> "در انتظار مشتری"
        Language.TR -> "Müşteri bekleniyor"
    }

    fun filterResolved(l: Language): String = when (l) {
        Language.EN -> "Resolved"
        Language.FA -> "حل‌شده"
        Language.TR -> "Çözüldü"
    }

    fun filterSpam(l: Language): String = when (l) {
        Language.EN -> "Spam"
        Language.FA -> "هرزنامه"
        Language.TR -> "Spam"
    }

    /** The menu behind the inbox title: every inbox this plan grants. */
    fun allInboxes(l: Language): String = when (l) {
        Language.EN -> "Inboxes"
        Language.FA -> "صندوق‌ها"
        Language.TR -> "Gelen kutuları"
    }

    fun otherInboxes(l: Language): String = when (l) {
        Language.EN -> "Other inboxes"
        Language.FA -> "صندوق‌های دیگر"
        Language.TR -> "Diğer gelen kutuları"
    }

    fun colleagues(l: Language): String = when (l) {
        Language.EN -> "Colleagues"
        Language.FA -> "همکاران"
        Language.TR -> "Meslektaşlar"
    }

    fun colleaguesEmptyTitle(l: Language): String = when (l) {
        Language.EN -> "No colleagues yet"
        Language.FA -> "هنوز همکاری نیست"
        Language.TR -> "Henüz meslektaş yok"
    }

    fun colleaguesEmptyBody(l: Language): String = when (l) {
        Language.EN -> "Operators invited to this workspace appear here."
        Language.FA -> "اپراتورهایی که به این فضای کاری دعوت شوند اینجا دیده می‌شوند."
        Language.TR -> "Bu çalışma alanına davet edilen operatörler burada görünür."
    }

    fun colleagueThreadEmpty(l: Language): String = when (l) {
        Language.EN -> "No messages yet"
        Language.FA -> "هنوز پیغامی نیست"
        Language.TR -> "Henüz mesaj yok"
    }

    fun availability(l: Language): String = when (l) {
        Language.EN -> "Availability"
        Language.FA -> "وضعیت دسترس‌پذیری"
        Language.TR -> "Uygunluk"
    }

    fun availabilitySeenAs(l: Language): String = when (l) {
        Language.EN -> "You are currently seen as"
        Language.FA -> "در حال حاضر شما این‌گونه دیده می‌شوید"
        Language.TR -> "Şu anda şöyle görünüyorsunuz"
    }

    fun availabilityOnline(l: Language): String = when (l) {
        Language.EN -> "Online"
        Language.FA -> "آنلاین"
        Language.TR -> "Çevrimiçi"
    }

    fun availabilityOffline(l: Language): String = when (l) {
        Language.EN -> "Offline"
        Language.FA -> "آفلاین"
        Language.TR -> "Çevrimdışı"
    }

    fun availabilityForceOffline(l: Language): String = when (l) {
        Language.EN -> "Force offline (invisible mode)"
        Language.FA -> "آفلاین اجباری (حالت نامرئی)"
        Language.TR -> "Zorla çevrimdışı (görünmez mod)"
    }

    fun availabilityForceOfflineHint(l: Language): String = when (l) {
        Language.EN -> "You appear offline to visitors whatever your schedule says."
        Language.FA -> "صرف‌نظر از زمان‌بندی، برای بازدیدکنندگان آفلاین دیده می‌شوید."
        Language.TR -> "Programınız ne derse desin ziyaretçilere çevrimdışı görünürsünüz."
    }

    fun availabilityWhenUsingApp(l: Language): String = when (l) {
        Language.EN -> "Available while I use the app"
        Language.FA -> "وقتی از برنامه استفاده می‌کنم، در دسترس باشم"
        Language.TR -> "Uygulamayı kullanırken uygunum"
    }

    fun availabilityWhenUsingAppHint(l: Language): String = when (l) {
        Language.EN -> "Marks you online automatically while the app is open."
        Language.FA -> "تا وقتی برنامه باز است، به‌صورت خودکار آنلاین در نظر گرفته می‌شوید."
        Language.TR -> "Uygulama açıkken sizi otomatik olarak çevrimiçi işaretler."
    }

    fun availabilitySchedule(l: Language): String = when (l) {
        Language.EN -> "Use my weekly schedule"
        Language.FA -> "از زمان‌بندی هفتگی‌ام استفاده کن"
        Language.TR -> "Haftalık programımı kullan"
    }

    fun availabilityScheduleHint(l: Language): String = when (l) {
        Language.EN -> "The hours themselves are set in the web console."
        Language.FA -> "خود ساعت‌ها را در کنسول وب تنظیم می‌کنید."
        Language.TR -> "Saatlerin kendisi web konsolundan ayarlanır."
    }

    fun availabilitySaveFailed(l: Language): String = when (l) {
        Language.EN -> "That did not save. Try again."
        Language.FA -> "ذخیره نشد. دوباره تلاش کنید."
        Language.TR -> "Kaydedilemedi. Tekrar deneyin."
    }

    fun emailInbox(l: Language): String = when (l) {
        Language.EN -> "Email"
        Language.FA -> "ایمیل"
        Language.TR -> "E-posta"
    }

    fun emailEmptyTitle(l: Language): String = when (l) {
        Language.EN -> "No email"
        Language.FA -> "ایمیلی نیست"
        Language.TR -> "E-posta yok"
    }

    fun emailEmptyBody(l: Language): String = when (l) {
        Language.EN -> "New mail in this mailbox will appear here."
        Language.FA -> "ایمیل‌های تازهٔ این صندوق اینجا نشان داده می‌شوند."
        Language.TR -> "Bu posta kutusuna gelen yeni e-postalar burada görünür."
    }

    fun emailNotConnectedTitle(l: Language): String = when (l) {
        Language.EN -> "Mailbox not connected"
        Language.FA -> "صندوق ایمیل وصل نیست"
        Language.TR -> "Posta kutusu bağlı değil"
    }

    fun emailNotConnectedBody(l: Language): String = when (l) {
        Language.EN -> "Connect a mailbox in the web console under Email, then it will open here too."
        Language.FA -> "در کنسول وب، بخش ایمیل، یک صندوق وصل کنید؛ بعد از آن اینجا هم باز می‌شود."
        Language.TR -> "Web konsolunda E-posta bölümünden bir posta kutusu bağlayın; sonra burada da açılır."
    }

    fun emailNoSubject(l: Language): String = when (l) {
        Language.EN -> "(no subject)"
        Language.FA -> "(بدون موضوع)"
        Language.TR -> "(konu yok)"
    }

    fun emailReply(l: Language): String = when (l) {
        Language.EN -> "Reply"
        Language.FA -> "پاسخ"
        Language.TR -> "Yanıtla"
    }

    fun emailReplyPlaceholder(l: Language): String = when (l) {
        Language.EN -> "Write a reply"
        Language.FA -> "پاسخ بنویسید"
        Language.TR -> "Bir yanıt yazın"
    }

    fun emailSend(l: Language): String = when (l) {
        Language.EN -> "Send"
        Language.FA -> "ارسال"
        Language.TR -> "Gönder"
    }

    fun emailStar(l: Language): String = when (l) {
        Language.EN -> "Star"
        Language.FA -> "ستاره"
        Language.TR -> "Yıldız"
    }

    fun emailMarkUnread(l: Language): String = when (l) {
        Language.EN -> "Mark as unread"
        Language.FA -> "علامت خوانده‌نشده"
        Language.TR -> "Okunmadı olarak işaretle"
    }

    fun emailSendFailed(l: Language): String = when (l) {
        Language.EN -> "The reply was not sent. Try again."
        Language.FA -> "پاسخ فرستاده نشد. دوباره تلاش کنید."
        Language.TR -> "Yanıt gönderilemedi. Tekrar deneyin."
    }

    fun inboxEmptyTitle(l: Language): String = when (l) {
        Language.EN -> "No conversations"
        Language.FA -> "گفت‌وگویی نیست"
        Language.TR -> "Görüşme yok"
    }

    fun inboxEmptyBody(l: Language): String = when (l) {
        Language.EN -> "New conversations will appear here as visitors reach out."
        Language.FA -> "گفت‌وگوهای تازه با پیام بازدیدکنندگان همین‌جا ظاهر می‌شوند."
        Language.TR -> "Ziyaretçiler yazdıkça yeni görüşmeler burada görünür."
    }

    fun markResolved(l: Language): String = when (l) {
        Language.EN -> "Resolve"
        Language.FA -> "حل شد"
        Language.TR -> "Çöz"
    }

    fun reopen(l: Language): String = when (l) {
        Language.EN -> "Reopen"
        Language.FA -> "بازگشایی"
        Language.TR -> "Yeniden aç"
    }

    fun messagePlaceholder(l: Language): String = when (l) {
        Language.EN -> "Message"
        Language.FA -> "پیام"
        Language.TR -> "Mesaj"
    }

    fun send(l: Language): String = when (l) {
        Language.EN -> "Send"
        Language.FA -> "ارسال"
        Language.TR -> "Gönder"
    }

    fun chatEmpty(l: Language): String = when (l) {
        Language.EN -> "No messages yet"
        Language.FA -> "هنوز پیامی نیست"
        Language.TR -> "Henüz mesaj yok"
    }

    fun aiReply(l: Language): String = when (l) {
        Language.EN -> "AI"
        Language.FA -> "هوش مصنوعی"
        Language.TR -> "Yapay zekâ"
    }

    fun systemNote(l: Language): String = when (l) {
        Language.EN -> "System"
        Language.FA -> "سیستم"
        Language.TR -> "Sistem"
    }

    fun contactsEmptyTitle(l: Language): String = when (l) {
        Language.EN -> "No contacts"
        Language.FA -> "مخاطبی نیست"
        Language.TR -> "Kişi yok"
    }

    fun contactsEmptyBody(l: Language): String = when (l) {
        Language.EN -> "People who talk to you are added here automatically."
        Language.FA -> "کسانی که با شما گفت‌وگو کنند خودکار این‌جا افزوده می‌شوند."
        Language.TR -> "Sizinle konuşan kişiler buraya otomatik eklenir."
    }

    fun noResults(l: Language): String = when (l) {
        Language.EN -> "No results"
        Language.FA -> "نتیجه‌ای نیست"
        Language.TR -> "Sonuç yok"
    }

    fun account(l: Language): String = when (l) {
        Language.EN -> "Account"
        Language.FA -> "حساب کاربری"
        Language.TR -> "Hesap"
    }

    fun language(l: Language): String = when (l) {
        Language.EN -> "Language"
        Language.FA -> "زبان"
        Language.TR -> "Dil"
    }

    fun workspace(l: Language): String = when (l) {
        Language.EN -> "Workspace"
        Language.FA -> "فضای کاری"
        Language.TR -> "Çalışma alanı"
    }

    fun about(l: Language): String = when (l) {
        Language.EN -> "About"
        Language.FA -> "درباره"
        Language.TR -> "Hakkında"
    }

    /**
     * Settings → About, and the one way forward for an owner who wants their
     * account removed.
     */
    fun support(l: Language): String = when (l) {
        Language.EN -> "Support"
        Language.FA -> "پشتیبانی"
        Language.TR -> "Destek"
    }

    fun version(l: Language): String = when (l) {
        Language.EN -> "Version"
        Language.FA -> "نسخه"
        Language.TR -> "Sürüm"
    }

    fun signOut(l: Language): String = when (l) {
        Language.EN -> "Sign out"
        Language.FA -> "خروج از حساب"
        Language.TR -> "Çıkış yap"
    }

    fun signOutConfirm(l: Language): String = when (l) {
        Language.EN -> "Sign out of Webyar?"
        Language.FA -> "از وب‌یار خارج می‌شوید؟"
        Language.TR -> "Webyar'dan çıkılsın mı?"
    }

    fun signOutFailed(l: Language): String = when (l) {
        Language.EN -> "Sign out failed. You are still signed in."
        Language.FA -> "خروج انجام نشد. هنوز وارد حساب هستید."
        Language.TR -> "Çıkış yapılamadı. Hâlâ oturumunuz açık."
    }

    /**
     * Deliberately terse: with four queues and a count beside each, a longer
     * label truncates mid-word in the segmented control.
     */
    fun filterNeedsHuman(l: Language): String = when (l) {
        Language.EN -> "Needs me"
        Language.FA -> "با شما"
        Language.TR -> "Sizde"
    }

    fun claim(l: Language): String = when (l) {
        Language.EN -> "Assign to me"
        Language.FA -> "به من بسپار"
        Language.TR -> "Bana ata"
    }

    fun assignedToYou(l: Language): String = when (l) {
        Language.EN -> "Yours"
        Language.FA -> "مال شما"
        Language.TR -> "Sizde"
    }

    fun priorityUrgent(l: Language): String = when (l) {
        Language.EN -> "Urgent"
        Language.FA -> "فوری"
        Language.TR -> "Acil"
    }

    fun priorityHigh(l: Language): String = when (l) {
        Language.EN -> "High"
        Language.FA -> "زیاد"
        Language.TR -> "Yüksek"
    }

    fun profile(l: Language): String = when (l) {
        Language.EN -> "Profile"
        Language.FA -> "نمایه"
        Language.TR -> "Profil"
    }

    fun displayName(l: Language): String = when (l) {
        Language.EN -> "Name"
        Language.FA -> "نام"
        Language.TR -> "Ad"
    }

    /**
     * The account form asks for the two parts rather than one "Name": the
     * route stores a composed `full_name` but accepts `first_name` and
     * `last_name`, and a family name is optional where a given name is not.
     */
    fun firstName(l: Language): String = when (l) {
        Language.EN -> "First name"
        Language.FA -> "نام"
        Language.TR -> "Ad"
    }

    fun lastName(l: Language): String = when (l) {
        Language.EN -> "Last name"
        Language.FA -> "نام خانوادگی"
        Language.TR -> "Soyad"
    }

    fun phoneLabel(l: Language): String = when (l) {
        Language.EN -> "Phone number"
        Language.FA -> "شماره تلفن"
        Language.TR -> "Telefon numarası"
    }

    fun changePhoto(l: Language): String = when (l) {
        Language.EN -> "Change photo"
        Language.FA -> "تغییر عکس"
        Language.TR -> "Fotoğrafı değiştir"
    }

    fun removePhoto(l: Language): String = when (l) {
        Language.EN -> "Remove photo"
        Language.FA -> "حذف عکس"
        Language.TR -> "Fotoğrafı kaldır"
    }

    fun save(l: Language): String = when (l) {
        Language.EN -> "Save"
        Language.FA -> "ذخیره"
        Language.TR -> "Kaydet"
    }

    fun saved(l: Language): String = when (l) {
        Language.EN -> "Saved"
        Language.FA -> "ذخیره شد"
        Language.TR -> "Kaydedildi"
    }

    fun saveFailed(l: Language): String = when (l) {
        Language.EN -> "Could not save. Try again."
        Language.FA -> "ذخیره نشد. دوباره تلاش کنید."
        Language.TR -> "Kaydedilemedi. Tekrar deneyin."
    }

    fun photoTooLarge(l: Language): String = when (l) {
        Language.EN -> "That image is too large. Pick a smaller one."
        Language.FA -> "این تصویر خیلی بزرگ است. کوچک‌تری انتخاب کنید."
        Language.TR -> "Bu görsel çok büyük. Daha küçüğünü seçin."
    }

    fun security(l: Language): String = when (l) {
        Language.EN -> "Security"
        Language.FA -> "امنیت"
        Language.TR -> "Güvenlik"
    }

    fun changePassword(l: Language): String = when (l) {
        Language.EN -> "Change password"
        Language.FA -> "تغییر رمز عبور"
        Language.TR -> "Parolayı değiştir"
    }

    fun currentPassword(l: Language): String = when (l) {
        Language.EN -> "Current password"
        Language.FA -> "رمز عبور فعلی"
        Language.TR -> "Mevcut parola"
    }

    fun newPassword(l: Language): String = when (l) {
        Language.EN -> "New password"
        Language.FA -> "رمز عبور تازه"
        Language.TR -> "Yeni parola"
    }

    fun passwordChanged(l: Language): String = when (l) {
        Language.EN -> "Password changed"
        Language.FA -> "رمز عبور عوض شد"
        Language.TR -> "Parola değiştirildi"
    }

    fun passwordTooShort(l: Language): String = when (l) {
        Language.EN -> "Use at least 8 characters."
        Language.FA -> "دست‌کم ۸ نویسه بگذارید."
        Language.TR -> "En az 8 karakter kullanın."
    }

    fun activeSessions(l: Language): String = when (l) {
        Language.EN -> "Signed-in devices"
        Language.FA -> "دستگاه‌های واردشده"
        Language.TR -> "Oturum açık cihazlar"
    }

    fun thisDevice(l: Language): String = when (l) {
        Language.EN -> "This device"
        Language.FA -> "همین دستگاه"
        Language.TR -> "Bu cihaz"
    }

    /**
     * The button on a device row. Short, because it sits at the end of a
     * line that already says which device — `revokeSession` is the swipe
     * action's label and says the whole sentence.
     */
    fun signOutDevice(l: Language): String = when (l) {
        Language.EN -> "Sign out"
        Language.FA -> "خروج"
        Language.TR -> "Çıkış"
    }

    fun revokeSession(l: Language): String = when (l) {
        Language.EN -> "Sign out this device"
        Language.FA -> "خروج این دستگاه"
        Language.TR -> "Bu cihazdan çık"
    }

    fun lastActive(l: Language): String = when (l) {
        Language.EN -> "Last active"
        Language.FA -> "آخرین فعالیت"
        Language.TR -> "Son etkinlik"
    }

    fun appearance(l: Language): String = when (l) {
        Language.EN -> "Appearance"
        Language.FA -> "ظاهر"
        Language.TR -> "Görünüm"
    }

    fun appearanceSystem(l: Language): String = when (l) {
        Language.EN -> "Match device"
        Language.FA -> "مطابق دستگاه"
        Language.TR -> "Cihazla aynı"
    }

    fun appearanceLight(l: Language): String = when (l) {
        Language.EN -> "Light"
        Language.FA -> "روشن"
        Language.TR -> "Açık"
    }

    fun appearanceDark(l: Language): String = when (l) {
        Language.EN -> "Dark"
        Language.FA -> "تیره"
        Language.TR -> "Koyu"
    }

    fun plan(l: Language): String = when (l) {
        Language.EN -> "Plan"
        Language.FA -> "پلن"
        Language.TR -> "Plan"
    }

    fun emailNotVerified(l: Language): String = when (l) {
        Language.EN -> "Email not verified"
        Language.FA -> "ایمیل تأیید نشده"
        Language.TR -> "E-posta doğrulanmadı"
    }

    fun attachFile(l: Language): String = when (l) {
        Language.EN -> "Attach a file"
        Language.FA -> "پیوست فایل"
        Language.TR -> "Dosya ekle"
    }

    fun voiceNote(l: Language): String = when (l) {
        Language.EN -> "Voice note"
        Language.FA -> "پیام صوتی"
        Language.TR -> "Sesli not"
    }

    fun shortcuts(l: Language): String = when (l) {
        Language.EN -> "Shortcuts"
        Language.FA -> "میان‌برها"
        Language.TR -> "Kısayollar"
    }

    fun searchShortcuts(l: Language): String = when (l) {
        Language.EN -> "Search shortcuts"
        Language.FA -> "جست‌وجوی میان‌برها"
        Language.TR -> "Kısayollarda ara"
    }

    fun shortcutsEmptyTitle(l: Language): String = when (l) {
        Language.EN -> "No saved replies yet"
        Language.FA -> "هنوز پاسخ آماده‌ای نیست"
        Language.TR -> "Henüz hazır yanıt yok"
    }

    fun shortcutsEmptyBody(l: Language): String = when (l) {
        Language.EN -> "Add them in the console under Settings → Shortcuts. Everyone in the workspace can use them."
        Language.FA -> "در کنسول، از تنظیمات ← میان‌برها اضافه‌شان کنید. همهٔ اعضای فضای کاری می‌توانند از آن‌ها استفاده کنند."
        Language.TR -> "Konsolda Ayarlar → Kısayollar altından ekleyin. Çalışma alanındaki herkes kullanabilir."
    }

    fun shortcutsUnavailableTitle(l: Language): String = when (l) {
        Language.EN -> "Shortcuts are not set up on this server"
        Language.FA -> "میان‌برها روی این سرور راه‌اندازی نشده‌اند"
        Language.TR -> "Kısayollar bu sunucuda kurulu değil"
    }

    fun shortcutsUnavailableBody(l: Language): String = when (l) {
        Language.EN -> "Your administrator can enable them by bringing the database up to date."
        Language.FA -> "مدیر سامانه می‌تواند با به‌روزرسانی پایگاه داده فعالشان کند."
        Language.TR -> "Yöneticiniz veritabanını güncelleyerek etkinleştirebilir."
    }

    fun emoji(l: Language): String = when (l) {
        Language.EN -> "Emoji"
        Language.FA -> "شکلک"
        Language.TR -> "Emoji"
    }

    fun offlineTitle(l: Language): String = when (l) {
        Language.EN -> "Can't reach the server"
        Language.FA -> "دسترسی به سرور ممکن نشد"
        Language.TR -> "Sunucuya ulaşılamıyor"
    }

    fun offlineBody(l: Language): String = when (l) {
        Language.EN -> "Check your connection and try again."
        Language.FA -> "اتصال خود را بررسی کنید و دوباره تلاش کنید."
        Language.TR -> "Bağlantınızı kontrol edip tekrar deneyin."
    }

    /**
     * Above conversations the phone saved earlier, when the server cannot
     * be reached right now.
     */
    fun offlineSavedCopy(l: Language): String = when (l) {
        Language.EN -> "Offline — showing what was saved on this phone."
        Language.FA -> "آفلاین — آنچه روی این گوشی ذخیره شده نمایش داده می‌شود."
        Language.TR -> "Çevrimdışı — bu telefonda kayıtlı olanlar gösteriliyor."
    }

    /** Read aloud for a message that has not reached the server yet. */
    fun messageSending(l: Language): String = when (l) {
        Language.EN -> "Sending"
        Language.FA -> "در حال ارسال"
        Language.TR -> "Gönderiliyor"
    }

    fun storage(l: Language): String = when (l) {
        Language.EN -> "Storage"
        Language.FA -> "فضای ذخیره‌سازی"
        Language.TR -> "Depolama"
    }

    fun storageConversations(l: Language): String = when (l) {
        Language.EN -> "Saved conversations"
        Language.FA -> "گفتگوهای ذخیره‌شده"
        Language.TR -> "Kayıtlı konuşmalar"
    }

    fun storageFiles(l: Language): String = when (l) {
        Language.EN -> "Files and media"
        Language.FA -> "فایل‌ها و رسانه‌ها"
        Language.TR -> "Dosyalar ve medya"
    }

    fun storagePictures(l: Language): String = when (l) {
        Language.EN -> "Pictures"
        Language.FA -> "تصاویر پروفایل"
        Language.TR -> "Profil resimleri"
    }

    fun storageTotal(l: Language): String = when (l) {
        Language.EN -> "Total"
        Language.FA -> "مجموع"
        Language.TR -> "Toplam"
    }

    fun storageFooter(l: Language): String = when (l) {
        Language.EN -> "Copies kept on this phone so conversations open at once and files are not downloaded twice. Clearing them removes nothing from the server and does not sign you out."
        Language.FA -> "نسخه‌هایی که روی این گوشی نگه داشته می‌شوند تا گفتگوها فوراً باز شوند و فایل‌ها دوباره دانلود نشوند. پاک کردن آن‌ها چیزی را از سرور حذف نمی‌کند و شما را از حساب خارج نمی‌کند."
        Language.TR -> "Konuşmaların hemen açılması ve dosyaların iki kez indirilmemesi için bu telefonda tutulan kopyalar. Silmek sunucudan hiçbir şeyi kaldırmaz ve oturumunuzu kapatmaz."
    }

    fun clearCache(l: Language): String = when (l) {
        Language.EN -> "Clear Cache"
        Language.FA -> "پاک کردن حافظهٔ موقت"
        Language.TR -> "Önbelleği Temizle"
    }

    fun clearCacheConfirm(l: Language): String = when (l) {
        Language.EN -> "Remove the copies saved on this phone? They will be downloaded again as needed."
        Language.FA -> "نسخه‌های ذخیره‌شده روی این گوشی حذف شوند؟ در صورت نیاز دوباره دانلود می‌شوند."
        Language.TR -> "Bu telefonda kayıtlı kopyalar kaldırılsın mı? Gerektiğinde yeniden indirilecekler."
    }

    fun sessionExpired(l: Language): String = when (l) {
        Language.EN -> "Your session expired. Please sign in again."
        Language.FA -> "نشست شما منقضی شد. دوباره وارد شوید."
        Language.TR -> "Oturumunuzun süresi doldu. Lütfen tekrar giriş yapın."
    }

    fun errorInvalidInput(l: Language): String = when (l) {
        Language.EN -> "Something in that request wasn't valid."
        Language.FA -> "اطلاعات واردشده درست نیست."
        Language.TR -> "Gönderilen bilgiler geçerli değil."
    }

    fun errorNotAllowed(l: Language): String = when (l) {
        Language.EN -> "You don't have access to do that."
        Language.FA -> "برای این کار دسترسی ندارید."
        Language.TR -> "Bu işlem için yetkiniz yok."
    }

    fun errorNotFound(l: Language): String = when (l) {
        Language.EN -> "That couldn't be found."
        Language.FA -> "این مورد پیدا نشد."
        Language.TR -> "Bu kayıt bulunamadı."
    }

    fun errorConflict(l: Language): String = when (l) {
        Language.EN -> "That changed since you opened it. Try again."
        Language.FA -> "این مورد در این فاصله تغییر کرده است. دوباره تلاش کنید."
        Language.TR -> "Bu kayıt siz açtıktan sonra değişti. Tekrar deneyin."
    }

    fun errorTooManyRequests(l: Language): String = when (l) {
        Language.EN -> "Too many attempts. Wait a moment and try again."
        Language.FA -> "تلاش‌ها بیش از حد بود. کمی صبر کنید و دوباره تلاش کنید."
        Language.TR -> "Çok fazla deneme yapıldı. Biraz bekleyip tekrar deneyin."
    }

    fun errorServerProblem(l: Language): String = when (l) {
        Language.EN -> "The server ran into a problem. Try again shortly."
        Language.FA -> "سرور به مشکل خورد. کمی بعد دوباره تلاش کنید."
        Language.TR -> "Sunucuda bir sorun oluştu. Birazdan tekrar deneyin."
    }

    fun errorUnreadableAnswer(l: Language): String = when (l) {
        Language.EN -> "The server's answer couldn't be read. Update the app if this keeps happening."
        Language.FA -> "پاسخ سرور خوانده نشد. اگر تکرار شد، اپ را به‌روز کنید."
        Language.TR -> "Sunucunun yanıtı okunamadı. Sorun sürerse uygulamayı güncelleyin."
    }

    fun unknownVisitor(l: Language): String = when (l) {
        Language.EN -> "Visitor"
        Language.FA -> "بازدیدکننده"
        Language.TR -> "Ziyaretçi"
    }

    fun filters(l: Language): String = when (l) {
        Language.EN -> "Filters"
        Language.FA -> "پالایه‌ها"
        Language.TR -> "Filtreler"
    }

    fun clearFilters(l: Language): String = when (l) {
        Language.EN -> "Clear"
        Language.FA -> "پاک کردن"
        Language.TR -> "Temizle"
    }

    fun apply(l: Language): String = when (l) {
        Language.EN -> "Apply"
        Language.FA -> "اعمال"
        Language.TR -> "Uygula"
    }

    fun done(l: Language): String = when (l) {
        Language.EN -> "Done"
        Language.FA -> "تمام"
        Language.TR -> "Bitti"
    }

    fun filterByName(l: Language): String = when (l) {
        Language.EN -> "Contact name"
        Language.FA -> "نام مخاطب"
        Language.TR -> "Kişi adı"
    }

    fun filterByEmail(l: Language): String = when (l) {
        Language.EN -> "Email address"
        Language.FA -> "نشانی ایمیل"
        Language.TR -> "E-posta adresi"
    }

    fun filterBySubject(l: Language): String = when (l) {
        Language.EN -> "Subject"
        Language.FA -> "موضوع"
        Language.TR -> "Konu"
    }

    fun conversationActions(l: Language): String = when (l) {
        Language.EN -> "Conversation"
        Language.FA -> "گفت‌وگو"
        Language.TR -> "Görüşme"
    }

    fun transferConversation(l: Language): String = when (l) {
        Language.EN -> "Transfer"
        Language.FA -> "انتقال مکالمه"
        Language.TR -> "Aktar"
    }

    fun changeStatus(l: Language): String = when (l) {
        Language.EN -> "Status"
        Language.FA -> "وضعیت مکالمه"
        Language.TR -> "Durum"
    }

    fun changePriority(l: Language): String = when (l) {
        Language.EN -> "Priority"
        Language.FA -> "اولویت"
        Language.TR -> "Öncelik"
    }

    fun tags(l: Language): String = when (l) {
        Language.EN -> "Tags"
        Language.FA -> "برچسب‌ها"
        Language.TR -> "Etiketler"
    }

    fun addTag(l: Language): String = when (l) {
        Language.EN -> "Add a tag"
        Language.FA -> "افزودن برچسب"
        Language.TR -> "Etiket ekle"
    }

    fun noTags(l: Language): String = when (l) {
        Language.EN -> "No tags yet"
        Language.FA -> "هنوز برچسبی نیست"
        Language.TR -> "Henüz etiket yok"
    }

    fun internalNotes(l: Language): String = when (l) {
        Language.EN -> "Internal notes"
        Language.FA -> "یادداشت داخلی"
        Language.TR -> "İç notlar"
    }

    fun notesPrivacyNote(l: Language): String = when (l) {
        Language.EN -> "Only your team can see these. The visitor never does."
        Language.FA -> "فقط هم‌تیمی‌های شما این‌ها را می‌بینند؛ بازدیدکننده هرگز."
        Language.TR -> "Bunları yalnızca ekibiniz görür; ziyaretçi asla görmez."
    }

    fun noNotes(l: Language): String = when (l) {
        Language.EN -> "No notes yet"
        Language.FA -> "هنوز یادداشتی نیست"
        Language.TR -> "Henüz not yok"
    }

    fun writeNote(l: Language): String = when (l) {
        Language.EN -> "Write a note"
        Language.FA -> "یادداشتی بنویسید"
        Language.TR -> "Bir not yazın"
    }

    fun unassigned(l: Language): String = when (l) {
        Language.EN -> "Unassigned"
        Language.FA -> "بدون مسئول"
        Language.TR -> "Atanmamış"
    }

    fun statusPending(l: Language): String = when (l) {
        Language.EN -> "Pending"
        Language.FA -> "در انتظار"
        Language.TR -> "Beklemede"
    }

    fun statusClosed(l: Language): String = when (l) {
        Language.EN -> "Closed"
        Language.FA -> "بسته"
        Language.TR -> "Kapalı"
    }

    fun priorityLow(l: Language): String = when (l) {
        Language.EN -> "Low"
        Language.FA -> "کم"
        Language.TR -> "Düşük"
    }

    fun priorityNormal(l: Language): String = when (l) {
        Language.EN -> "Normal"
        Language.FA -> "عادی"
        Language.TR -> "Normal"
    }

    fun voiceCall(l: Language): String = when (l) {
        Language.EN -> "Voice call"
        Language.FA -> "تماس صوتی"
        Language.TR -> "Sesli arama"
    }

    fun videoCall(l: Language): String = when (l) {
        Language.EN -> "Video call"
        Language.FA -> "تماس تصویری"
        Language.TR -> "Görüntülü arama"
    }

    fun inviteSent(l: Language): String = when (l) {
        Language.EN -> "Waiting for the visitor to accept"
        Language.FA -> "در انتظار پذیرش بازدیدکننده"
        Language.TR -> "Ziyaretçinin kabul etmesi bekleniyor"
    }

    fun inviteFailed(l: Language): String = when (l) {
        Language.EN -> "The call could not be started"
        Language.FA -> "تماس آغاز نشد"
        Language.TR -> "Arama başlatılamadı"
    }

    fun connectingCall(l: Language): String = when (l) {
        Language.EN -> "Connecting…"
        Language.FA -> "در حال اتصال…"
        Language.TR -> "Bağlanıyor…"
    }

    fun hangUpCall(l: Language): String = when (l) {
        Language.EN -> "End"
        Language.FA -> "پایان"
        Language.TR -> "Bitir"
    }

    fun mute(l: Language): String = when (l) {
        Language.EN -> "Mute"
        Language.FA -> "بی‌صدا"
        Language.TR -> "Sessiz"
    }

    fun camera(l: Language): String = when (l) {
        Language.EN -> "Camera"
        Language.FA -> "دوربین"
        Language.TR -> "Kamera"
    }

    fun speaker(l: Language): String = when (l) {
        Language.EN -> "Speaker"
        Language.FA -> "بلندگو"
        Language.TR -> "Hoparlör"
    }

    fun callEnded(l: Language): String = when (l) {
        Language.EN -> "Call ended"
        Language.FA -> "تماس پایان یافت"
        Language.TR -> "Arama bitti"
    }

    fun callDeclined(l: Language): String = when (l) {
        Language.EN -> "The visitor declined"
        Language.FA -> "بازدیدکننده نپذیرفت"
        Language.TR -> "Ziyaretçi reddetti"
    }

    fun callNoAnswer(l: Language): String = when (l) {
        Language.EN -> "No answer"
        Language.FA -> "پاسخی داده نشد"
        Language.TR -> "Yanıt yok"
    }

    fun callFailed(l: Language): String = when (l) {
        Language.EN -> "The call could not connect"
        Language.FA -> "تماس برقرار نشد"
        Language.TR -> "Arama bağlanamadı"
    }

    fun callRelayWarning(l: Language): String = when (l) {
        Language.EN -> "No relay server configured — this call may fail on some networks"
        Language.FA -> "سرور رله تنظیم نشده — ممکن است روی بعضی شبکه‌ها برقرار نشود"
        Language.TR -> "Röle sunucusu tanımlı değil — bazı ağlarda bağlanmayabilir"
    }

    fun callNoMicrophone(l: Language): String = when (l) {
        Language.EN -> "Your microphone is unavailable — they cannot hear you"
        Language.FA -> "میکروفون در دسترس نیست — صدای شما را نمی‌شنوند"
        Language.TR -> "Mikrofonunuz kullanılamıyor — sizi duyamıyorlar"
    }

    fun callNoCamera(l: Language): String = when (l) {
        Language.EN -> "Camera unavailable — continuing with audio only"
        Language.FA -> "دوربین در دسترس نیست — تماس فقط صوتی ادامه دارد"
        Language.TR -> "Kamera kullanılamıyor — yalnızca sesle devam ediliyor"
    }

    fun sysAgentJoinedGeneric(l: Language): String = when (l) {
        Language.EN -> "A colleague joined the conversation"
        Language.FA -> "یکی از همکاران به گفتگو پیوست"
        Language.TR -> "Bir meslektaşımız sohbete katıldı"
    }

    fun sysNoAgentAvailable(l: Language): String = when (l) {
        Language.EN -> "All our colleagues are currently busy. Your message was recorded and we'll respond as soon as we can."
        Language.FA -> "همه همکاران در حال حاضر مشغول هستند. پیام شما ثبت شد و در اولین فرصت پاسخ می‌دهیم."
        Language.TR -> "Tüm ekibimiz şu anda meşgul. Mesajınız kaydedildi, en kısa sürede yanıtlayacağız."
    }

    fun sysInQueue(l: Language): String = when (l) {
        Language.EN -> "You are in the queue — someone will be with you shortly."
        Language.FA -> "در صف هستید — به‌زودی همکاری پاسخ می‌دهد."
        Language.TR -> "Sıradasınız — kısa süre içinde bir ekip arkadaşımız yanıtlayacak."
    }

    fun sysCallInviteAudio(l: Language): String = when (l) {
        Language.EN -> "Visitor invited to an audio call"
        Language.FA -> "کاربر به تماس صوتی دعوت شد"
        Language.TR -> "Ziyaretçi sesli aramaya davet edildi"
    }

    fun sysCallInviteVideo(l: Language): String = when (l) {
        Language.EN -> "Visitor invited to a video call"
        Language.FA -> "کاربر به تماس تصویری دعوت شد"
        Language.TR -> "Ziyaretçi görüntülü aramaya davet edildi"
    }

    fun callEndedNotConnected(l: Language): String = when (l) {
        Language.EN -> "Call did not connect"
        Language.FA -> "تماس برقرار نشد"
        Language.TR -> "Görüşme bağlanamadı"
    }

    fun inviteStatusPending(l: Language): String = when (l) {
        Language.EN -> "Pending"
        Language.FA -> "در انتظار"
        Language.TR -> "Bekliyor"
    }

    fun inviteStatusJoined(l: Language): String = when (l) {
        Language.EN -> "Joined"
        Language.FA -> "پیوست"
        Language.TR -> "Katıldı"
    }

    fun inviteStatusExpired(l: Language): String = when (l) {
        Language.EN -> "Expired"
        Language.FA -> "منقضی"
        Language.TR -> "Süresi doldu"
    }

    fun inviteStatusCancelled(l: Language): String = when (l) {
        Language.EN -> "Cancelled"
        Language.FA -> "لغو شد"
        Language.TR -> "İptal edildi"
    }

    fun inviteStatusDeclined(l: Language): String = when (l) {
        Language.EN -> "Declined"
        Language.FA -> "رد شد"
        Language.TR -> "Reddedildi"
    }

    fun previewSomeone(l: Language): String = when (l) {
        Language.EN -> "A user"
        Language.FA -> "کاربر"
        Language.TR -> "Bir kullanıcı"
    }

    fun previewYouSentImage(l: Language): String = when (l) {
        Language.EN -> "You sent a photo"
        Language.FA -> "شما یک تصویر ارسال کردید"
        Language.TR -> "Bir fotoğraf gönderdiniz"
    }

    fun previewYouSentAudio(l: Language): String = when (l) {
        Language.EN -> "You sent a voice message"
        Language.FA -> "شما یک پیام صوتی ارسال کردید"
        Language.TR -> "Bir sesli mesaj gönderdiniz"
    }

    fun previewYouSentVideo(l: Language): String = when (l) {
        Language.EN -> "You sent a video"
        Language.FA -> "شما یک ویدیو ارسال کردید"
        Language.TR -> "Bir video gönderdiniz"
    }

    fun previewYouSentFile(l: Language): String = when (l) {
        Language.EN -> "You sent a file"
        Language.FA -> "شما یک فایل ارسال کردید"
        Language.TR -> "Bir dosya gönderdiniz"
    }

    fun deviceDesktop(l: Language): String = when (l) {
        Language.EN -> "Desktop"
        Language.FA -> "رایانه رومیزی"
        Language.TR -> "Masaüstü"
    }

    fun deviceMobile(l: Language): String = when (l) {
        Language.EN -> "Mobile"
        Language.FA -> "موبایل"
        Language.TR -> "Mobil"
    }

    fun deviceTablet(l: Language): String = when (l) {
        Language.EN -> "Tablet"
        Language.FA -> "تبلت"
        Language.TR -> "Tablet"
    }

    /**
     * Shown while the bytes are on their way. Taken from the console's
     * `inbox.receivingFile`, so the two read the same.
     */
    fun receivingFile(l: Language): String = when (l) {
        Language.EN -> "Receiving…"
        Language.FA -> "در حال دریافت…"
        Language.TR -> "Alınıyor…"
    }

    fun attachmentFailed(l: Language): String = when (l) {
        Language.EN -> "Could not load this file."
        Language.FA -> "این فایل بارگیری نشد."
        Language.TR -> "Bu dosya yüklenemedi."
    }

    /**
     * For a recording in a format this phone has no decoder for — an Opus
     * voice note from Telegram, say. The file is still there; only playing
     * it here is not possible.
     */
    fun playbackUnsupported(l: Language): String = when (l) {
        Language.EN -> "This format can't be played here."
        Language.FA -> "این قالب اینجا پخش نمی‌شود."
        Language.TR -> "Bu biçim burada oynatılamıyor."
    }

    fun photo(l: Language): String = when (l) {
        Language.EN -> "Photo"
        Language.FA -> "تصویر"
        Language.TR -> "Fotoğraf"
    }

    fun videoFile(l: Language): String = when (l) {
        Language.EN -> "Video"
        Language.FA -> "ویدیو"
        Language.TR -> "Video"
    }

    fun file(l: Language): String = when (l) {
        Language.EN -> "File"
        Language.FA -> "فایل"
        Language.TR -> "Dosya"
    }

    fun notNow(l: Language): String = when (l) {
        Language.EN -> "Not now"
        Language.FA -> "الان نه"
        Language.TR -> "Şimdi değil"
    }

    fun close(l: Language): String = when (l) {
        Language.EN -> "Close"
        Language.FA -> "بستن"
        Language.TR -> "Kapat"
    }

    /**
     * Byte units. Latin abbreviations in English and Turkish; Persian has its
     * own words for these and the console uses them.
     */
    fun unitBytes(l: Language): String = when (l) {
        Language.EN -> "B"
        Language.FA -> "بایت"
        Language.TR -> "B"
    }

    fun unitKilobytes(l: Language): String = when (l) {
        Language.EN -> "KB"
        Language.FA -> "کیلوبایت"
        Language.TR -> "KB"
    }

    fun unitMegabytes(l: Language): String = when (l) {
        Language.EN -> "MB"
        Language.FA -> "مگابایت"
        Language.TR -> "MB"
    }

    fun sendPhoto(l: Language): String = when (l) {
        Language.EN -> "Photo or video"
        Language.FA -> "تصویر یا ویدیو"
        Language.TR -> "Fotoğraf veya video"
    }

    fun sendDocument(l: Language): String = when (l) {
        Language.EN -> "Document"
        Language.FA -> "سند"
        Language.TR -> "Belge"
    }

    fun sendingFile(l: Language): String = when (l) {
        Language.EN -> "Sending…"
        Language.FA -> "در حال ارسال…"
        Language.TR -> "Gönderiliyor…"
    }

    fun fileTooLarge(l: Language): String = when (l) {
        Language.EN -> "That file is over 25 MB."
        Language.FA -> "این فایل از ۲۵ مگابایت بزرگ‌تر است."
        Language.TR -> "Bu dosya 25 MB'tan büyük."
    }

    fun fileTypeNotAllowed(l: Language): String = when (l) {
        Language.EN -> "That kind of file can't be sent."
        Language.FA -> "این نوع فایل قابل ارسال نیست."
        Language.TR -> "Bu tür bir dosya gönderilemez."
    }

    fun recording(l: Language): String = when (l) {
        Language.EN -> "Recording"
        Language.FA -> "در حال ضبط"
        Language.TR -> "Kaydediliyor"
    }

    /**
     * Shown when the microphone was refused. It points at Settings because
     * that is the only place the answer can be changed once it is given.
     */
    fun microphoneDenied(l: Language): String = when (l) {
        Language.EN -> "Allow microphone access in Settings to record a voice note."
        Language.FA -> "برای ضبط پیام صوتی، دسترسی به میکروفون را در تنظیمات اجازه دهید."
        Language.TR -> "Sesli mesaj kaydetmek için Ayarlar'dan mikrofon erişimine izin verin."
    }

    fun recordingFailed(l: Language): String = when (l) {
        Language.EN -> "Recording could not start."
        Language.FA -> "ضبط شروع نشد."
        Language.TR -> "Kayıt başlatılamadı."
    }

    fun discard(l: Language): String = when (l) {
        Language.EN -> "Discard"
        Language.FA -> "دور انداختن"
        Language.TR -> "At"
    }

    /**
     * The whole of what the field says it is for.
     *
     * A question rather than an instruction, and nothing after it: the
     * operator does not need the mechanism explained every time they open a
     * thread, and a placeholder that runs to three lines pushes the field
     * itself off the bottom of a phone.
     */
    fun sayNowPlaceholder(l: Language): String = when (l) {
        Language.EN -> "What should the visitor be told?"
        Language.FA -> "چه چیزی به بازدیدکننده گفته شود؟"
        Language.TR -> "Ziyaretçiye ne söylensin?"
    }

    /**
     * The line in the AI composer's tool row, as the Mac app has it: what
     * happens to the operator's words once they are sent.
     */
    fun sayNowHint(l: Language): String = when (l) {
        Language.EN -> "The AI rewrites your words and sends them to the visitor now."
        Language.FA -> "هوش مصنوعی حرف شما را بازنویسی می‌کند و همین حالا برای بازدیدکننده می‌فرستد."
        Language.TR -> "Yapay zekâ sözlerinizi yeniden yazar ve ziyaretçiye hemen gönderir."
    }

    /**
     * The AI send button, spoken. Its glyph is the AI's sparkles, but a
     * glyph says nothing to VoiceOver.
     */
    fun sayNowAction(l: Language): String = when (l) {
        Language.EN -> "Send with AI"
        Language.FA -> "ارسال با هوش مصنوعی"
        Language.TR -> "Yapay zekâ ile gönder"
    }

    fun sayNowSent(l: Language): String = when (l) {
        Language.EN -> "The AI sent your message to the visitor"
        Language.FA -> "پیام با هوش مصنوعی برای بازدیدکننده ارسال شد"
        Language.TR -> "Mesajınız yapay zekâ ile ziyaretçiye gönderildi"
    }

    fun sayNowFailed(l: Language): String = when (l) {
        Language.EN -> "Could not send the message"
        Language.FA -> "ارسال پیام ممکن نشد"
        Language.TR -> "Mesaj gönderilemedi"
    }

    /**
     * What the voice button picks, for VoiceOver. Its value is read out
     * separately, so this names the choice and not the current answer.
     */
    fun sayNowVoice(l: Language): String = when (l) {
        Language.EN -> "Voice"
        Language.FA -> "زبان پیام"
        Language.TR -> "Mesajın dili"
    }

    fun sayNowVoiceSpecialist(l: Language): String = when (l) {
        Language.EN -> "In a specialist's voice"
        Language.FA -> "از زبان کارشناس"
        Language.TR -> "Uzman dilinden"
    }

    fun sayNowVoiceAssistant(l: Language): String = when (l) {
        Language.EN -> "In the AI's voice"
        Language.FA -> "از زبان هوش مصنوعی"
        Language.TR -> "Yapay zekâ dilinden"
    }

    fun takeOver(l: Language): String = when (l) {
        Language.EN -> "Take over"
        Language.FA -> "در دست گرفتن"
        Language.TR -> "Devral"
    }

    fun takenOver(l: Language): String = when (l) {
        Language.EN -> "The conversation is yours — the AI has stopped replying."
        Language.FA -> "مکالمه در اختیار شما قرار گرفت — هوش مصنوعی دیگر پاسخ خودکار نمی‌دهد."
        Language.TR -> "Görüşme sizde — yapay zekâ artık otomatik yanıt vermiyor."
    }

    fun takeOverFailed(l: Language): String = when (l) {
        Language.EN -> "Take-over failed"
        Language.FA -> "در دست گرفتن ناموفق بود"
        Language.TR -> "Devralma başarısız oldu"
    }

    /** The Visitors tab. Short, because it shares the bar with four others. */
    fun tabVisitors(l: Language): String = when (l) {
        Language.EN -> "Visitors"
        Language.FA -> "بازدیدکنندگان"
        Language.TR -> "Ziyaretçiler"
    }

    fun visitorsTitle(l: Language): String = when (l) {
        Language.EN -> "Online Visitors"
        Language.FA -> "بازدیدکنندگان آنلاین"
        Language.TR -> "Çevrimiçi Ziyaretçiler"
    }

    fun visitorsSubtitle(l: Language): String = when (l) {
        Language.EN -> "Real-time visitor intelligence"
        Language.FA -> "هوش لحظه‌ای بازدیدکنندگان"
        Language.TR -> "Gerçek zamanlı ziyaretçi zekâsı"
    }

    fun visitorsSearchPrompt(l: Language): String = when (l) {
        Language.EN -> "Search by page, country, browser…"
        Language.FA -> "جست‌وجو بر اساس صفحه، کشور، مرورگر…"
        Language.TR -> "Sayfa, ülke, tarayıcı ile ara…"
    }

    /** The list half of the list / map switch. */
    fun visitorsList(l: Language): String = when (l) {
        Language.EN -> "List"
        Language.FA -> "فهرست"
        Language.TR -> "Liste"
    }

    fun visitorsMap(l: Language): String = when (l) {
        Language.EN -> "Map"
        Language.FA -> "نقشه"
        Language.TR -> "Harita"
    }

    fun visitorsFilters(l: Language): String = when (l) {
        Language.EN -> "Filters"
        Language.FA -> "فیلترها"
        Language.TR -> "Filtreler"
    }

    fun visitorsFilterOnline(l: Language): String = when (l) {
        Language.EN -> "Online only"
        Language.FA -> "فقط آنلاین"
        Language.TR -> "Yalnızca çevrimiçi"
    }

    fun visitorsFilterInChat(l: Language): String = when (l) {
        Language.EN -> "Has conversation"
        Language.FA -> "دارای گفت‌وگو"
        Language.TR -> "Sohbeti olan"
    }

    fun visitorsFilterCountry(l: Language): String = when (l) {
        Language.EN -> "Country"
        Language.FA -> "کشور"
        Language.TR -> "Ülke"
    }

    fun visitorsAllCountries(l: Language): String = when (l) {
        Language.EN -> "All countries"
        Language.FA -> "همه کشورها"
        Language.TR -> "Tüm ülkeler"
    }

    fun visitorsIncludeOffline(l: Language): String = when (l) {
        Language.EN -> "Include offline"
        Language.FA -> "نمایش آفلاین‌ها"
        Language.TR -> "Çevrimdışıları göster"
    }

    fun visitorsClearFilters(l: Language): String = when (l) {
        Language.EN -> "Clear filters"
        Language.FA -> "پاک کردن فیلترها"
        Language.TR -> "Filtreleri temizle"
    }

    fun visitorsStatOnline(l: Language): String = when (l) {
        Language.EN -> "Online"
        Language.FA -> "آنلاین"
        Language.TR -> "Çevrimiçi"
    }

    fun visitorsStatActive(l: Language): String = when (l) {
        Language.EN -> "Active now"
        Language.FA -> "فعال"
        Language.TR -> "Şu an aktif"
    }

    fun visitorsStatCountries(l: Language): String = when (l) {
        Language.EN -> "Countries"
        Language.FA -> "کشورها"
        Language.TR -> "Ülkeler"
    }

    fun visitorsStatPages(l: Language): String = when (l) {
        Language.EN -> "Pages"
        Language.FA -> "صفحات"
        Language.TR -> "Sayfalar"
    }

    fun visitorsEmptyTitle(l: Language): String = when (l) {
        Language.EN -> "No visitors right now"
        Language.FA -> "بازدیدکننده‌ای حضور ندارد"
        Language.TR -> "Şu anda ziyaretçi yok"
    }

    fun visitorsEmptyBody(l: Language): String = when (l) {
        Language.EN -> "Live visitors browsing your site will appear here."
        Language.FA -> "بازدیدکنندگانی که همین حالا در سایت شما هستند اینجا نمایش داده می‌شوند."
        Language.TR -> "Sitenizdeki canlı ziyaretçiler burada görünecek."
    }

    fun visitorsNoResults(l: Language): String = when (l) {
        Language.EN -> "No visitors match your filters"
        Language.FA -> "بازدیدکننده‌ای با این فیلترها یافت نشد"
        Language.TR -> "Filtrelerinizle eşleşen ziyaretçi yok"
    }

    fun visitorsErrorTitle(l: Language): String = when (l) {
        Language.EN -> "Could not load visitors"
        Language.FA -> "بارگذاری بازدیدکنندگان ناموفق بود"
        Language.TR -> "Ziyaretçiler yüklenemedi"
    }

    fun visitorsJustNow(l: Language): String = when (l) {
        Language.EN -> "just now"
        Language.FA -> "هم‌اکنون"
        Language.TR -> "şimdi"
    }

    /** A template: `{n}` is replaced with the number in the reader's digits. */
    fun visitorsMinutesAgo(l: Language): String = when (l) {
        Language.EN -> "{n}m ago"
        Language.FA -> "{n} دقیقه پیش"
        Language.TR -> "{n} dk önce"
    }

    /** A template: `{n}` is replaced with the number in the reader's digits. */
    fun visitorsHoursAgo(l: Language): String = when (l) {
        Language.EN -> "{n}h ago"
        Language.FA -> "{n} ساعت پیش"
        Language.TR -> "{n} sa önce"
    }

    fun visitorsUnknownLocation(l: Language): String = when (l) {
        Language.EN -> "Unknown location"
        Language.FA -> "موقعیت نامشخص"
        Language.TR -> "Bilinmeyen konum"
    }

    /** Under the map. A template: `{n}` is replaced with the number. */
    fun visitorsWithoutLocation(l: Language): String = when (l) {
        Language.EN -> "{n} without a known location"
        Language.FA -> "{n} نفر بدون موقعیت مشخص"
        Language.TR -> "Konumu bilinmeyen {n} kişi"
    }

    fun visitorStatusOnline(l: Language): String = when (l) {
        Language.EN -> "Online"
        Language.FA -> "آنلاین"
        Language.TR -> "Çevrimiçi"
    }

    fun visitorStatusIdle(l: Language): String = when (l) {
        Language.EN -> "Idle"
        Language.FA -> "غیرفعال"
        Language.TR -> "Boşta"
    }

    fun visitorStatusOffline(l: Language): String = when (l) {
        Language.EN -> "Offline"
        Language.FA -> "آفلاین"
        Language.TR -> "Çevrimdışı"
    }

    fun visitorInChat(l: Language): String = when (l) {
        Language.EN -> "In chat"
        Language.FA -> "در گفت‌وگو"
        Language.TR -> "Sohbette"
    }

    fun visitorDetails(l: Language): String = when (l) {
        Language.EN -> "Visitor details"
        Language.FA -> "جزئیات بازدیدکننده"
        Language.TR -> "Ziyaretçi detayları"
    }

    fun visitorCurrentPage(l: Language): String = when (l) {
        Language.EN -> "Current page"
        Language.FA -> "صفحه فعلی"
        Language.TR -> "Mevcut sayfa"
    }

    fun visitorLocation(l: Language): String = when (l) {
        Language.EN -> "Location"
        Language.FA -> "موقعیت"
        Language.TR -> "Konum"
    }

    fun visitorIPAddress(l: Language): String = when (l) {
        Language.EN -> "IP address"
        Language.FA -> "آدرس IP"
        Language.TR -> "IP adresi"
    }

    fun visitorBrowserOS(l: Language): String = when (l) {
        Language.EN -> "Browser · OS"
        Language.FA -> "مرورگر · سیستم‌عامل"
        Language.TR -> "Tarayıcı · İşletim sistemi"
    }

    fun visitorDevice(l: Language): String = when (l) {
        Language.EN -> "Device"
        Language.FA -> "دستگاه"
        Language.TR -> "Cihaz"
    }

    fun visitorReferrer(l: Language): String = when (l) {
        Language.EN -> "Referrer"
        Language.FA -> "ارجاع‌دهنده"
        Language.TR -> "Yönlendiren"
    }

    fun visitorDirect(l: Language): String = when (l) {
        Language.EN -> "Direct visit"
        Language.FA -> "ورود مستقیم"
        Language.TR -> "Doğrudan ziyaret"
    }

    fun visitorLastActivity(l: Language): String = when (l) {
        Language.EN -> "Last activity"
        Language.FA -> "آخرین فعالیت"
        Language.TR -> "Son etkinlik"
    }

    fun visitorPageHistory(l: Language): String = when (l) {
        Language.EN -> "Page history"
        Language.FA -> "تاریخچه صفحات"
        Language.TR -> "Sayfa geçmişi"
    }

    fun visitorPageHistoryEmpty(l: Language): String = when (l) {
        Language.EN -> "No page history yet"
        Language.FA -> "هنوز تاریخچه‌ای ثبت نشده"
        Language.TR -> "Henüz sayfa geçmişi yok"
    }

    fun visitorEntryPoint(l: Language): String = when (l) {
        Language.EN -> "Entry point"
        Language.FA -> "نقطه ورود"
        Language.TR -> "Giriş noktası"
    }

    fun visitorJourney(l: Language): String = when (l) {
        Language.EN -> "Journey"
        Language.FA -> "مسیر بازدید"
        Language.TR -> "Gezinti"
    }

    fun visitorCurrentlyOn(l: Language): String = when (l) {
        Language.EN -> "Currently on"
        Language.FA -> "هم‌اکنون در"
        Language.TR -> "Şu anda"
    }

    fun visitorStartChat(l: Language): String = when (l) {
        Language.EN -> "Start chat"
        Language.FA -> "شروع گفت‌وگو"
        Language.TR -> "Sohbet başlat"
    }

    fun visitorOpenChat(l: Language): String = when (l) {
        Language.EN -> "Open chat"
        Language.FA -> "باز کردن گفت‌وگو"
        Language.TR -> "Sohbeti aç"
    }

    fun visitorCopySession(l: Language): String = when (l) {
        Language.EN -> "Copy session ID"
        Language.FA -> "کپی شناسه نشست"
        Language.TR -> "Oturum kimliğini kopyala"
    }

    fun visitorCopied(l: Language): String = when (l) {
        Language.EN -> "Copied"
        Language.FA -> "کپی شد"
        Language.TR -> "Kopyalandı"
    }

    fun visitorChatFailed(l: Language): String = when (l) {
        Language.EN -> "The chat could not be opened. Try again in a moment."
        Language.FA -> "باز کردن گفت‌وگو ممکن نشد. کمی بعد دوباره امتحان کنید."
        Language.TR -> "Sohbet açılamadı. Birazdan tekrar deneyin."
    }

    /** Over a visitor's page when they dropped off the live list while it was open. */
    fun visitorLeft(l: Language): String = when (l) {
        Language.EN -> "This visitor has left the site."
        Language.FA -> "این بازدیدکننده سایت را ترک کرده است."
        Language.TR -> "Bu ziyaretçi siteden ayrıldı."
    }

    /** The Analytics tab. Short, because it shares the bar with four others. */
    fun tabAnalytics(l: Language): String = when (l) {
        Language.EN -> "Analytics"
        Language.FA -> "آمار"
        Language.TR -> "Analitik"
    }

    fun analyticsTitle(l: Language): String = when (l) {
        Language.EN -> "Website analytics"
        Language.FA -> "تحلیل وب‌سایت"
        Language.TR -> "Web sitesi analitiği"
    }

    fun analyticsSubtitle(l: Language): String = when (l) {
        Language.EN -> "Visits recorded by the chat widget on your site"
        Language.FA -> "بازدیدهایی که ویجت گفت‌وگو در سایت شما ثبت می‌کند"
        Language.TR -> "Sohbet widget'ının sitenizde kaydettiği ziyaretler"
    }

    /** A template: `{count}` is replaced with the number in the reader's digits. */
    fun analyticsLiveNow(l: Language): String = when (l) {
        Language.EN -> "{count} on the site now"
        Language.FA -> "{count} نفر هم‌اکنون در سایت"
        Language.TR -> "Şu an sitede {count} kişi"
    }

    fun analyticsRange7(l: Language): String = when (l) {
        Language.EN -> "7 days"
        Language.FA -> "۷ روز"
        Language.TR -> "7 gün"
    }

    fun analyticsRange28(l: Language): String = when (l) {
        Language.EN -> "28 days"
        Language.FA -> "۲۸ روز"
        Language.TR -> "28 gün"
    }

    fun analyticsRange90(l: Language): String = when (l) {
        Language.EN -> "90 days"
        Language.FA -> "۹۰ روز"
        Language.TR -> "90 gün"
    }

    fun analyticsOverview(l: Language): String = when (l) {
        Language.EN -> "Overview"
        Language.FA -> "نمای کلی"
        Language.TR -> "Genel bakış"
    }

    fun analyticsOverviewHint(l: Language): String = when (l) {
        Language.EN -> "Visitors, visits and time on site"
        Language.FA -> "بازدیدکننده‌ها، بازدیدها و زمان حضور"
        Language.TR -> "Ziyaretçiler, ziyaretler ve sitede geçen süre"
    }

    fun analyticsSources(l: Language): String = when (l) {
        Language.EN -> "Traffic sources"
        Language.FA -> "منابع ترافیک"
        Language.TR -> "Trafik kaynakları"
    }

    fun analyticsSourcesHint(l: Language): String = when (l) {
        Language.EN -> "Where your visitors come from"
        Language.FA -> "بازدیدکننده‌ها از کجا می‌آیند"
        Language.TR -> "Ziyaretçileriniz nereden geliyor"
    }

    fun analyticsPages(l: Language): String = when (l) {
        Language.EN -> "Pages"
        Language.FA -> "صفحات"
        Language.TR -> "Sayfalar"
    }

    fun analyticsPagesHint(l: Language): String = when (l) {
        Language.EN -> "Most viewed, entry and exit pages"
        Language.FA -> "پربازدیدترین، صفحات ورود و خروج"
        Language.TR -> "En çok görüntülenen, giriş ve çıkış sayfaları"
    }

    fun analyticsGeography(l: Language): String = when (l) {
        Language.EN -> "Geography"
        Language.FA -> "جغرافیا"
        Language.TR -> "Coğrafya"
    }

    fun analyticsGeographyHint(l: Language): String = when (l) {
        Language.EN -> "Countries, cities and languages"
        Language.FA -> "کشورها، شهرها و زبان‌ها"
        Language.TR -> "Ülkeler, şehirler ve diller"
    }

    fun analyticsTechnology(l: Language): String = when (l) {
        Language.EN -> "Devices & browsers"
        Language.FA -> "دستگاه و مرورگر"
        Language.TR -> "Cihaz ve tarayıcı"
    }

    fun analyticsTechnologyHint(l: Language): String = when (l) {
        Language.EN -> "Device, operating system and browser"
        Language.FA -> "نوع دستگاه، سیستم‌عامل و مرورگر"
        Language.TR -> "Cihaz, işletim sistemi ve tarayıcı"
    }

    fun analyticsEvents(l: Language): String = when (l) {
        Language.EN -> "Events"
        Language.FA -> "رویدادها"
        Language.TR -> "Olaylar"
    }

    fun analyticsEventsHint(l: Language): String = when (l) {
        Language.EN -> "Custom events from your site"
        Language.FA -> "رویدادهای سفارشی سایت شما"
        Language.TR -> "Sitenizden özel olaylar"
    }

    fun analyticsVisitors(l: Language): String = when (l) {
        Language.EN -> "Visitors"
        Language.FA -> "بازدیدکننده"
        Language.TR -> "Ziyaretçi"
    }

    fun analyticsSessions(l: Language): String = when (l) {
        Language.EN -> "Visits"
        Language.FA -> "بازدید"
        Language.TR -> "Ziyaret"
    }

    fun analyticsPageviews(l: Language): String = when (l) {
        Language.EN -> "Page views"
        Language.FA -> "بازدید صفحه"
        Language.TR -> "Sayfa görüntüleme"
    }

    fun analyticsPagesPerVisit(l: Language): String = when (l) {
        Language.EN -> "Pages per visit"
        Language.FA -> "صفحه در هر بازدید"
        Language.TR -> "Ziyaret başına sayfa"
    }

    fun analyticsBounceRate(l: Language): String = when (l) {
        Language.EN -> "Bounce rate"
        Language.FA -> "نرخ پرش"
        Language.TR -> "Hemen çıkma oranı"
    }

    fun analyticsAvgDuration(l: Language): String = when (l) {
        Language.EN -> "Avg. time on site"
        Language.FA -> "میانگین زمان حضور"
        Language.TR -> "Ort. sitede kalma"
    }

    /** A template: `{count}` is replaced with the number in the reader's digits. */
    fun analyticsVsPrevious(l: Language): String = when (l) {
        Language.EN -> "Compared with the {count} days before"
        Language.FA -> "در مقایسه با {count} روز قبل از آن"
        Language.TR -> "Önceki {count} günle karşılaştırıldığında"
    }

    fun analyticsTrend(l: Language): String = when (l) {
        Language.EN -> "Traffic over time"
        Language.FA -> "روند ترافیک"
        Language.TR -> "Zaman içinde trafik"
    }

    fun analyticsTopChannels(l: Language): String = when (l) {
        Language.EN -> "Top channels"
        Language.FA -> "کانال‌های برتر"
        Language.TR -> "En iyi kanallar"
    }

    fun analyticsTopPages(l: Language): String = when (l) {
        Language.EN -> "Top pages"
        Language.FA -> "صفحات برتر"
        Language.TR -> "En iyi sayfalar"
    }

    fun analyticsVisitsUnit(l: Language): String = when (l) {
        Language.EN -> "visits"
        Language.FA -> "بازدید"
        Language.TR -> "ziyaret"
    }

    fun analyticsViewsUnit(l: Language): String = when (l) {
        Language.EN -> "views"
        Language.FA -> "بازدید"
        Language.TR -> "görüntüleme"
    }

    fun analyticsChannel(l: Language): String = when (l) {
        Language.EN -> "Channel"
        Language.FA -> "کانال"
        Language.TR -> "Kanal"
    }

    fun analyticsSource(l: Language): String = when (l) {
        Language.EN -> "Source"
        Language.FA -> "منبع"
        Language.TR -> "Kaynak"
    }

    fun analyticsCampaign(l: Language): String = when (l) {
        Language.EN -> "Campaign"
        Language.FA -> "کمپین"
        Language.TR -> "Kampanya"
    }

    fun analyticsCountry(l: Language): String = when (l) {
        Language.EN -> "Country"
        Language.FA -> "کشور"
        Language.TR -> "Ülke"
    }

    fun analyticsCity(l: Language): String = when (l) {
        Language.EN -> "City"
        Language.FA -> "شهر"
        Language.TR -> "Şehir"
    }

    fun analyticsLanguage(l: Language): String = when (l) {
        Language.EN -> "Language"
        Language.FA -> "زبان"
        Language.TR -> "Dil"
    }

    fun analyticsPagesTop(l: Language): String = when (l) {
        Language.EN -> "Most viewed"
        Language.FA -> "پربازدیدترین"
        Language.TR -> "En çok görüntülenen"
    }

    fun analyticsPagesEntry(l: Language): String = when (l) {
        Language.EN -> "Entry"
        Language.FA -> "ورود"
        Language.TR -> "Giriş"
    }

    fun analyticsPagesExit(l: Language): String = when (l) {
        Language.EN -> "Exit"
        Language.FA -> "خروج"
        Language.TR -> "Çıkış"
    }

    fun analyticsDevice(l: Language): String = when (l) {
        Language.EN -> "Device"
        Language.FA -> "دستگاه"
        Language.TR -> "Cihaz"
    }

    fun analyticsOS(l: Language): String = when (l) {
        Language.EN -> "Operating system"
        Language.FA -> "سیستم‌عامل"
        Language.TR -> "İşletim sistemi"
    }

    fun analyticsBrowser(l: Language): String = when (l) {
        Language.EN -> "Browser"
        Language.FA -> "مرورگر"
        Language.TR -> "Tarayıcı"
    }

    fun analyticsEventCount(l: Language): String = when (l) {
        Language.EN -> "Times"
        Language.FA -> "تعداد"
        Language.TR -> "Adet"
    }

    fun analyticsEventVisits(l: Language): String = when (l) {
        Language.EN -> "Visits"
        Language.FA -> "بازدید"
        Language.TR -> "Ziyaret"
    }

    fun analyticsConversion(l: Language): String = when (l) {
        Language.EN -> "Conversion"
        Language.FA -> "نرخ تبدیل"
        Language.TR -> "Dönüşüm"
    }

    fun analyticsNoData(l: Language): String = when (l) {
        Language.EN -> "No visits in this range yet"
        Language.FA -> "در این بازه هنوز بازدیدی نیست"
        Language.TR -> "Bu aralıkta henüz ziyaret yok"
    }

    fun analyticsNoDataHint(l: Language): String = when (l) {
        Language.EN -> "The chat widget's snippet records every page view on your site; they show up here."
        Language.FA -> "اسکریپت ویجت گفت‌وگو هر بازدید صفحه در سایت شما را ثبت می‌کند و اینجا نمایش داده می‌شود."
        Language.TR -> "Sohbet widget'ının kodu sitenizdeki her sayfa görüntülemeyi kaydeder; burada görünür."
    }

    fun analyticsNoEvents(l: Language): String = when (l) {
        Language.EN -> "No custom events yet"
        Language.FA -> "هنوز رویداد سفارشی‌ای نیست"
        Language.TR -> "Henüz özel olay yok"
    }

    fun analyticsNoEventsHint(l: Language): String = when (l) {
        Language.EN -> "Send them from your site with window.gsAnalytics.track('name')."
        Language.FA -> "از سایت خود با window.gsAnalytics.track('name') رویداد بفرستید."
        Language.TR -> "Sitenizden window.gsAnalytics.track('ad') ile gönderin."
    }

    fun analyticsLocked(l: Language): String = when (l) {
        Language.EN -> "Website analytics is not in your plan"
        Language.FA -> "تحلیل وب‌سایت در پلن شما نیست"
        Language.TR -> "Web sitesi analitiği planınızda yok"
    }

    fun analyticsLockedHint(l: Language): String = when (l) {
        Language.EN -> "The workspace owner can add it by upgrading the plan."
        Language.FA -> "مالک فضای کاری می‌تواند با ارتقای پلن آن را فعال کند."
        Language.TR -> "Çalışma alanı sahibi planı yükselterek ekleyebilir."
    }

    fun analyticsLoadFailed(l: Language): String = when (l) {
        Language.EN -> "This report could not be loaded."
        Language.FA -> "این گزارش بارگذاری نشد."
        Language.TR -> "Bu rapor yüklenemedi."
    }

    fun analyticsTruncated(l: Language): String = when (l) {
        Language.EN -> "This range is very busy, so these numbers are from a sample of it."
        Language.FA -> "این بازه خیلی پرترافیک است؛ اعداد از نمونه‌ای از آن محاسبه شده‌اند."
        Language.TR -> "Bu aralık çok yoğun; rakamlar bir örneklemden hesaplandı."
    }

    fun analyticsUnknown(l: Language): String = when (l) {
        Language.EN -> "Unknown"
        Language.FA -> "نامشخص"
        Language.TR -> "Bilinmiyor"
    }

    fun analyticsTotal(l: Language): String = when (l) {
        Language.EN -> "Total"
        Language.FA -> "مجموع"
        Language.TR -> "Toplam"
    }

    fun analyticsLeader(l: Language): String = when (l) {
        Language.EN -> "Top"
        Language.FA -> "در صدر"
        Language.TR -> "Zirvede"
    }

    fun analyticsDistinct(l: Language): String = when (l) {
        Language.EN -> "Different items"
        Language.FA -> "تعداد موارد"
        Language.TR -> "Farklı öğe"
    }

    /** After a number of minutes in a duration: 2m 14s. */
    fun analyticsMinutesShort(l: Language): String = when (l) {
        Language.EN -> "m"
        Language.FA -> "دقیقه"
        Language.TR -> "dk"
    }

    /** After a number of seconds in a duration: 2m 14s. */
    fun analyticsSecondsShort(l: Language): String = when (l) {
        Language.EN -> "s"
        Language.FA -> "ثانیه"
        Language.TR -> "sn"
    }

    fun analyticsChannelDirect(l: Language): String = when (l) {
        Language.EN -> "Direct"
        Language.FA -> "مستقیم"
        Language.TR -> "Doğrudan"
    }

    fun analyticsChannelOrganicSearch(l: Language): String = when (l) {
        Language.EN -> "Organic search"
        Language.FA -> "جست‌وجوی ارگانیک"
        Language.TR -> "Organik arama"
    }

    fun analyticsChannelOrganicSocial(l: Language): String = when (l) {
        Language.EN -> "Organic social"
        Language.FA -> "شبکه‌های اجتماعی"
        Language.TR -> "Organik sosyal"
    }

    fun analyticsChannelReferral(l: Language): String = when (l) {
        Language.EN -> "Referral"
        Language.FA -> "ارجاع از سایت‌ها"
        Language.TR -> "Yönlendirme"
    }

    fun analyticsChannelPaidSearch(l: Language): String = when (l) {
        Language.EN -> "Paid search"
        Language.FA -> "جست‌وجوی پولی"
        Language.TR -> "Ücretli arama"
    }

    fun analyticsChannelPaidSocial(l: Language): String = when (l) {
        Language.EN -> "Paid social"
        Language.FA -> "تبلیغات شبکه‌های اجتماعی"
        Language.TR -> "Ücretli sosyal"
    }

    fun analyticsChannelEmail(l: Language): String = when (l) {
        Language.EN -> "Email"
        Language.FA -> "ایمیل"
        Language.TR -> "E-posta"
    }

    fun analyticsChannelOther(l: Language): String = when (l) {
        Language.EN -> "Other"
        Language.FA -> "سایر"
        Language.TR -> "Diğer"
    }

    fun analyticsDeviceMobile(l: Language): String = when (l) {
        Language.EN -> "Mobile"
        Language.FA -> "موبایل"
        Language.TR -> "Mobil"
    }

    fun analyticsDeviceDesktop(l: Language): String = when (l) {
        Language.EN -> "Desktop"
        Language.FA -> "دسکتاپ"
        Language.TR -> "Masaüstü"
    }

    fun analyticsDeviceTablet(l: Language): String = when (l) {
        Language.EN -> "Tablet"
        Language.FA -> "تبلت"
        Language.TR -> "Tablet"
    }
}
