package com.webyar.operator.core

import com.webyar.operator.core.model.EmailBody
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Making an HTML mail readable.
 *
 * Not a parser and not trying to be — but the four things it does have to
 * survive real mail, which is generated by other people's tools and is rarely
 * tidy.
 */
class EmailBodyTest {

    @Test fun `tags come out and the words stay`() {
        assertEquals("Hello there", EmailBody.plainText("<p><b>Hello</b> there</p>"))
    }

    @Test fun `script and style never reach the reader`() {
        val html = "<style>p{color:red}</style><script>alert(1)</script><p>Body</p>"
        val text = EmailBody.plainText(html)
        assertEquals("Body", text)
        assertFalse(text.contains("alert"))
        assertFalse(text.contains("color"))
    }

    @Test fun `a script spanning several lines is still one match`() {
        // Without DOT_MATCHES_ALL the regex stops at the first newline and the
        // rest of the script lands in the reader's message.
        val html = "<script>\nvar a = 1;\nvar b = 2;\n</script><p>After</p>"
        assertEquals("After", EmailBody.plainText(html))
    }

    @Test fun `block ends become line breaks`() {
        assertEquals("One\nTwo", EmailBody.plainText("<div>One</div><div>Two</div>"))
    }

    @Test fun `the entities that appear in almost every message are put back`() {
        assertEquals("a & b < c > d \" e ' f", EmailBody.plainText("a &amp; b &lt; c &gt; d &quot; e &#39; f"))
    }

    @Test fun `the zero-width non-joiner survives, because Persian needs it`() {
        // &zwnj; is how a mail writes the half-space, and dropping it turns
        // "می‌شود" into "میشود" — a different spelling, not a different glyph.
        assertTrue(EmailBody.plainText("می&zwnj;شود").contains('‌'))
    }

    @Test fun `runs of blank lines collapse to one gap`() {
        val html = "<p>A</p><br><br><br><br><p>B</p>"
        assertEquals("A\n\nB", EmailBody.plainText(html))
    }

    @Test fun `an empty document is empty, not a crash`() {
        assertEquals("", EmailBody.plainText(""))
        assertEquals("", EmailBody.plainText("<div></div>"))
    }
}
