package com.webyar.operator.core

import com.webyar.operator.core.model.EmailBody
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Making an HTML mail readable.
 *
 * Not a parser and not trying to be — but the four things it does have to
 * survive real mail, which is generated by other people's tools and is rarely
 * tidy.
 */
class EmailBodyTest {

    @Test fun `tags come out and the words stay`() {
        assertEquals("Hello there", EmailBody.plainText("<p><b>Hello</b> there</p>"))
    }

    @Test fun `script and style never reach the reader`() {
        val html = "<style>p{color:red}</style><script>alert(1)</script><p>Body</p>"
        val text = EmailBody.plainText(html)
        assertEquals("Body", text)
        assertFalse(text.contains("alert"))
        assertFalse(text.contains("color"))
    }

    @Test fun `a script spanning several lines is still one match`() {
        // Without DOT_MATCHES_ALL the regex stops at the first newline and the
        // rest of the script lands in the reader's message.
        val html = "<script>\nvar a = 1;\nvar b = 2;\n</script><p>After</p>"
        assertEquals("After", EmailBody.plainText(html))
    }

    @Test fun `block ends become line breaks`() {
        assertEquals("One\nTwo", EmailBody.plainText("<div>One</div><div>Two</div>"))
    }

    @Test fun `the entities that appear in almost every message are put back`() {
        assertEquals("a & b < c > d \" e ' f", EmailBody.plainText("a &amp; b &lt; c &gt; d &quot; e &#39; f"))
    }

    @Test fun `the zero-width non-joiner survives, because Persian needs it`() {
        // &zwnj; is how a mail writes the half-space, and dropping it turns
        // "می‌شود" into "میشود" — a different spelling, not a different glyph.
        assertTrue(EmailBody.plainText("می&zwnj;شود").contains('‌'))
    }

    @Test fun `runs of blank lines collapse to one gap`() {
        val html = "<p>A</p><br><br><br><br><p>B</p>"
        assertEquals("A\n\nB", EmailBody.plainText(html))
    }

    @Test fun `an empty document is empty, not a crash`() {
        assertEquals("", EmailBody.plainText(""))
        assertEquals("", EmailBody.plainText("<div></div>"))
    }
    /**
     * The em dash a word processor puts in for a typed hyphen, and the curly
     * quotes it substitutes. These are in almost every mail written in a rich
     * editor, and they used to come through as «Thanks &mdash; received.»
     */
    @Test fun `the entities a word processor inserts are put back too`() {
        assertEquals(
            "Thanks \u2014 received. It\u2019s \u201cdone\u201d\u2026",
            EmailBody.plainText("<p>Thanks &mdash; received. It&rsquo;s &ldquo;done&rdquo;&hellip;</p>"),
        )
    }

    @Test fun `a numeric entity is decoded, in decimal and in hex`() {
        assertEquals("a \u2014 b", EmailBody.plainText("a &#8212; b"))
        assertEquals("a \u2014 b", EmailBody.plainText("a &#x2014; b"))
        // Above the basic plane, so it needs a surrogate pair rather than a char.
        assertEquals("\ud83d\ude42", EmailBody.plainText("&#128578;"))
    }

    /**
     * A code point that is not one is left exactly as written. Showing
     * `&#1114112;` is ugly; showing whatever it truncated to would be wrong.
     */
    @Test fun `a nonsense code point is left alone`() {
        assertEquals("&#1114112;", EmailBody.plainText("&#1114112;"))
        assertEquals("&#0;", EmailBody.plainText("&#0;"))
    }

    /**
     * The ampersand is decoded LAST, and this is why.
     *
     * A mail that wants to SHOW the text "&mdash;" writes "&amp;mdash;".
     * Decoding the ampersand first turns that into "&mdash;" and then into an
     * em dash — quietly changing what somebody wrote.
     */
    @Test fun `an escaped entity stays text rather than becoming the character`() {
        assertEquals("&mdash;", EmailBody.plainText("&amp;mdash;"))
        assertEquals("&#8212;", EmailBody.plainText("&amp;#8212;"))
        assertEquals("a & b", EmailBody.plainText("a &amp; b"))
    }

}
