/**
 * Setup & Integrations
 * --------------------
 * Crisp-style installation hub for the workspace's chat widget.
 *
 * Implemented (operational):
 *  - Workspace ID (single source of truth = workspaces.id; same value used
 *    by the widget loader as `data-workspace-id` and window.__gs_id).
 *  - HTML / Website embed snippet (window + script-tag variants), powered
 *    by the central `buildWidgetEmbedSnippet` helper in src/lib/widgetEmbed.
 *  - CMS install guides for WordPress, Shopify, Prestashop, WooCommerce
 *    and WHMCS — each opens a dialog with the embed snippet and a
 *    plain-language step-by-step guide for that platform.
 *
 * Not yet operational (clearly marked "Coming soon"):
 *  - Email channels (Gmail / Outlook / IMAP) — require inbound email infra.
 *  - Messaging plugins (Instagram, Messenger, Slack, Telegram, X, WhatsApp).
 *  - Native App SDKs (iOS / Android / React Native).
 *
 * NOTE: We never fabricate IDs or fake addresses. The Workspace ID shown
 * here is the literal `workspaces.id` row already used by the widget
 * runtime; the embed snippet is generated by the same helper used in the
 * Widget page so the two stay in lockstep.
 */
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from '@/i18n';
import { useCurrentWorkspace, useWorkspacePath } from '@/hooks/useWorkspace';
import { useWidgetPlatformPublicSettings } from '@/hooks/useWidgetPlatformSettings';
import { resolveWidgetUrls, buildWidgetEmbedSnippet } from '@/lib/widgetEmbed';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription,
} from '@/components/ui/dialog';
import { toast } from '@/hooks/use-toast';
import {
  Copy, Check, ExternalLink, HelpCircle, Code2, ArrowRight,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { BrandIcon } from '@/components/integrations/BrandIcon';

/* ---------- Channel catalog ----------------------------------------- */

type ChannelStatus = 'available' | 'soon';

interface CmsGuide {
  steps: string[];
  docsUrl?: string;
  /** Optional: when set, the dialog also shows a "Plugin / App" call-to-action. */
  pluginUrl?: string;
}

interface Channel {
  id: string;
  name: string;
  status: ChannelStatus;
  /** When 'available' + cms is set, opens an install dialog with that guide. */
  cms?: CmsGuide;
  /** When the channel is 'soon', this short note is shown in the tooltip. */
  soonReason?: string;
}

interface ChannelGroup {
  key: string;
  title: string;
  description?: string;
  channels: Channel[];
  /** Two- or three-column grid. Defaults to three. */
  columns?: 2 | 3;
}

/* ---------- Page ---------------------------------------------------- */

export default function SettingsIntegrationsPage() {
  const { t } = useTranslation();
  const workspace = useCurrentWorkspace();
  const wsPath = useWorkspacePath();
  const { data: platformWidget } = useWidgetPlatformPublicSettings();
  const [copied, setCopied] = useState<string | null>(null);
  const [openChannel, setOpenChannel] = useState<Channel | null>(null);

  const urls = useMemo(
    () => resolveWidgetUrls(platformWidget, typeof window !== 'undefined' ? window.location.origin : undefined),
    [platformWidget],
  );

  // The single embed snippet pasted into any HTML page.
  const embedSnippet = useMemo(
    () => buildWidgetEmbedSnippet(urls, {
      variant: 'window',
      workspaceId: workspace?.id,
      headerComment: platformWidget?.embed_header_comment,
      footerComment: platformWidget?.embed_footer_comment,
    }),
    [urls, workspace?.id, platformWidget?.embed_header_comment, platformWidget?.embed_footer_comment],
  );

  const handleCopy = (key: string, value: string) => {
    void navigator.clipboard.writeText(value);
    setCopied(key);
    toast({ title: t('common.copied') });
    window.setTimeout(() => setCopied(c => (c === key ? null : c)), 1800);
  };

  if (!workspace) {
    return <div className="p-8 text-center text-muted-foreground">{t('common.loading')}</div>;
  }

  /* ---------- Catalog (defined inside so we can reference t) -------- */

  const groups: ChannelGroup[] = [
    {
      key: 'website',
      title: t('integrationsPage.groups.website'),
      description: t('integrationsPage.groups.websiteDesc'),
      channels: [
        {
          id: 'html', name: 'HTML', status: 'available',
          cms: {
            steps: [
              t('integrationsPage.html.step1'),
              t('integrationsPage.html.step2'),
              t('integrationsPage.html.step3'),
            ],
          },
        },
        {
          id: 'wordpress', name: 'WordPress', status: 'available',
          cms: {
            steps: [
              t('integrationsPage.wordpress.step1'),
              t('integrationsPage.wordpress.step2'),
              t('integrationsPage.wordpress.step3'),
              t('integrationsPage.wordpress.step4'),
            ],
            docsUrl: 'https://wordpress.org/documentation/article/customizer/',
          },
        },
        {
          id: 'shopify', name: 'Shopify', status: 'available',
          cms: {
            steps: [
              t('integrationsPage.shopify.step1'),
              t('integrationsPage.shopify.step2'),
              t('integrationsPage.shopify.step3'),
              t('integrationsPage.shopify.step4'),
            ],
            docsUrl: 'https://help.shopify.com/en/manual/online-store/themes/theme-structure/extend/code',
          },
        },
        {
          id: 'prestashop', name: 'Prestashop', status: 'available',
          cms: {
            steps: [
              t('integrationsPage.prestashop.step1'),
              t('integrationsPage.prestashop.step2'),
              t('integrationsPage.prestashop.step3'),
            ],
          },
        },
        {
          id: 'woocommerce', name: 'WooCommerce', status: 'available',
          cms: {
            steps: [
              t('integrationsPage.woocommerce.step1'),
              t('integrationsPage.woocommerce.step2'),
              t('integrationsPage.woocommerce.step3'),
              t('integrationsPage.woocommerce.step4'),
            ],
            docsUrl: 'https://woocommerce.com/document/',
          },
        },
        {
          // A real connector, not a snippet guide: the extension injects the
          // widget itself and connects under Plugins → OpenCart.
          id: 'opencart', name: 'OpenCart', status: 'available',
          cms: {
            steps: [
              t('integrationsPage.opencart.step1'),
              t('integrationsPage.opencart.step2'),
              t('integrationsPage.opencart.step3'),
            ],
          },
        },
        {
          id: 'whmcs', name: 'WHMCS', status: 'available',
          cms: {
            steps: [
              t('integrationsPage.whmcs.step1'),
              t('integrationsPage.whmcs.step2'),
              t('integrationsPage.whmcs.step3'),
            ],
            docsUrl: 'https://docs.whmcs.com/Custom_Header_Output_Hooks',
            pluginUrl: wsPath('/plugins/whmcs'),
          },
        },
        {
          id: 'adobe', name: 'Adobe Commerce', status: 'soon',
          soonReason: t('integrationsPage.soon.cms'),
        },
      ],
    },
    {
      key: 'email',
      title: t('integrationsPage.groups.email'),
      description: t('integrationsPage.groups.emailDesc'),
      channels: [
        { id: 'gmail',   name: 'Gmail',        status: 'soon', soonReason: t('integrationsPage.soon.email') },
        { id: 'outlook', name: 'Outlook',      status: 'soon', soonReason: t('integrationsPage.soon.email') },
        { id: 'email',   name: 'Email (IMAP)', status: 'soon', soonReason: t('integrationsPage.soon.email') },
      ],
    },
    {
      key: 'messaging',
      title: t('integrationsPage.groups.messaging'),
      description: t('integrationsPage.groups.messagingDesc'),
      channels: [
        { id: 'instagram', name: 'Instagram',   status: 'soon', soonReason: t('integrationsPage.soon.oauth') },
        { id: 'messenger', name: 'Messenger',   status: 'soon', soonReason: t('integrationsPage.soon.oauth') },
        { id: 'slack',     name: 'Slack',       status: 'soon', soonReason: t('integrationsPage.soon.oauth') },
        { id: 'telegram',  name: 'Telegram',    status: 'soon', soonReason: t('integrationsPage.soon.oauth') },
        { id: 'twitter',   name: 'X (Twitter)', status: 'soon', soonReason: t('integrationsPage.soon.oauth') },
        { id: 'whatsapp',  name: 'WhatsApp',    status: 'soon', soonReason: t('integrationsPage.soon.oauth') },
      ],
    },
    {
      key: 'sdk',
      title: t('integrationsPage.groups.sdk'),
      description: t('integrationsPage.groups.sdkDesc'),
      channels: [
        { id: 'ios',         name: 'iOS SDK',          status: 'soon', soonReason: t('integrationsPage.soon.sdk') },
        { id: 'android',     name: 'Android SDK',      status: 'soon', soonReason: t('integrationsPage.soon.sdk') },
        { id: 'reactnative', name: 'React Native SDK', status: 'soon', soonReason: t('integrationsPage.soon.sdk') },
      ],
    },
  ];

  return (
    <div className="space-y-10 animate-fade-in pb-12">
      {/* Header */}
      <header className="flex items-center gap-2">
        <h1 className="text-2xl font-semibold text-foreground">{t('integrationsPage.title')}</h1>
        <HelpCircle className="h-4 w-4 text-muted-foreground" />
      </header>

      {/* Workspace ID (Website ID) */}
      <section className="space-y-2">
        <label className="text-xs font-medium text-foreground">
          {t('integrationsPage.websiteId')}
        </label>
        <div className="flex gap-2">
          <Input
            value={workspace.id}
            readOnly
            className="font-mono text-sm bg-muted/30 cursor-text"
            onFocus={(e) => e.currentTarget.select()}
          />
          <Button
            type="button"
            onClick={() => handleCopy('wsid', workspace.id)}
            variant="default"
            className="shrink-0 gap-1.5"
          >
            {copied === 'wsid' ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
            <span>{copied === 'wsid' ? t('common.copied') : t('common.copy')}</span>
          </Button>
        </div>
        <p className="text-[11px] text-muted-foreground">
          {t('integrationsPage.websiteIdHint')}
        </p>
      </section>

      {/* Quick chatbox install button */}
      <section className="flex flex-col gap-3 rounded-xl border border-border/60 bg-card/40 p-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-start gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
            <Code2 className="h-5 w-5" />
          </div>
          <div>
            <p className="text-sm font-semibold text-foreground">
              {t('integrationsPage.chatbox')}
            </p>
            <p className="text-xs text-muted-foreground">
              {t('integrationsPage.chatboxDesc')}
            </p>
          </div>
        </div>
        <Button
          onClick={() => setOpenChannel(groups[0].channels[0])}
          className="gap-1.5 self-start sm:self-auto"
        >
          <ArrowRight className="h-3.5 w-3.5" />
          {t('integrationsPage.chatboxCta')}
        </Button>
      </section>

      {/* Channel groups */}
      {groups.map((g) => (
        <section key={g.key} className="space-y-3">
          <div>
            <h2 className="text-base font-semibold text-foreground">{g.title}</h2>
            {g.description && (
              <p className="mt-0.5 text-sm text-muted-foreground">{g.description}</p>
            )}
          </div>

          <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
            {g.channels.map((c) => (
              <ChannelCard
                key={c.id}
                channel={c}
                onClick={() => c.status === 'available' ? setOpenChannel(c) : null}
                soonLabel={t('integrationsPage.comingSoon')}
              />
            ))}
          </div>
        </section>
      ))}

      {/* Install dialog */}
      <Dialog open={!!openChannel} onOpenChange={(o) => !o && setOpenChannel(null)}>
        <DialogContent className="max-w-2xl">
          {openChannel && (
            <>
              <DialogHeader>
                <DialogTitle className="flex items-center gap-3">
                  <BrandIcon id={openChannel.id} size={40} />
                  <span>
                    {t('integrationsPage.installOn')} {openChannel.name}
                  </span>
                </DialogTitle>
                <DialogDescription>
                  {t('integrationsPage.installDesc')}
                </DialogDescription>
              </DialogHeader>

              {openChannel.cms?.pluginUrl && (
                <div className="flex flex-col gap-3 rounded-lg border border-primary/30 bg-primary/5 p-3 text-sm sm:flex-row sm:items-center sm:justify-between">
                  <span className="text-foreground">{t('integrationsPage.pluginCta.text', { name: openChannel.name })}</span>
                  <Button asChild size="sm" className="shrink-0 gap-1.5">
                    <Link to={openChannel.cms.pluginUrl} onClick={() => setOpenChannel(null)}>
                      {t('integrationsPage.pluginCta.button')}
                      <ArrowRight className="h-3.5 w-3.5 rtl:rotate-180" />
                    </Link>
                  </Button>
                </div>
              )}

              {openChannel.cms?.pluginUrl && openChannel.cms?.steps && (
                <p className="text-xs font-medium text-muted-foreground">{t('integrationsPage.pluginCta.manual')}</p>
              )}

              {openChannel.cms?.steps && (
                <ol className="space-y-2 text-sm text-foreground">
                  {openChannel.cms.steps.map((step, i) => (
                    <li key={i} className="flex gap-3">
                      <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-primary/10 text-[11px] font-semibold text-primary">
                        {i + 1}
                      </span>
                      <span className="text-muted-foreground">{step}</span>
                    </li>
                  ))}
                </ol>
              )}

              {/* The embed snippet — copy block */}
              <div className="space-y-1.5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-medium text-foreground">
                    {t('integrationsPage.snippet')}
                  </span>
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    onClick={() => handleCopy(`snippet-${openChannel.id}`, embedSnippet)}
                    className="h-7 gap-1.5 text-xs"
                  >
                    {copied === `snippet-${openChannel.id}` ? (
                      <Check className="h-3 w-3" />
                    ) : (
                      <Copy className="h-3 w-3" />
                    )}
                    {copied === `snippet-${openChannel.id}`
                      ? t('common.copied') : t('common.copy')}
                  </Button>
                </div>
                <pre className="max-h-64 overflow-auto rounded-lg border border-border/50 bg-muted/30 p-3 text-[11px] leading-relaxed text-foreground">
                  <code>{embedSnippet}</code>
                </pre>
              </div>

              {openChannel.cms?.docsUrl && (
                <a
                  href={openChannel.cms.docsUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1.5 text-xs text-primary hover:underline"
                >
                  <ExternalLink className="h-3 w-3" />
                  {t('integrationsPage.officialDocs')}
                </a>
              )}
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}

/* ---------- Channel card ------------------------------------------- */

function ChannelCard({
  channel,
  onClick,
  soonLabel,
}: {
  channel: Channel;
  onClick: () => void;
  soonLabel: string;
}) {
  const isSoon = channel.status === 'soon';
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={isSoon}
      title={isSoon ? channel.soonReason : undefined}
      className={cn(
        'group flex items-center gap-3 rounded-xl border border-border/60 bg-card px-3.5 py-3 text-start transition-all',
        isSoon
          ? 'opacity-60 cursor-not-allowed'
          : 'hover:border-primary/40 hover:bg-accent/40 hover:shadow-sm',
      )}
    >
      <BrandIcon id={channel.id} />
      <span className="flex-1 text-sm font-medium text-foreground">
        {channel.name}
      </span>
      {isSoon ? (
        <Badge variant="outline" className="text-[10px] uppercase tracking-wider">
          {soonLabel}
        </Badge>
      ) : (
        <ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-0.5" />
      )}
    </button>
  );
}
