#!/bin/sh
# NOT generated by Coolify. Hand-written; see deploy/windows-downloads/README.md.
# Mirrors the Windows app's official releases onto the site, so people and the
# installed apps get everything from https://app.webyar.ai/downloads/:
#   Webyar-Setup-<version>.exe (+ Webyar-Setup.exe -> the newest) and
#   windows/ — the Velopack update feed (releases.win.json, RELEASES, *.nupkg).
# CI builds and uploads each release to github.com/pc30cc/webyar-desktop-releases;
# this runs every 5 minutes (systemd timer webyar-windows-sync) and copies new ones here.
set -eu
FILES=/data/webyar-downloads/files
FEED=$FILES/windows
REPO=pc30cc/webyar-desktop-releases
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$FEED"

curl -fsSL "https://api.github.com/repos/$REPO/releases?per_page=6" -o "$TMP/releases.json"
python3 - "$TMP/releases.json" > "$TMP/plan.txt" <<'PY'
import json, sys
rels = [r for r in json.load(open(sys.argv[1])) if not r.get("draft") and not r.get("prerelease")]
for i, r in enumerate(rels):
    v = r["tag_name"].lstrip("v")
    for a in r.get("assets", []):
        n = a["name"]
        if n.endswith(".nupkg"):
            print("pkg", n, a["size"], a["browser_download_url"])
        elif i == 0 and n in ("releases.win.json", "RELEASES"):
            print("index", n, a["size"], a["browser_download_url"])
        elif i == 0 and n == "Webyar-Setup.exe":
            print("setup", "Webyar-Setup-%s.exe" % v, a["size"], a["browser_download_url"])
PY

fetch() { # name size url dest-dir
  [ -f "$4/$1" ] && [ "$(stat -c %s "$4/$1")" = "$2" ] && return 0
  curl -fsSL "$3" -o "$TMP/$1"
  [ "$(stat -c %s "$TMP/$1")" = "$2" ] || { echo "size mismatch for $1" >&2; return 1; }
  mv "$TMP/$1" "$4/$1"
  echo "fetched $1"
}

# Packages first, then the index that lists them, so the feed never names a missing file.
grep '^pkg ' "$TMP/plan.txt" | while read -r _ n s u; do fetch "$n" "$s" "$u" "$FEED"; done
grep '^setup ' "$TMP/plan.txt" | while read -r _ n s u; do fetch "$n" "$s" "$u" "$FILES" && ln -sfn "$n" "$FILES/Webyar-Setup.exe"; done
grep '^index ' "$TMP/plan.txt" | while read -r _ n s u; do
  curl -fsSL "$u" -o "$TMP/$n.new" && [ "$(stat -c %s "$TMP/$n.new")" = "$s" ] && mv "$TMP/$n.new" "$FEED/$n"
done

# Keep the newest 12 packages; older ones are never asked for.
ls -1 "$FEED"/*.nupkg 2>/dev/null | sort -V | head -n -12 | xargs -r rm -f
