/**
 * Conversations API — backend-mediated agent reply send.
 *
 * Flow (POST /api/conversations/send-message):
 *   1. Verify the caller is an authenticated workspace member.
 *   2. Insert into conversation_messages.
 *   3. Bump conversations.updated_at.
 *   4. Publish a `message` event to the Centrifugo conversation channel
 *      (ws:<workspace_id>:conv:<conversation_id>) so the visitor widget
 *      receives the agent reply live without polling/refresh.
 *   5. Return the inserted row + a `realtime` flag indicating whether the
 *      live publish actually went out (so the inbox UI can show a hint).
 *
 * Auth model:
 *   • Bearer = Supabase user access token (same as src/lib/realtime-admin-api.ts).
 *   • We resolve the user, then verify membership via is_workspace_member RPC.
 *   • All DB writes go through the service-role client — RLS is enforced
 *     at the route layer, not via the user's JWT (matches the admin pattern
 *     already used by /api/realtime/admin and /api/admin).
 */

import { Router } from 'express';
import { z } from 'zod';
import type { ServerConfig } from '../config.js';
import { getServiceClient } from '../supabase.js';
import {
  publishConversationEvent,
  buildMessageEnvelope,
  publishOperatorEvent,
  type OperatorEventPayload,
} from '../services/realtime/publish.js';
import {
  attachUploadedFileToMessage,
  enrichMessagesWithAttachments,
} from './widgetAttachments.js';
import {
  recordConversationEvent,
  recordAuditAndEvent,
} from '../services/conversationEvents.js';
import { isActionActive } from '../services/observability/autoActionsCache.js';
import { isTelegramMenuEventsVisible } from '../services/channels/telegram/settings.js';
import { emitLog } from '../services/observability/metrics.js';
import { markHumanTakeover } from '../services/ai-agent/handoffState.js';
import { maybeCreateLearningCandidateFromOperatorReply } from '../services/ai-agent/learning/candidates.js';
import { markSpam, unmarkSpam } from '../services/spam/state.js';
import { enforceMaxConversationsLimit } from '../services/billing/conversationLimit.js';
import { authorizeWorkspaceAccess } from '../lib/workspaceAuth.js';
import { dispatchOutboundIfChannelConversation } from '../services/channels/outbound.js';
import { enqueueOutboundMediaIfChannelConversation } from '../services/channels/mediaOutbound.js';

import { applyPostSendAction } from '../services/conversationPostSend.js';
import { isActionableCustomerTurn, isQualifiedCustomerFacingAnswer } from '../services/needsReply.js';


export const conversationsRouter = Router();

const ALLOWED_STATUSES = ['open', 'pending', 'resolved', 'closed'] as const;
const ALLOWED_PRIORITIES = ['low', 'normal', 'high', 'urgent'] as const;

const sendMessageSchema = z.object({
  conversation_id: z.string().uuid(),
  workspace_id: z.string().uuid(),
  body: z.string().max(50_000).optional().default(''),
  metadata: z.record(z.unknown()).optional(),
  attachment_id: z.string().uuid().nullable().optional(),
  /** Split Send: status transition applied AFTER a successful send. */
  post_send_action: z.enum(['none', 'wait_for_customer', 'resolve']).optional().default('none'),
  /**
   * Server-side idempotency key generated by the composer. A double-click or a
   * network retry replays the SAME key, so the duplicate is collapsed instead
   * of producing a second message + a second provider delivery.
   */
  client_message_id: z.string().min(8).max(64).optional(),
}).refine(
  d => (d.body && d.body.trim().length > 0) || !!d.attachment_id,
  { message: 'body or attachment_id required' }
);



/**
 * Schema for starting a proactive conversation from the Visitors page.
 * The operator targets a visitor_session; we either reuse the most-recent
 * open conversation tied to that session, or create a new one.
 */
const startFromVisitorSchema = z.object({
  workspace_id: z.string().uuid(),
  visitor_session_id: z.string().uuid(),
});

/**
 * Authenticate the request as a workspace member.
 * Returns { userId } on success, sends 401/403 on failure. Delegates to the
 * central first-party session helper (server/lib/workspaceAuth.ts).
 */
async function authorizeWorkspaceMember(
  req: any,
  res: any,
  _config: ServerConfig,
  workspaceId: string,
): Promise<{ userId: string; isAdmin: boolean; role: string | null } | null> {
  const auth = await authorizeWorkspaceAccess(req, res, workspaceId);
  if (!auth) return null;
  return { userId: auth.userId, isAdmin: auth.isAdmin, role: auth.role };
}

/**
 * POST /api/conversations/:conversationId/take-over
 *
 * Inbox-owned human takeover. Intentionally lives here (and NOT only under
 * /api/ai-agent) so an operator can always grab a conversation even when the
 * AI Agent module is off at platform level or missing from the workspace
 * plan — otherwise an AI-managed thread could never be handed back to a human.
 */
const inboxTakeOverSchema = z.object({
  workspaceId: z.string().uuid(),
  assign_to_me: z.boolean().optional().default(true),
});
conversationsRouter.post('/:conversationId/take-over', async (req, res) => {
  const config = (req as any).serverConfig as ServerConfig;
  const conversationId = String(req.params.conversationId || '');
  const parsed = inboxTakeOverSchema.safeParse(req.body);
  if (!conversationId || !parsed.success) return res.status(400).json({ error: 'invalid_params' });
  const { workspaceId, assign_to_me } = parsed.data;

  const sb = getServiceClient(config);
  const { data: conv } = await sb
    .from('conversations')
    .select('id, workspace_id, assigned_to')
    .eq('id', conversationId)
    .maybeSingle();
  if (!conv || conv.workspace_id !== workspaceId) {
    return res.status(404).json({ error: 'conversation_not_found' });
  }
  const auth = await authorizeWorkspaceMember(req, res, config, workspaceId);
  if (!auth) return;

  if (assign_to_me && !conv.assigned_to) {
    await sb.from('conversations').update({ assigned_to: auth.userId }).eq('id', conversationId);
  }
  await markHumanTakeover(config, {
    workspaceId,
    conversationId,
    operatorId: auth.userId,
    reason: 'manual_takeover',
  });
  return res.json({ ok: true });
});



/**
 * Operator typing — ephemeral realtime-only event.
 *
 * Phase 1 contract:
 *   - No DB write. The server simply publishes an ephemeral
 *     `{ type: 'typing', payload: { actor: 'agent', conversation_id, ts } }`
 *     envelope on the conversation channel using the active realtime publisher.
 *   - On polling deployments the publish becomes a no-op and typing is silently
 *     not delivered (by design — typing is best-effort).
 *   - Caller must be an authenticated workspace member of the conversation.
 *   - Returns `{ ok, published }` so clients can throttle accordingly.
 */
const typingSchema = z.object({
  conversation_id: z.string().uuid(),
  workspace_id: z.string().uuid(),
});

conversationsRouter.post('/typing', async (req, res) => {
  try {
    const config: ServerConfig = (req as any).serverConfig;
    const parsed = typingSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({ error: 'Invalid payload' });
    }
    const auth = await authorizeWorkspaceMember(req, res, config, parsed.data.workspace_id);
    if (!auth) return;

    // Verify the conversation belongs to this workspace.
    const sb = getServiceClient(config);
    const { data: conv } = await sb
      .from('conversations')
      .select('id, workspace_id')
      .eq('id', parsed.data.conversation_id)
      .maybeSingle();
    if (!conv || conv.workspace_id !== parsed.data.workspace_id) {
      return res.status(404).json({ error: 'Conversation not found in workspace' });
    }

    // Phase 5C.1 — server-side typing suppression while the
    // disable_typing_temporarily auto-action is active. Drop without
    // touching the realtime publisher. Message send is unaffected.
    if (isActionActive('disable_typing_temporarily')) {
      emitLog(config, 'info', 'auto_action_effect_applied', {
        action_type: 'disable_typing_temporarily',
        workspace_id: parsed.data.workspace_id,
        conversation_id: parsed.data.conversation_id,
        surface: 'operator',
        ts: Date.now(),
      });
      return res.json({ ok: true, published: false, reason: 'auto_action_suppressed' });
    }

    const pub = await publishConversationEvent(
      config,
      parsed.data.workspace_id,
      parsed.data.conversation_id,
      {
        type: 'typing',
        payload: {
          actor: 'agent',
          conversation_id: parsed.data.conversation_id,
          ts: Date.now(),
        },
      },
    );
    return res.json({ ok: true, published: pub.ok });
  } catch (err: any) {
    console.error('[conversations/typing] error:', err);
    return res.status(500).json({ error: err?.message || 'Internal error' });
  }
});

conversationsRouter.post('/send-message', async (req, res) => {
  try {
    const config: ServerConfig = (req as any).serverConfig;
    const parsed = sendMessageSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Invalid payload',
        details: parsed.error.flatten().fieldErrors,
      });
    }

    const auth = await authorizeWorkspaceMember(req, res, config, parsed.data.workspace_id);
    if (!auth) return; // response already sent

    const sb = getServiceClient(config);

    // Verify the conversation belongs to this workspace.
    const { data: conv, error: convErr } = await sb
      .from('conversations')
      .select('id, workspace_id')
      .eq('id', parsed.data.conversation_id)
      .maybeSingle();
    if (convErr) return res.status(500).json({ error: convErr.message });
    if (!conv || conv.workspace_id !== parsed.data.workspace_id) {
      return res.status(404).json({ error: 'Conversation not found in workspace' });
    }

    // Insert message. body may be empty when only an attachment is sent.
    const messageBody = parsed.data.body || '';
    const clientMessageId = parsed.data.client_message_id ?? null;
    const baseMetadata: Record<string, unknown> = {
      ...(parsed.data.metadata ?? {}),
      source: (parsed.data.metadata as any)?.source ?? 'inbox',
    };
    if (parsed.data.attachment_id) baseMetadata.attachment_id = parsed.data.attachment_id;
    if (clientMessageId) baseMetadata.client_message_id = clientMessageId;

    const MESSAGE_COLUMNS =
      'id, conversation_id, sender_type, sender_id, body, created_at, metadata, seen_at';

    /**
     * Idempotency (double-click / client retry). The partial unique index from
     * migration 070 is the real guard — this lookup only avoids a pointless
     * failing insert. A replay returns the ORIGINAL message and skips the
     * outbound dispatch, so no second Telegram/WhatsApp/… delivery is queued.
     */
    let duplicate = false;
    let inserted: any = null;
    if (clientMessageId) {
      const { data: prior } = await sb
        .from('conversation_messages')
        .select(MESSAGE_COLUMNS)
        .eq('conversation_id', parsed.data.conversation_id)
        .filter('metadata->>client_message_id', 'eq', clientMessageId)
        .maybeSingle();
      if (prior) { inserted = prior; duplicate = true; }
    }

    if (!inserted) {
      const { data: row, error: insErr } = await sb
        .from('conversation_messages')
        .insert({
          conversation_id: parsed.data.conversation_id,
          body: messageBody,
          sender_type: 'agent',
          sender_id: auth.userId,
          metadata: baseMetadata,
        })
        .select(MESSAGE_COLUMNS)
        .single();
      if (insErr || !row) {
        // Lost the race against a concurrent replay of the same key.
        if (clientMessageId && /duplicate key|23505/i.test(insErr?.message || '')) {
          const { data: prior } = await sb
            .from('conversation_messages')
            .select(MESSAGE_COLUMNS)
            .eq('conversation_id', parsed.data.conversation_id)
            .filter('metadata->>client_message_id', 'eq', clientMessageId)
            .maybeSingle();
          if (prior) { inserted = prior; duplicate = true; }
        }
        if (!inserted) {
          return res.status(500).json({ error: insErr?.message || 'Insert failed' });
        }
      } else {
        inserted = row;
      }
    }


    // Phase 2 — Bind operator-uploaded attachment to this message + conversation.
    let attachmentBound = false;
    if (!duplicate && parsed.data.attachment_id && inserted?.id) {
      const ok = await attachUploadedFileToMessage(
        config,
        parsed.data.attachment_id,
        parsed.data.workspace_id,
        parsed.data.conversation_id,
        inserted.id,
      );
      attachmentBound = ok;
      if (!ok) {
        console.warn('[conversations/send-message] failed to attach',
          parsed.data.attachment_id, 'to', inserted.id);
      }
    }

    // Bump conversation timestamp (and reopen if needed).
    if (!duplicate) {
      await sb
        .from('conversations')
        .update({ updated_at: new Date().toISOString() })
        .eq('id', parsed.data.conversation_id);
    }

    // Channel bridge: if this conversation came from a plugin channel
    // (Telegram / Bale / WhatsApp / Instagram), make the delivery intent
    // durable. No-op for widget conversations. AWAITED, because Split Send may
    // only change the status once the transport accepted the reply.
    //
    // An attachment reply takes the MEDIA path: the DB trigger only enqueues
    // text, so a file-only (or file+caption) reply would otherwise never leave
    // the platform.
    let dispatch: { accepted: boolean; result: string };
    if (duplicate) {
      dispatch = { accepted: true, result: 'already_enqueued' };
    } else if (attachmentBound && parsed.data.attachment_id) {
      try {
        const mediaResult = await enqueueOutboundMediaIfChannelConversation(config, {
          workspaceId: parsed.data.workspace_id,
          conversationId: parsed.data.conversation_id,
          messageId: inserted.id,
          attachmentId: parsed.data.attachment_id,
          caption: messageBody,
          req: req as any,
        });
        dispatch = { accepted: true, result: mediaResult };
      } catch (err: any) {
        console.warn('[conversations/send-message] outbound media enqueue failed:', err?.message);
        dispatch = { accepted: false, result: 'failed' };
      }
    } else {
      dispatch = await dispatchOutboundIfChannelConversation(config, {
        workspaceId: parsed.data.workspace_id,
        conversationId: parsed.data.conversation_id,
        messageId: inserted.id,
        body: messageBody,
      });
    }




    // Enrich envelope with public-safe attachment metadata so the visitor
    // widget renders the file via its proxy route. Same shape as visitor flow.
    const [enriched] = await enrichMessagesWithAttachments(
      config, parsed.data.workspace_id, [inserted as any]
    );

    // Operator identity must travel WITH the realtime envelope — otherwise the
    // visitor sees the reply instantly but with a blank avatar until a reload
    // hits /poll or /history (which enrich the sender server-side).
    let senderProfile: { name: string | null; avatar: string | null } | null = null;
    if (auth.userId) {
      try {
        const { data: prof } = await sb
          .from('profiles')
          .select('full_name, avatar_url')
          .eq('id', auth.userId)
          .maybeSingle();
        if (prof) senderProfile = { name: (prof as any).full_name || null, avatar: (prof as any).avatar_url || null };
      } catch { /* avatar is cosmetic — never block the send */ }
    }

    // Publish to realtime — fire-and-forget semantics. A replayed request must
    // not emit a second message envelope.
    const pub = duplicate
      ? { ok: false, reason: 'duplicate_request' as string | null }
      : await publishConversationEvent(
          config,
          parsed.data.workspace_id,
          parsed.data.conversation_id,
          buildMessageEnvelope({
            ...(enriched as any),
            sender_id: auth.userId ?? null,
            sender_name: senderProfile?.name ?? null,
            sender_avatar: senderProfile?.avatar ?? null,
          }),
        );


    // Phase 3 — record attachment_added event (timeline-only) when applicable.
    if (!duplicate && parsed.data.attachment_id) {
      void recordConversationEvent(config, {
        workspaceId: parsed.data.workspace_id,
        conversationId: parsed.data.conversation_id,
        eventType: 'attachment_added',
        actorType: 'agent',
        actorId: auth.userId,
        payload: {
          message_id: inserted.id,
          attachment_id: parsed.data.attachment_id,
        },
      });
    }

    // AI Agent — explicit human takeover marker. Once an operator replies,
    // the conversation leaves the Automated inbox and the AI must back off
    // (in `auto_reply_until_human_joins` and, by default, also in
    // `auto_reply_always` via pause_auto_reply_after_human_reply=true).
    void markHumanTakeover(config, {
      workspaceId: parsed.data.workspace_id,
      conversationId: parsed.data.conversation_id,
      operatorId: auth.userId,
      reason: 'operator_replied',
    }).catch((e: any) =>
      console.warn('[conversations/send-message] markHumanTakeover failed:', e?.message),
    );

    // AI Agent — learning candidate v1. Pair this operator reply with the
    // visitor's last question if the AI recently bailed out. Best-effort.
    if (!duplicate && inserted?.id && (parsed.data.body || '').trim().length > 0) {
      void maybeCreateLearningCandidateFromOperatorReply(config, {
        workspaceId: parsed.data.workspace_id,
        conversationId: parsed.data.conversation_id,
        operatorMessageId: inserted.id,
        operatorMessageBody: parsed.data.body || '',
        operatorId: auth.userId,
      }).catch((e: any) =>
        console.warn('[conversations/send-message] learning candidate hook failed:', e?.message),
      );
    }

    // Split Send — optional status transition, applied ONLY now that the
    // message really exists AND the transport accepted it. Shared by every
    // channel (widget / Telegram / Bale / WhatsApp / Instagram) because they
    // all send through this route. The transition itself is decided inside the
    // DB (row lock + "no newer customer message" guard).
    const postSend = await applyPostSendAction(config, {
      action: parsed.data.post_send_action,
      workspaceId: parsed.data.workspace_id,
      conversationId: parsed.data.conversation_id,
      actorId: auth.userId,
      messageId: inserted.id,
      deliveryAccepted: dispatch.accepted,
      ipAddress: (req.headers['x-forwarded-for'] as string)?.split(',')[0]?.trim()
        || req.socket?.remoteAddress || null,
    });


    return res.json({
      ok: true,
      message: enriched,
      duplicate,
      delivery: { accepted: dispatch.accepted, result: dispatch.result },
      realtime: { published: pub.ok, reason: pub.reason ?? null },
      post_send: {
        action: parsed.data.post_send_action,
        changed: postSend.changed,
        status: postSend.status ?? null,
        reason: postSend.reason ?? null,
        blocked: postSend.blocked ?? null,
      },
    });


  } catch (err: any) {
    console.error('[conversations/send-message] error:', err);
    return res.status(500).json({ error: err?.message || 'Internal error' });
  }
});

// ═══════════════════════════════════════════════════════════════════
// POST /api/conversations/start-from-visitor
//
// Operator-initiated outreach from the Visitors page. Given a visitor
// session, returns an existing open conversation (most-recent) or
// creates a fresh one tied to that session + its contact (if any).
// Idempotent for repeated clicks: an open conversation is reused.
// ═══════════════════════════════════════════════════════════════════
conversationsRouter.post('/start-from-visitor', async (req, res) => {
  try {
    const config: ServerConfig = (req as any).serverConfig;
    const parsed = startFromVisitorSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Invalid payload',
        details: parsed.error.flatten().fieldErrors,
      });
    }
    const auth = await authorizeWorkspaceMember(req, res, config, parsed.data.workspace_id);
    if (!auth) return;

    const sb = getServiceClient(config);

    // Verify the visitor session belongs to this workspace.
    const { data: session, error: sessErr } = await sb
      .from('visitor_sessions')
      .select('id, workspace_id, contact_id, visitor_id')
      .eq('id', parsed.data.visitor_session_id)
      .eq('workspace_id', parsed.data.workspace_id)
      .maybeSingle();
    if (sessErr) return res.status(500).json({ error: sessErr.message });
    if (!session) return res.status(404).json({ error: 'Visitor session not found' });

    // Reuse the most-recent NON-resolved/closed conversation for this
    // visitor session if one exists — avoids spawning duplicates when
    // operators click the button multiple times.
    const { data: existing } = await sb
      .from('conversations')
      .select('id, status')
      .eq('workspace_id', parsed.data.workspace_id)
      .eq('visitor_session_id', parsed.data.visitor_session_id)
      .in('status', ['open', 'pending'])
      .order('updated_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (existing?.id) {
      return res.json({ ok: true, conversation_id: existing.id, created: false });
    }

    // Phase 5 — enforce max_conversations only on the actual creation
    // branch. Reuse of an existing open/pending conversation above does
    // not count. workspace_id is already verified via authorizeWorkspaceMember.
    {
      const ok = await enforceMaxConversationsLimit(req, res);
      if (!ok) return;
    }

    // Create a new conversation. We do NOT seed a message — the operator
    // composes their first message in the inbox, which routes through the
    // existing /send-message endpoint (carrying realtime publish, attachments,
    // and timeline events for free).
    const { data: created, error: createErr } = await sb
      .from('conversations')
      .insert({
        workspace_id: parsed.data.workspace_id,
        visitor_session_id: parsed.data.visitor_session_id,
        contact_id: session.contact_id ?? null,
        status: 'open',
        priority: 'normal',
      })
      .select('id')
      .single();

    if (createErr || !created) {
      return res.status(500).json({ error: createErr?.message || 'Create failed' });
    }

    // Timeline event so the inbox shows where this conversation came from.
    void recordConversationEvent(config, {
      workspaceId: parsed.data.workspace_id,
      conversationId: created.id,
      eventType: 'conversation_started',
      actorType: 'agent',
      actorId: auth.userId,
      payload: {
        source: 'visitor_outreach',
        visitor_session_id: parsed.data.visitor_session_id,
        visitor_id: session.visitor_id,
      },
    });

    return res.json({ ok: true, conversation_id: created.id, created: true });
  } catch (err: any) {
    console.error('[conversations/start-from-visitor] error:', err);
    return res.status(500).json({ error: err?.message || 'Internal error' });
  }
});

// ═══════════════════════════════════════════════════════════════════
// Phase 3 — PATCH /api/conversations/:id
// Editable fields: status, priority, assigned_to, tags
// Each change records a normalized conversation_events row + audit_log.
// We intentionally do NOT add a new realtime envelope type — the
// 'message'|'typing'|'seen' contract stays untouched. Inbox refreshes
// via React Query invalidation on the success response. Widget is unaffected.
// ═══════════════════════════════════════════════════════════════════
const patchConversationSchema = z.object({
  workspace_id: z.string().uuid(),
  status: z.enum(ALLOWED_STATUSES).optional(),
  priority: z.enum(ALLOWED_PRIORITIES).optional(),
  assigned_to: z.string().uuid().nullable().optional(),
  tags: z.array(z.string().min(1).max(50)).max(20).optional(),
}).refine(
  d => d.status !== undefined || d.priority !== undefined
    || d.assigned_to !== undefined || d.tags !== undefined,
  { message: 'No editable field provided' }
);

conversationsRouter.patch('/:id', async (req, res) => {
  try {
    const config: ServerConfig = (req as any).serverConfig;
    const parsed = patchConversationSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Invalid payload',
        details: parsed.error.flatten().fieldErrors,
      });
    }
    const auth = await authorizeWorkspaceMember(req, res, config, parsed.data.workspace_id);
    if (!auth) return;

    const sb = getServiceClient(config);
    const conversationId = req.params.id;

    // Load current row to verify workspace ownership AND compute the diff.
    const { data: before, error: loadErr } = await sb
      .from('conversations')
      .select('id, workspace_id, status, priority, assigned_to, tags')
      .eq('id', conversationId)
      .maybeSingle();
    if (loadErr) return res.status(500).json({ error: loadErr.message });
    if (!before || before.workspace_id !== parsed.data.workspace_id) {
      return res.status(404).json({ error: 'Conversation not found in workspace' });
    }

    // Verify the assignee (if any) is also a workspace member.
    if (parsed.data.assigned_to) {
      const { data: targetIsMember } = await sb.rpc('is_workspace_member', {
        _workspace_id: parsed.data.workspace_id,
        _user_id: parsed.data.assigned_to,
      });
      if (!targetIsMember) {
        return res.status(400).json({ error: 'Assignee is not a workspace member' });
      }
    }

    // Build the update set. Tags are normalized (trim, dedupe, lowercase).
    const update: Record<string, unknown> = { updated_at: new Date().toISOString() };
    if (parsed.data.status !== undefined) update.status = parsed.data.status;
    if (parsed.data.priority !== undefined) update.priority = parsed.data.priority;
    if (parsed.data.assigned_to !== undefined) update.assigned_to = parsed.data.assigned_to;
    let normalizedTags: string[] | undefined;
    if (parsed.data.tags !== undefined) {
      const seen = new Set<string>();
      normalizedTags = [];
      for (const raw of parsed.data.tags) {
        const tag = String(raw).trim().toLowerCase();
        if (!tag || seen.has(tag)) continue;
        seen.add(tag);
        normalizedTags.push(tag);
      }
      update.tags = normalizedTags;
    }

    const { data: after, error: updErr } = await sb
      .from('conversations')
      .update(update)
      .eq('id', conversationId)
      .select('id, workspace_id, status, priority, assigned_to, tags, updated_at')
      .single();
    if (updErr || !after) {
      return res.status(500).json({ error: updErr?.message || 'Update failed' });
    }

    // ─── Record events + audit per changed field ───
    const ip = (req.headers['x-forwarded-for'] as string)?.split(',')[0]?.trim()
      || req.socket?.remoteAddress
      || null;

    const eventBase = {
      workspaceId: parsed.data.workspace_id,
      conversationId,
      actorType: 'agent' as const,
      actorId: auth.userId,
      ipAddress: ip,
    };

    // Build a single `conversation_updated` payload describing every field
    // that actually changed. Used for the realtime `event` envelope below.
    const changes: Record<string, { from: unknown; to: unknown } | { added: string[]; removed: string[] }> = {};
    let statusEvType: 'status_changed' | 'resolved' | 'reopened' | null = null;

    if (parsed.data.status !== undefined && before.status !== parsed.data.status) {
      const wasResolved = before.status === 'resolved' || before.status === 'closed';
      const nowResolved = parsed.data.status === 'resolved' || parsed.data.status === 'closed';
      statusEvType = 'status_changed';
      if (!wasResolved && nowResolved) statusEvType = 'resolved';
      else if (wasResolved && !nowResolved) statusEvType = 'reopened';
      changes.status = { from: before.status, to: parsed.data.status };
      void recordAuditAndEvent(config, {
        ...eventBase,
        eventType: statusEvType,
        auditAction: 'conversation.status_changed',
        oldValue: { status: before.status },
        newValue: { status: parsed.data.status },
        // Machine-readable reason so an operator reopen is never confused
        // with the automatic `customer_replied` resume.
        payload: {
          from: before.status,
          to: parsed.data.status,
          reason:
            parsed.data.status === 'open' && before.status !== 'open'
              ? 'manually_reopened'
              : 'manual_status_change',
          source: 'operator_status_change',
        },

      });

    }

    if (parsed.data.priority !== undefined && before.priority !== parsed.data.priority) {
      changes.priority = { from: before.priority, to: parsed.data.priority };
      void recordAuditAndEvent(config, {
        ...eventBase,
        eventType: 'priority_changed',
        auditAction: 'conversation.priority_changed',
        oldValue: { priority: before.priority },
        newValue: { priority: parsed.data.priority },
        payload: { from: before.priority, to: parsed.data.priority },
      });
    }

    if (parsed.data.assigned_to !== undefined && before.assigned_to !== parsed.data.assigned_to) {
      changes.assigned_to = { from: before.assigned_to, to: parsed.data.assigned_to };
      void recordAuditAndEvent(config, {
        ...eventBase,
        eventType: parsed.data.assigned_to ? 'assigned' : 'unassigned',
        auditAction: parsed.data.assigned_to ? 'conversation.assigned' : 'conversation.unassigned',
        oldValue: { assigned_to: before.assigned_to },
        newValue: { assigned_to: parsed.data.assigned_to },
        payload: { from: before.assigned_to, to: parsed.data.assigned_to },
      });

      // Operator-visible transfer notice inside the thread itself
      // ("X transferred this conversation to Y"). Internal-only: the widget
      // filters `metadata.internal === true` out of /poll and /history, so
      // the visitor never sees internal staffing moves.
      void (async () => {
        try {
          const ids = [auth.userId, before.assigned_to, parsed.data.assigned_to]
            .filter((v): v is string => !!v);
          const nameById = new Map<string, string>();
          if (ids.length) {
            const { data: people } = await sb
              .from('profiles')
              .select('id, full_name')
              .in('id', Array.from(new Set(ids)));
            (people || []).forEach((p: any) => {
              if (p?.full_name) nameById.set(p.id, p.full_name as string);
            });
          }
          const actorName = nameById.get(auth.userId) || null;
          const fromName = before.assigned_to ? (nameById.get(before.assigned_to) || null) : null;
          const toName = parsed.data.assigned_to ? (nameById.get(parsed.data.assigned_to) || null) : null;
          const body = toName
            ? `${actorName || 'An operator'} transferred this conversation to ${toName}`
            : `${actorName || 'An operator'} unassigned this conversation`;
          await sb.from('conversation_messages').insert({
            conversation_id: conversationId,
            sender_type: 'system',
            body,
            metadata: {
              kind: parsed.data.assigned_to ? 'conversation_transferred' : 'conversation_unassigned',
              internal: true,
              actor_id: auth.userId,
              actor_name: actorName,
              from_id: before.assigned_to,
              from_name: fromName,
              to_id: parsed.data.assigned_to,
              to_name: toName,
            },
          });
        } catch (e: any) {
          console.warn('[conversations PATCH] transfer notice failed:', e?.message || e);
        }
      })();
    }


    if (normalizedTags !== undefined) {
      const beforeTags = new Set<string>((before.tags as string[] | null) ?? []);
      const afterTags = new Set<string>(normalizedTags);
      const added = [...afterTags].filter(t => !beforeTags.has(t));
      const removed = [...beforeTags].filter(t => !afterTags.has(t));
      if (added.length || removed.length) {
        changes.tags = { added, removed };
      }
      for (const tag of added) {
        void recordConversationEvent(config, {
          ...eventBase,
          eventType: 'tag_added',
          payload: { tag },
        });
      }
      for (const tag of removed) {
        void recordConversationEvent(config, {
          ...eventBase,
          eventType: 'tag_removed',
          payload: { tag },
        });
      }
    }

    // ─── Realtime push (Phase 5) ───
    // Operator-only `event` envelope. Fans out to the per-conversation
    // channel AND the workspace inbox channel. Best-effort, non-blocking.
    if (Object.keys(changes).length > 0) {
      const kind: OperatorEventPayload['kind'] =
        statusEvType === 'resolved' ? 'conversation_resolved'
        : statusEvType === 'reopened' ? 'conversation_reopened'
        : 'conversation_updated';
      void publishOperatorEvent(config, {
        kind,
        conversation_id: conversationId,
        workspace_id: parsed.data.workspace_id,
        actor_id: auth.userId,
        changes,
        updated_at: after.updated_at,
      });
    }

    return res.json({ ok: true, conversation: after });
  } catch (err: any) {
    console.error('[conversations PATCH] error:', err);
    return res.status(500).json({ error: err?.message || 'Internal error' });
  }
});

// ═══════════════════════════════════════════════════════════════════
// POST /api/conversations/:id/claim
// Manual-routing-mode claim: the first operator to claim an unassigned
// conversation owns it. Atomic via public.claim_conversation() — unlike
// the PATCH assigned_to path above (a plain read-then-write, fine for a
// deliberate reassignment by anyone with permission), this is a
// compare-and-set so two operators racing to claim the same conversation
// can never both succeed.
// ═══════════════════════════════════════════════════════════════════
const claimConversationSchema = z.object({
  workspace_id: z.string().uuid(),
});

conversationsRouter.post('/:id/claim', async (req, res) => {
  try {
    const config: ServerConfig = (req as any).serverConfig;
    const parsed = claimConversationSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({ error: 'Invalid payload', details: parsed.error.flatten().fieldErrors });
    }
    const auth = await authorizeWorkspaceMember(req, res, config, parsed.data.workspace_id);
    if (!auth) return;

    const sb = getServiceClient(config);
    const conversationId = req.params.id;
    const { data: before } = await sb
      .from('conversations')
      .select('id, workspace_id, assigned_to')
      .eq('id', conversationId)
      .maybeSingle();
    if (!before || before.workspace_id !== parsed.data.workspace_id) {
      return res.status(404).json({ error: 'Conversation not found in workspace' });
    }

    const { claimConversationManually } = await import('../services/chatRouting.js');
    const result = await claimConversationManually(config, {
      workspaceId: parsed.data.workspace_id,
      conversationId,
      userId: auth.userId,
    });

    if (!result.claimed) {
      return res.status(409).json({
        error: 'already_claimed',
        assigned_to: result.assignedTo,
      });
    }

    void recordAuditAndEvent(config, {
      workspaceId: parsed.data.workspace_id,
      conversationId,
      actorType: 'agent',
      actorId: auth.userId,
      eventType: 'assigned',
      auditAction: 'conversation.claimed',
      oldValue: { assigned_to: before.assigned_to },
      newValue: { assigned_to: auth.userId },
      payload: { from: before.assigned_to, to: auth.userId, method: 'manual_claim' },
    });

    return res.json({ ok: true, assigned_to: auth.userId });
  } catch (err: any) {
    console.error('[conversations claim] error:', err);
    return res.status(500).json({ error: err?.message || 'Internal error' });
  }
});

// ─── Spam routing ─────────────────────────────────────────────────────
// POST /api/conversations/spam       → mark spam
// POST /api/conversations/not-spam   → clear spam flag
//
// Soft routing only. Marking spam:
//   • flags the conversation (and the contact, if any, plus all their
//     other conversations) so they move to the Spam queue
//   • prevents the AI Agent from auto-replying or generating suggestions
//   • does NOT close the conversation, delete history, or block the
//     visitor — Block is a separate, deliberate action.
const spamSchema = z.object({
  workspace_id: z.string().uuid(),
  conversation_id: z.string().uuid(),
});

conversationsRouter.post('/spam', async (req: any, res: any) => {
  const config = (req as any).serverConfig as ServerConfig;
  const parsed = spamSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: 'invalid_params' });
  const auth = await authorizeWorkspaceMember(req, res, config, parsed.data.workspace_id);
  if (!auth) return;
  try {
    const result = await markSpam(config, {
      workspaceId: parsed.data.workspace_id,
      conversationId: parsed.data.conversation_id,
      operatorId: auth.userId,
    });
    // Realtime: nudge every operator's inbox to re-fetch — the affected
    // conversation(s) move between queues (Main/Automated/NeedsHuman → Spam).
    for (const cid of result.conversation_ids) {
      void publishOperatorEvent(config, {
        kind: 'spam_changed',
        conversation_id: cid,
        workspace_id: parsed.data.workspace_id,
        actor_id: auth.userId,
        is_spam: true,
        contact_id: result.contact_id,
      });
    }
    return res.json(result);
  } catch (err: any) {
    if (err?.message === 'conversation_not_found') {
      return res.status(404).json({ error: 'conversation_not_found' });
    }
    console.error('[conversations spam] error:', err);
    return res.status(500).json({ error: err?.message || 'Internal error' });
  }
});

// ═══════════════════════════════════════════════════════════════════
// GET / — Inbox list.
//
// Replaces src/hooks/useConversations.ts's direct
// supabase.from('conversations').select('*, contacts(...)') query, which
// relied on RLS scoped to auth.uid() and silently returned nothing once
// the dashboard stopped carrying a Supabase Auth session. Reproduces the
// exact queue/status/needs-human/assigned-to-me filtering, the contact
// join, the last-message/last-visitor-message/unread-count enrichment,
// and the "unanswered AI-intro thread" exclusion from Main Inbox — all
// previously computed client-side against two direct Supabase reads.
//
// Visitor network-profile enrichment (geo/IP/device) is intentionally
// NOT duplicated here: it already goes through the authenticated
// POST /api/visitor-intel/network/batch route (see
// src/hooks/useVisitorNetwork.ts), so the frontend hook calls that
// separately after this list resolves, exactly as it does today.
// ═══════════════════════════════════════════════════════════════════
const listQuerySchema = z.object({
  workspace_id: z.string().uuid(),
  queue: z.enum(['main', 'automated', 'spam']).optional().default('main'),
  status: z.string().max(200).optional(),
  needs_human: z.enum(['true', 'false']).optional(),
  assigned_to_me: z.string().uuid().optional(),
  // Assignment scope. Default 'mine': every operator — owners and admins
  // included — only sees unassigned threads plus the ones assigned to them,
  // so a transferred conversation leaves the sender's Inbox immediately.
  // 'all' is the explicit full-workspace view, allowed for privileged roles.
  scope: z.enum(['mine', 'all']).optional().default('mine'),
});

conversationsRouter.get('/', async (req: any, res: any) => {
  try {
    const config: ServerConfig = (req as any).serverConfig;
    const parsed = listQuerySchema.safeParse(req.query);
    if (!parsed.success) {
      return res.status(400).json({ error: 'Invalid query', details: parsed.error.flatten().fieldErrors });
    }
    const { workspace_id, queue, status, assigned_to_me, scope } = parsed.data;
    const needsHuman = parsed.data.needs_human === 'true';
    const auth = await authorizeWorkspaceMember(req, res, config, workspace_id);
    if (!auth) return;
    const isPrivileged =
      auth.isAdmin || auth.role === 'owner' || auth.role === 'admin' || auth.role === 'team_lead';
    // Privileged roles keep the full view ONLY when they explicitly ask for
    // it (scope=all). Otherwise their Inbox behaves like an operator's.
    const canSeeAllAssignments = isPrivileged && scope === 'all';

    const sb = getServiceClient(config);
    let q = sb
      .from('conversations')
      .select('*, contacts(name, email, avatar_url, visitor_code, metadata)')
      .eq('workspace_id', workspace_id)
      .order('updated_at', { ascending: false });

    if (queue === 'automated') {
      q = q.eq('ai_state', 'ai_managed').neq('status', 'closed').is('assigned_to', null).eq('is_spam', false);
    } else if (queue === 'spam') {
      q = q.eq('is_spam', true);
    } else {
      q = q.eq('is_spam', false);
      if (needsHuman) {
        q = q.eq('ai_state', 'needs_human');
      } else {
        q = q.or('ai_state.is.null,ai_state.neq.ai_managed');
      }
      if (assigned_to_me) {
        q = q.eq('assigned_to', assigned_to_me);
      } else if (!canSeeAllAssignments) {
        // A claimed conversation belongs to the operator who took it: other
        // agents must not keep seeing it in their Inbox. Owners/admins and
        // team leads still get the full workspace view.
        q = q.or(`assigned_to.is.null,assigned_to.eq.${auth.userId}`);
      }
      if (status && status !== 'all') {
        const parts = status.split(',').map((x) => x.trim()).filter(Boolean);
        q = parts.length > 1 ? q.in('status', parts) : q.eq('status', parts[0]);
      }
    }

    const { data, error } = await q;
    if (error) return res.status(500).json({ error: error.message });
    const convos = (data || []) as any[];

    const ids = convos.map((c) => c.id).filter(Boolean);
    if (ids.length > 0) {
      const { data: msgs } = await sb
        .from('conversation_messages')
        .select('conversation_id, body, created_at, sender_type, sender_id, seen_at, metadata')
        .in('conversation_id', ids)
        // Bot menu/button taps are navigation, not chat content — keep them
        // out of the fetch window entirely so a visitor browsing the bot menu
        // can never push the real last message out of the preview.
        .or('metadata->>channel_menu_event.is.null,metadata->>channel_menu_event.neq.true')
        .order('created_at', { ascending: false })
        .limit(2000);

      const byConv: Record<string, { body: string; created_at: string; seen_at: string | null }> = {};
      const lastByConv: Record<string, { body: string; created_at: string; sender_type: string; sender_id?: string | null; sender_name?: string | null; attachment_id?: string | null; attachment_kind?: 'image' | 'audio' | 'video' | 'file' | null; system_kind?: string | null; actor_name?: string | null; to_name?: string | null }> = {};
      // Human operators who ever wrote in the thread — drives "who handled
      // this" visibility for resolved threads and the list preview label.
      const agentParticipants: Record<string, Set<string>> = {};
      const unreadByConv: Record<string, number> = {};
      // Needs Reply is derived from the message stream, never stored. Rows
      // arrive newest-first, so the FIRST conversational turn we see per
      // conversation decides the obligation (see services/needsReply.ts).
      const needsReplyByConv: Record<string, boolean> = {};
      const needsReplyDecided = new Set<string>();
      // Oldest actionable customer turn of the CURRENT unanswered streak, so
      // the Inbox can rank by real waiting age instead of `updated_at` (which
      // assignment, routing metadata and delivery receipts also bump).
      const waitingSinceByConv: Record<string, string | null> = {};
      for (const m of (msgs || []) as any[]) {
        if (!m.conversation_id) continue;
        // Channel menu/button taps are navigation, not conversation content:
        // they must never drive the list preview or the unread badge. Older
        // rows may carry the flag as a boolean, and menu taps written before
        // the flag existed still carry `channel_menu_command`.
        const meta = (m.metadata || {}) as Record<string, unknown>;
        const isMenuEvent =
          String(meta.channel_menu_event ?? '') === 'true' || !!meta.channel_menu_command;
        if (isMenuEvent) continue;

        if (!lastByConv[m.conversation_id]) {
          lastByConv[m.conversation_id] = {
            body: m.body ?? '',
            created_at: m.created_at,
            sender_type: m.sender_type,
            sender_id: m.sender_id ?? null,
            sender_name: null,
            // A file-only message has an empty body: the list preview must
            // describe the media instead of claiming "no messages yet".
            attachment_id: (meta as any)?.attachment_id ? String((meta as any).attachment_id) : null,
            attachment_kind: null,
            // System notices (transfer / unassign) are stored in English:
            // ship the structured metadata so the UI can localize the preview.
            system_kind: (meta as any)?.kind ? String((meta as any).kind) : null,
            actor_name: (meta as any)?.actor_name ? String((meta as any).actor_name) : null,
            to_name: (meta as any)?.to_name ? String((meta as any).to_name) : null,
          };
        }
        if (m.sender_type === 'agent' && m.sender_id) {
          (agentParticipants[m.conversation_id] ||= new Set<string>()).add(String(m.sender_id));
        }


        // Rows arrive newest-first. The first conversational turn decides the
        // obligation; we then keep walking back over the customer streak to
        // find when the wait actually started.
        if (isQualifiedCustomerFacingAnswer(m as any)) {
          if (!needsReplyDecided.has(m.conversation_id)) {
            needsReplyByConv[m.conversation_id] = false;
          }
          needsReplyDecided.add(m.conversation_id);
        } else if (isActionableCustomerTurn(m as any)) {
          if (!needsReplyDecided.has(m.conversation_id)) {
            needsReplyByConv[m.conversation_id] = true;
            waitingSinceByConv[m.conversation_id] = m.created_at ?? null;
          } else if (needsReplyByConv[m.conversation_id]) {
            // Still inside the unanswered streak → the wait began earlier.
            waitingSinceByConv[m.conversation_id] = m.created_at ?? null;
          }
        }

        if (m.sender_type !== 'contact') continue;
        if (!byConv[m.conversation_id]) {
          byConv[m.conversation_id] = { body: m.body ?? '', created_at: m.created_at, seen_at: m.seen_at ?? null };
        }
        if (!m.seen_at) {
          unreadByConv[m.conversation_id] = (unreadByConv[m.conversation_id] ?? 0) + 1;
        }
      }

      // Resolve the media kind of every attachment-only preview in one query,
      // so the Inbox list can say "sent a photo / voice message / file".
      const previewAttachmentIds = Array.from(new Set(
        Object.values(lastByConv)
          .filter((l) => l.attachment_id && !String(l.body || '').trim())
          .map((l) => l.attachment_id as string),
      ));
      if (previewAttachmentIds.length) {
        const { data: atts } = await sb
          .from('conversation_attachments')
          .select('id, mime_type')
          .in('id', previewAttachmentIds);
        const mimeById = new Map<string, string>(
          ((atts || []) as any[]).map((a) => [String(a.id), String(a.mime_type || '')]),
        );
        for (const last of Object.values(lastByConv)) {
          if (!last.attachment_id) continue;
          const mime = mimeById.get(last.attachment_id) || '';
          last.attachment_kind = mime.startsWith('image/')
            ? 'image'
            : mime.startsWith('audio/')
              ? 'audio'
              : mime.startsWith('video/')
                ? 'video'
                : 'file';
        }
      }

      // Resolve display names for the operators whose message is the list
      // preview, so the row reads "Ali: …" instead of always "You: …".
      const agentSenderIds = Array.from(new Set(
        Object.values(lastByConv)
          .filter((l) => l.sender_type === 'agent' && l.sender_id)
          .map((l) => String(l.sender_id)),
      ));
      if (agentSenderIds.length) {
        const { data: profs } = await sb
          .from('profiles')
          .select('id, full_name, email')
          .in('id', agentSenderIds);
        const nameById = new Map<string, string>(
          ((profs || []) as any[]).map((p) => [
            String(p.id),
            String(p.full_name || String(p.email || '').split('@')[0] || ''),
          ]),
        );
        for (const last of Object.values(lastByConv)) {
          if (last.sender_type !== 'agent' || !last.sender_id) continue;
          last.sender_name = nameById.get(String(last.sender_id)) || null;
        }
      }

      for (const c of convos) {
        c.last_visitor_message = byConv[c.id] ?? null;
        c.last_message = lastByConv[c.id] ?? null;
        c.unread_count = unreadByConv[c.id] ?? 0;
        c.handled_by = Array.from(agentParticipants[c.id] ?? []);
        // Only an `open` thread can owe the customer an answer: `pending`
        // means we are waiting for THEM, `resolved`/`closed` are done.
        c.needs_reply = c.status === 'open' && (needsReplyByConv[c.id] ?? false);
        c.waiting_since = c.needs_reply ? (waitingSinceByConv[c.id] ?? null) : null;
      }
    }

    let result = convos;
    if (queue === 'main') {
      // AI greeting threads (source='ai_agent_intro') the visitor never
      // answered are not human-actionable — exclude them from Main Inbox
      // unless a human has already touched the thread.
      result = convos.filter((c) => {
        const meta = c?.metadata || {};
        const introOnly = meta.source === 'ai_agent_intro' && !c.last_visitor_message;
        const humanTouched = !!c.assigned_to || c.ai_state === 'human_active'
          || (c.last_message && c.last_message.sender_type === 'agent');
        return !introOnly || humanTouched;
      });
    }

    // A finished thread belongs to whoever actually handled it. An operator
    // must not see resolved/closed threads that another operator answered,
    // even when nobody claimed them (`assigned_to` stays null on the
    // "send & resolve" path). Owners/admins/team leads keep the full view.
    if (!canSeeAllAssignments) {
      result = result.filter((c) => {
        if (c.status !== 'resolved' && c.status !== 'closed') return true;
        if (c.assigned_to && c.assigned_to !== auth.userId) return false;
        const handled: string[] = Array.isArray(c.handled_by) ? c.handled_by : [];
        if (handled.length === 0) return true; // AI/system resolved → shared
        return handled.includes(auth.userId);
      });
    }

    return res.json({ conversations: result });
  } catch (err: any) {
    console.error('[conversations list] error:', err);
    return res.status(500).json({ error: err?.message || 'Internal error' });
  }
});

// ─── Sidebar inbox counters ─────────────────────────────────────────
conversationsRouter.get('/inbox-counts', async (req: any, res: any) => {
  try {
    const config: ServerConfig = (req as any).serverConfig;
    const workspaceId = String(req.query.workspace_id || '');
    if (!workspaceId) return res.status(400).json({ error: 'workspace_id is required' });
    const auth = await authorizeWorkspaceMember(req, res, config, workspaceId);
    if (!auth) return;

    const sb = getServiceClient(config);
    const seesAll =
      (auth.isAdmin || auth.role === 'owner' || auth.role === 'admin' || auth.role === 'team_lead')
      && String(req.query.scope || 'mine') === 'all';
    const base = () => {
      const q = sb.from('conversations').select('id', { count: 'exact', head: true }).eq('workspace_id', workspaceId);
      return seesAll ? q : q.or(`assigned_to.is.null,assigned_to.eq.${auth.userId}`);
    };
    const [mainRes, autoRes, needsRes, spamRes] = await Promise.all([
      base().eq('is_spam', false).neq('status', 'closed').or('ai_state.is.null,ai_state.neq.ai_managed'),
      base().eq('is_spam', false).neq('status', 'closed').eq('ai_state', 'ai_managed').is('assigned_to', null),
      base().eq('is_spam', false).neq('status', 'closed').eq('ai_state', 'needs_human'),
      base().eq('is_spam', true),
    ]);
    return res.json({
      main: mainRes.count ?? 0,
      automated: autoRes.count ?? 0,
      needs_human: needsRes.count ?? 0,
      spam: spamRes.count ?? 0,
    });
  } catch (err: any) {
    console.error('[conversations inbox-counts] error:', err);
    return res.status(500).json({ error: err?.message || 'Internal error' });
  }
});

// ─── Per-tab counters for the Main Inbox status tabs ─────────────────
conversationsRouter.get('/inbox-tab-counts', async (req: any, res: any) => {
  try {
    const config: ServerConfig = (req as any).serverConfig;
    const workspaceId = String(req.query.workspace_id || '');
    if (!workspaceId) return res.status(400).json({ error: 'workspace_id is required' });
    const auth = await authorizeWorkspaceMember(req, res, config, workspaceId);
    if (!auth) return;

    const sb = getServiceClient(config);
    const seesAll =
      (auth.isAdmin || auth.role === 'owner' || auth.role === 'admin' || auth.role === 'team_lead')
      && String(req.query.scope || 'mine') === 'all';
    const scopeAssignment = (q: any) =>
      seesAll ? q : q.or(`assigned_to.is.null,assigned_to.eq.${auth.userId}`);
    const base = () =>
      scopeAssignment(sb.from('conversations').select('id', { count: 'exact', head: true })
        .eq('workspace_id', workspaceId).eq('is_spam', false).or('ai_state.is.null,ai_state.neq.ai_managed'));
    /* The AI tab lives outside `base()` scope: it counts exactly the
       ai_managed threads that base() excludes. */
    const automatedQuery = scopeAssignment(sb.from('conversations').select('id', { count: 'exact', head: true })
      .eq('workspace_id', workspaceId).eq('is_spam', false).eq('ai_state', 'ai_managed'));
    const [openRes, pendingRes, resolvedRes, allRes, needsRes, automatedRes] = await Promise.all([
      base().eq('status', 'open'),
      base().eq('status', 'pending'),
      base().in('status', ['resolved', 'closed']),
      base(),
      base().eq('ai_state', 'needs_human'),
      automatedQuery,
    ]);
    // Same ownership rule as the list: a finished thread another operator
    // handled is not part of this operator's Resolved tab.
    let resolvedCount = resolvedRes.count ?? 0;
    if (!seesAll && resolvedCount > 0) {
      const { data: resolvedRows } = await sb
        .from('conversations')
        .select('id, assigned_to')
        .eq('workspace_id', workspaceId)
        .eq('is_spam', false)
        .in('status', ['resolved', 'closed'])
        .or(`assigned_to.is.null,assigned_to.eq.${auth.userId}`)
        .limit(2000);
      const rows = (resolvedRows || []) as any[];
      const ids = rows.map((r) => r.id);
      const handled: Record<string, Set<string>> = {};
      if (ids.length) {
        const { data: agentMsgs } = await sb
          .from('conversation_messages')
          .select('conversation_id, sender_id')
          .in('conversation_id', ids)
          .eq('sender_type', 'agent')
          .limit(5000);
        for (const m of (agentMsgs || []) as any[]) {
          if (!m.sender_id) continue;
          (handled[m.conversation_id] ||= new Set<string>()).add(String(m.sender_id));
        }
      }
      resolvedCount = rows.filter((r) => {
        if (r.assigned_to && r.assigned_to !== auth.userId) return false;
        const set = handled[r.id];
        return !set || set.size === 0 || set.has(auth.userId);
      }).length;
    }
    return res.json({
      open: openRes.count ?? 0,
      pending: pendingRes.count ?? 0,
      resolved: resolvedCount,
      all: allRes.count ?? 0,
      needs_human: needsRes.count ?? 0,
      automated: automatedRes.count ?? 0,
    });

  } catch (err: any) {
    console.error('[conversations inbox-tab-counts] error:', err);
    return res.status(500).json({ error: err?.message || 'Internal error' });
  }
});

// ═══════════════════════════════════════════════════════════════════
// GET /:id/messages — thread for one conversation, enriched with
// attachment metadata and sender identity (name + avatar).
//
// Replaces src/hooks/useConversations.ts's direct reads of
// conversation_messages / conversation_attachments / profiles.
// Authorization derives from the conversation's OWN workspace_id, not
// a client-supplied one — a caller cannot probe an arbitrary
// conversation id by guessing/forging a workspace_id query param.
// ═══════════════════════════════════════════════════════════════════
conversationsRouter.get('/:id/messages', async (req: any, res: any) => {
  try {
    const config: ServerConfig = (req as any).serverConfig;
    const conversationId = req.params.id;
    const sb = getServiceClient(config);

    const { data: conv } = await sb
      .from('conversations')
      .select('id, workspace_id')
      .eq('id', conversationId)
      .maybeSingle();
    if (!conv) return res.status(404).json({ error: 'conversation_not_found' });

    const auth = await authorizeWorkspaceMember(req, res, config, (conv as any).workspace_id);
    if (!auth) return;

    const { data, error } = await sb
      .from('conversation_messages')
      .select('*')
      .eq('conversation_id', conversationId)
      .order('created_at', { ascending: true });
    if (error) return res.status(500).json({ error: error.message });
    let messages = (data || []) as any[];

    // Super Admin can hide Telegram bot menu taps from operator threads.
    if (messages.some((m) => String((m?.metadata as any)?.channel_menu_event ?? '') === 'true')) {
      const menuVisible = await isTelegramMenuEventsVisible(config);
      if (!menuVisible) {
        messages = messages.filter(
          (m) => String((m?.metadata as any)?.channel_menu_event ?? '') !== 'true',
        );
      }
    }

    const ids = new Set<string>();
    const fromMeta = new Set<string>();
    for (const m of messages) {
      if (m?.id) ids.add(m.id);
      const aid = (m?.metadata as any)?.attachment_id;
      if (typeof aid === 'string') fromMeta.add(aid);
    }
    const attMap: Record<string, any> = {};
    // A single inbound channel message can carry SEVERAL media parts
    // (WhatsApp album, Telegram document + caption, …) so this is a list.
    const byMsg: Record<string, any[]> = {};
    if (ids.size || fromMeta.size) {
      const orFilters: string[] = [];
      if (ids.size) orFilters.push(`message_id.in.(${Array.from(ids).join(',')})`);
      if (fromMeta.size) orFilters.push(`id.in.(${Array.from(fromMeta).join(',')})`);
      const { data: atts } = await sb
        .from('conversation_attachments')
        .select('id, file_name, mime_type, size_bytes, status, message_id, created_at')
        .or(orFilters.join(','));
      for (const a of (atts || []) as any[]) {
        if (a.status !== 'attached' && a.status !== 'uploaded') continue;
        const mime = String(a.mime_type || '');
        const meta = {
          id: a.id, file_name: a.file_name, mime_type: a.mime_type, size_bytes: a.size_bytes,
          kind: mime.startsWith('image/')
            ? 'image'
            : mime.startsWith('audio/')
              ? 'audio'
              : mime.startsWith('video/')
                ? 'video'
                : 'file',
        };
        attMap[a.id] = meta;
        if (a.message_id) (byMsg[a.message_id] ||= []).push(meta);
      }
    }

    const senderIds = Array.from(new Set(
      messages.filter((m) => (m.sender_type === 'agent' || m.sender_type === 'ai') && m.sender_id).map((m) => m.sender_id),
    ));
    const senderMap: Record<string, { name: string | null; avatar: string | null }> = {};
    if (senderIds.length) {
      const { data: profiles } = await sb.from('profiles').select('id, full_name, avatar_url').in('id', senderIds);
      for (const p of (profiles || []) as any[]) {
        senderMap[p.id] = { name: p.full_name || null, avatar: p.avatar_url || null };
      }
    }

    const enriched = messages.map((m) => {
      const aid = (m?.metadata as any)?.attachment_id;
      const list: any[] = [];
      const seen = new Set<string>();
      if (typeof aid === 'string' && attMap[aid]) { list.push(attMap[aid]); seen.add(aid); }
      for (const a of (m.id && byMsg[m.id]) || []) {
        if (!seen.has(a.id)) { list.push(a); seen.add(a.id); }
      }
      const prof = m.sender_id ? senderMap[m.sender_id] : null;
      return {
        ...m,
        // `attachment` kept for backwards compatibility with older clients.
        ...(list.length ? { attachment: list[0], attachments: list } : {}),
        sender_name: prof?.name ?? null,
        sender_avatar: prof?.avatar ?? null,
      };
    });


    return res.json({ messages: enriched });
  } catch (err: any) {
    console.error('[conversations messages] error:', err);
    return res.status(500).json({ error: err?.message || 'Internal error' });
  }
});

// ═══════════════════════════════════════════════════════════════════
// POST /:id/seen — operator-side "seen" trigger.
//
// Replaces the client-side supabase.rpc('mark_conversation_seen', ...)
// call. That RPC checks is_workspace_member(workspace_id, auth.uid())
// internally — it would silently no-op (0 rows) called via service_role,
// since auth.uid() is NULL outside a Supabase Auth session. The
// membership check and monotonic update are reimplemented directly here
// against the same table/columns; behavior is identical.
// ═══════════════════════════════════════════════════════════════════
conversationsRouter.post('/:id/seen', async (req: any, res: any) => {
  try {
    const config: ServerConfig = (req as any).serverConfig;
    const conversationId = req.params.id;
    const sb = getServiceClient(config);

    const { data: conv } = await sb
      .from('conversations')
      .select('id, workspace_id')
      .eq('id', conversationId)
      .maybeSingle();
    if (!conv) return res.status(404).json({ error: 'conversation_not_found' });

    const auth = await authorizeWorkspaceMember(req, res, config, (conv as any).workspace_id);
    if (!auth) return;

    const { data, error } = await sb
      .from('conversation_messages')
      .update({ seen_at: new Date().toISOString() })
      .eq('conversation_id', conversationId)
      .eq('sender_type', 'contact')
      .is('seen_at', null)
      .select('id');
    if (error) return res.status(500).json({ error: error.message });
    return res.json({ ok: true, count: (data || []).length });
  } catch (err: any) {
    console.error('[conversations seen] error:', err);
    return res.status(500).json({ error: err?.message || 'Internal error' });
  }
});

// ═══════════════════════════════════════════════════════════════════
// DELETE / — delete ALL conversations (+ their messages) in a
// workspace. Destructive workspace-wide operation, so — unlike the
// per-message/per-conversation routes above, which only require plain
// membership — this requires manage:true (owner/admin), matching the
// bar already set for other destructive workspace-wide operations
// (member removal, invitation deletion) elsewhere in this migration.
// ═══════════════════════════════════════════════════════════════════
const deleteAllSchema = z.object({ workspace_id: z.string().uuid() });

conversationsRouter.delete('/', async (req: any, res: any) => {
  try {
    const config: ServerConfig = (req as any).serverConfig;
    const parsed = deleteAllSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: 'workspace_id is required' });
    const auth = await authorizeWorkspaceAccess(req, res, parsed.data.workspace_id, { manage: true });
    if (!auth) return;

    const sb = getServiceClient(config);
    const { data: convs, error: fetchErr } = await sb
      .from('conversations')
      .select('id')
      .eq('workspace_id', parsed.data.workspace_id);
    if (fetchErr) return res.status(500).json({ error: fetchErr.message });
    const ids = (convs ?? []).map((c: any) => c.id);
    if (ids.length === 0) return res.json({ deleted: 0 });

    const { error: msgErr } = await sb.from('conversation_messages').delete().in('conversation_id', ids);
    if (msgErr) return res.status(500).json({ error: msgErr.message });

    const { error: convErr } = await sb.from('conversations').delete().in('id', ids);
    if (convErr) return res.status(500).json({ error: convErr.message });

    return res.json({ deleted: ids.length });
  } catch (err: any) {
    console.error('[conversations delete-all] error:', err);
    return res.status(500).json({ error: err?.message || 'Internal error' });
  }
});

conversationsRouter.post('/not-spam', async (req: any, res: any) => {
  const config = (req as any).serverConfig as ServerConfig;
  const parsed = spamSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: 'invalid_params' });
  const auth = await authorizeWorkspaceMember(req, res, config, parsed.data.workspace_id);
  if (!auth) return;
  try {
    const result = await unmarkSpam(config, {
      workspaceId: parsed.data.workspace_id,
      conversationId: parsed.data.conversation_id,
      operatorId: auth.userId,
    });
    void publishOperatorEvent(config, {
      kind: 'spam_changed',
      conversation_id: parsed.data.conversation_id,
      workspace_id: parsed.data.workspace_id,
      actor_id: auth.userId,
      is_spam: false,
      contact_id: result.contact_id,
    });
    return res.json(result);
  } catch (err: any) {
    if (err?.message === 'conversation_not_found') {
      return res.status(404).json({ error: 'conversation_not_found' });
    }
    console.error('[conversations not-spam] error:', err);
    return res.status(500).json({ error: err?.message || 'Internal error' });
  }
});
