// GENERATED by scripts/ios/write-native-config.mjs — do not edit by hand.
//
// Source of truth: platform_domains.api_base_url (Super Admin → Branding),
// resolved at generation time. This is only the BOOTSTRAP the app uses for its
// very first request; see PlatformOrigin.swift, which replaces it with the
// platform's own answer and remembers that instead.

import Foundation

enum GeneratedConfig {
    /// Origin the app sends every API request to.
    static let apiBaseURL = URL(string: "https://api.webyar.ai")!

    /// Opened from Settings → About.
    static let supportURL = URL(string: "https://destekly.tr/contact")

    /// Language a first launch starts in, before the operator picks one.
    static let defaultLanguage = Language.en
}
