// GENERATED by scripts/ios/write-native-config.mjs — do not edit by hand.
// Source of truth: config/mobile-runtime.json (or MOBILE_API_BASE_URL).

import Foundation

enum GeneratedConfig {
    /// Origin the app sends every API request to.
    static let apiBaseURL = URL(string: "https://api.destekly.tr")!

    /// Opened from Settings → About.
    static let supportURL = URL(string: "https://destekly.tr/contact")

    /// Language a first launch starts in, before the operator picks one.
    static let defaultLanguage = Language.en
}
