import { supabase } from '@/lib/supabase';
import { useAuth } from '@/features/auth/AuthContext';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useParams, useNavigate } from 'react-router-dom';
import { useMemo, useCallback } from 'react';
import type { Workspace } from '@/types/models';

/** Fetch all workspaces the current user is a member of */
export function useWorkspaces() {
  const { user } = useAuth();
  return useQuery({
    queryKey: ['workspaces', user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('workspaces')
        .select('*, workspace_members!inner(user_id)')
        .eq('workspace_members.user_id', user!.id);
      if (error) throw error;
      return data as Workspace[];
    },
    enabled: !!user,
  });
}

/**
 * Route-based active workspace — STRICT resolution.
 * Reads :slug from /app/w/:slug/* and resolves against user's workspaces.
 * Returns `notFound: true` if slug doesn't match any workspace the user has access to.
 * NEVER falls back to a different workspace.
 */
export function useActiveWorkspace() {
  const { slug } = useParams<{ slug: string }>();
  const { data: workspaces, isLoading } = useWorkspaces();

  const result = useMemo(() => {
    if (!workspaces || isLoading) return { workspace: null, notFound: false };
    if (!slug) return { workspace: null, notFound: false };

    const match = workspaces.find(w => w.slug === slug);
    if (!match) return { workspace: null, notFound: true };
    return { workspace: match, notFound: false };
  }, [workspaces, slug, isLoading]);

  return { ...result, workspaces: workspaces ?? [], isLoading };
}

/** @deprecated Use useActiveWorkspace instead */
export function useCurrentWorkspace() {
  const { workspace } = useActiveWorkspace();
  return workspace;
}

/** Build a workspace-scoped path */
export function useWorkspacePath() {
  const { workspace } = useActiveWorkspace();
  return useCallback(
    (path: string) => workspace ? `/app/w/${workspace.slug}${path}` : `/app${path}`,
    [workspace]
  );
}

/** Create a workspace atomically via RPC */
export function useCreateWorkspace() {
  const { user } = useAuth();
  const qc = useQueryClient();

  return useMutation({
    mutationFn: async ({ accountId, name }: { accountId: string; name: string }) => {
      // Slug is auto-generated by the backend — no user input needed
      const { data, error } = await supabase.rpc('create_workspace_atomic', {
        _account_id: accountId,
        _name: name,
        _slug: '', // Backend will generate ws_xxxx slug
        _user_id: user!.id,
      });
      if (error) throw error;
      return data as string;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ['workspaces'] }),
  });
}

/** Fetch the user's account */
export function useAccount() {
  const { user } = useAuth();
  return useQuery({
    queryKey: ['account', user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('accounts')
        .select('*, account_members!inner(user_id)')
        .eq('account_members.user_id', user!.id)
        .limit(1)
        .single();
      if (error) throw error;
      return data;
    },
    enabled: !!user,
  });
}
