-- Fixture for the in-process PostgREST engine's parity suite.
--
-- Its own schema, so the suite never touches application tables and the
-- reference PostgREST (when one is run) can expose exactly this schema.
DROP SCHEMA IF EXISTS pgrst_parity CASCADE;
CREATE SCHEMA pgrst_parity;
SET search_path TO pgrst_parity;

CREATE TABLE parent (
  id uuid PRIMARY KEY,
  name text NOT NULL,
  meta jsonb DEFAULT '{}'::jsonb,
  tags text[],
  n int DEFAULT 7,
  status text DEFAULT 'open',
  doc tsvector,
  created_at timestamptz NOT NULL DEFAULT '2026-01-01T00:00:00Z'
);

CREATE TABLE child (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id uuid REFERENCES parent(id),
  other_parent_id uuid REFERENCES parent(id),
  label text,
  score numeric(10, 2),
  payload jsonb,
  sent_at timestamptz
);

-- One-to-one (FK is the primary key).
CREATE TABLE profile (
  parent_id uuid PRIMARY KEY REFERENCES parent(id),
  note text
);

-- A single, unambiguous many-to-one.
CREATE TABLE workspace (
  id uuid PRIMARY KEY,
  slug text UNIQUE NOT NULL,
  name text
);

CREATE TABLE member (
  workspace_id uuid NOT NULL REFERENCES workspace(id),
  user_name text NOT NULL,
  role text NOT NULL DEFAULT 'agent',
  settings jsonb,
  PRIMARY KEY (workspace_id, user_name)
);

CREATE TABLE kv (
  key text PRIMARY KEY,
  value jsonb,
  updated_at timestamptz
);

CREATE FUNCTION comp_one(_n int) RETURNS parent LANGUAGE sql AS $$ SELECT * FROM pgrst_parity.parent ORDER BY name LIMIT 1 $$;
CREATE FUNCTION do_nothing() RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE FUNCTION scalar_fn(a int, b text DEFAULT 'x') RETURNS text LANGUAGE sql AS $$ SELECT a::text || b $$;
CREATE FUNCTION set_text(_n int) RETURNS SETOF text LANGUAGE sql AS $$ SELECT g::text FROM generate_series(1, _n) g $$;
CREATE FUNCTION set_table(_n int) RETURNS TABLE(i int, sq int) LANGUAGE sql AS $$ SELECT g, g * g FROM generate_series(1, _n) g $$;
CREATE FUNCTION json_fn(_x jsonb) RETURNS jsonb LANGUAGE sql AS $$ SELECT jsonb_build_object('got', _x) $$;
CREATE FUNCTION arr_fn(_ids uuid[], _flag boolean) RETURNS int LANGUAGE sql AS $$ SELECT coalesce(array_length(_ids, 1), 0) + CASE WHEN _flag THEN 100 ELSE 0 END $$;
CREATE FUNCTION raise_fn() RETURNS int LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'PARITY_BOOM' USING DETAIL = 'd1', HINT = 'h1'; END $$;
CREATE FUNCTION out_fn(OUT a int, OUT b text) LANGUAGE sql AS $$ SELECT 1, 'two' $$;
CREATE FUNCTION set_parents() RETURNS SETOF parent LANGUAGE sql AS $$ SELECT * FROM pgrst_parity.parent $$;
CREATE FUNCTION bool_fn(_x text) RETURNS boolean LANGUAGE sql AS $$ SELECT _x IS NOT NULL $$;
CREATE FUNCTION null_fn() RETURNS text LANGUAGE sql AS $$ SELECT NULL::text $$;

-- The reference PostgREST switches into service_role; give it what the
-- application's migrations give it.
GRANT USAGE ON SCHEMA pgrst_parity TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA pgrst_parity TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA pgrst_parity TO service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA pgrst_parity TO service_role;
