package com.webyar.operator.core.storage

import androidx.datastore.preferences.core.stringPreferencesKey
import com.webyar.operator.core.model.User
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * The last operator known to be signed in.
 *
 * Exists so a flaky moment at launch does not look like being signed out.
 * Restoring a session can only be confirmed by asking the server, and on a
 * cold launch — a train, a lift, an emulator whose network is not up yet —
 * that question goes unanswered. Without something to fall back on the app has
 * to choose between showing the login screen to somebody who is signed in, or
 * showing the app to somebody who is not. This makes the first case
 * unnecessary: the token is still in the Keystore, so the session is almost
 * certainly fine, and every screen will discover otherwise the moment a
 * request comes back 401.
 *
 * Deliberately not encrypted: this is a name and an email the operator typed
 * into their own phone, not a credential. The token stays where it is.
 */
class SessionCache(private val store: SecureStore) {
    private val key = stringPreferencesKey("session.lastUser")
    private val json = Json { ignoreUnknownKeys = true }

    /**
     * `User` decodes from the server's shape, which is not the shape worth
     * writing to disk. This is the small, stable subset.
     */
    @Serializable
    private data class Stored(val id: String, val email: String?, val fullName: String?)

    suspend fun save(user: User) {
        runCatching { store.write(key, json.encodeToString(Stored(user.id, user.email, user.fullName))) }
    }

    suspend fun read(): User? = runCatching {
        store.read(key)?.let { json.decodeFromString<Stored>(it) }
    }.getOrNull()?.let { User(id = it.id, email = it.email, fullName = it.fullName) }

    suspend fun clear() = store.remove(key)
}

/**
 * Where this app talks to, and where its links point.
 *
 * The platform names its own hosts once, in Super Admin → Branding
 * (`platform_domains`), and every server-side consumer already follows that
 * without a redeploy. A native app is the one place that could become the
 * exception — a host compiled into the binary keeps pointing at the old domain
 * for as long as the app is installed.
 *
 * So it reads from the platform. The compiled value in [GeneratedConfig] is a
 * **bootstrap of last resort** and nothing more: a shipped binary has to
 * contain some origin to make its first request, because you cannot ask the
 * API where the API is without an API. Everything after that first answer
 * comes from the platform and is remembered.
 *
 * The stored value can always be abandoned. A domain typed wrong in Super
 * Admin would otherwise brick every installed copy, so a stored origin that
 * stops answering is forgotten and the compiled one takes over again.
 */
class PlatformOrigin(private val store: SecureStore) {
    private val originKey = stringPreferencesKey("platform.apiOrigin")
    private val supportKey = stringPreferencesKey("platform.supportURL")

    /** The origin to use right now. Only https is ever adopted. */
    suspend fun current(): String =
        store.read(originKey)?.takeIf { it.startsWith("https://") } ?: GeneratedConfig.API_BASE_URL

    /** True while running on something the platform said, not the built-in value. */
    suspend fun isStored(): Boolean = store.read(originKey) != null

    suspend fun remember(url: String) {
        if (url.startsWith("https://")) store.write(originKey, url)
    }

    suspend fun forget() = store.remove(originKey)

    /** Opened from Settings → About. */
    suspend fun supportUrl(): String? = store.read(supportKey) ?: GeneratedConfig.SUPPORT_URL

    suspend fun rememberSupport(url: String?) {
        if (url != null && url.startsWith("https://")) store.write(supportKey, url)
    }
}

/**
 * The bootstrap origin, and nothing else.
 *
 * On iOS this file is generated by `scripts/ios/write-native-config.mjs` from
 * `platform_domains.api_base_url`. The Android generator is not written yet,
 * so this is the same value stated by hand — and it is only ever the first
 * request; see [PlatformOrigin].
 */
object GeneratedConfig {
    const val API_BASE_URL = "https://api.webyar.ai"
    val SUPPORT_URL: String? = null
}
