#!/usr/bin/env tsx
/**
 * Applies `config/ios-app.json` to the Xcode project.
 *
 * Writes four generated files, all of them fully derived — never hand-edited:
 *
 *   ios/App/App/Info.plist            identity, purpose strings, orientations,
 *                                     background modes, export compliance
 *   ios/App/App/App.entitlements      aps-environment, associated domains,
 *                                     app groups, keychain, Sign in with Apple
 *   ios/App/App/PrivacyInfo.xcprivacy Apple's required-reason API manifest
 *   ios/generated.xcconfig            bundle id, versions, team, deployment
 *                                     target, signing style
 *
 * Runs as part of `npm run ios:sync` (so `npm run ios:prepare` covers it) and
 * is safe to run repeatedly: the output depends only on the JSON input.
 *
 * Why a committed JSON file and not the database: the build machine has no
 * database credentials, and an archive must be reproducible from the commit
 * alone. Super Admin → Mobile App edits the same shape and exports this file.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  buildInfoPlist,
  buildEntitlements,
  buildPrivacyManifest,
  buildXcconfig,
  toPlistXml,
} from '../../server/services/mobileApp/generatedConfig.js';
import {
  MOBILE_APP_DEFAULTS,
  normalize,
  type MobileAppSettings,
} from '../../server/services/mobileApp/settings.js';

const root = process.cwd();
const configPath = resolve(root, 'config/ios-app.json');
const iosApp = resolve(root, 'ios/App/App');

if (!existsSync(resolve(root, 'ios/App/App.xcodeproj'))) {
  console.error('[ios] no Xcode project at ios/App/App.xcodeproj — nothing to apply.');
  process.exit(1);
}

let raw: Record<string, unknown> = {};
if (existsSync(configPath)) {
  raw = JSON.parse(readFileSync(configPath, 'utf8')) as Record<string, unknown>;
} else {
  console.warn('[ios] config/ios-app.json not found — applying built-in defaults.');
}

// An env override exists for CI, where the build number usually comes from the
// pipeline rather than from a commit.
if (process.env.IOS_BUILD_NUMBER) raw.build_number = Number(process.env.IOS_BUILD_NUMBER);
if (process.env.IOS_MARKETING_VERSION) raw.marketing_version = process.env.IOS_MARKETING_VERSION;
if (process.env.APPLE_TEAM_ID) raw.apple_team_id = process.env.APPLE_TEAM_ID;

const settings: MobileAppSettings = normalize({ ...MOBILE_APP_DEFAULTS, ...raw });

const generated = `<!--
  GENERATED by scripts/ios/apply-app-settings.ts from config/ios-app.json.
  Do not edit by hand: \`npm run ios:sync\` overwrites this file.
-->
`;

function writePlist(path: string, value: Record<string, unknown>, label: string): void {
  const xml = toPlistXml(value).replace('<plist version="1.0">', `${generated}<plist version="1.0">`);
  writeFileSync(path, xml, 'utf8');
  console.log(`[ios] ${label} → ${path.replace(`${root}/`, '')}`);
}

writePlist(resolve(iosApp, 'Info.plist'), buildInfoPlist(settings), 'Info.plist');

const entitlements = buildEntitlements(settings);
writePlist(resolve(iosApp, 'App.entitlements'), entitlements, 'entitlements');

writePlist(
  resolve(iosApp, 'PrivacyInfo.xcprivacy'),
  buildPrivacyManifest(settings),
  'privacy manifest',
);

const xcconfig = buildXcconfig(settings);
const xcconfigBody = `// GENERATED by scripts/ios/apply-app-settings.ts from config/ios-app.json.
// Do not edit by hand: \`npm run ios:sync\` overwrites this file.
${Object.entries(xcconfig)
  .map(([key, value]) => `${key} = ${value}`)
  .join('\n')}
`;
writeFileSync(resolve(root, 'ios/generated.xcconfig'), xcconfigBody, 'utf8');
console.log('[ios] build settings → ios/generated.xcconfig');

console.log(
  `[ios] ${settings.display_name} ${settings.marketing_version} (${settings.build_number}) · ${settings.bundle_id}` +
    `${settings.apple_team_id ? ` · team ${settings.apple_team_id}` : ' · NO TEAM SET'}`,
);
