plugins {
    // NOT `org.jetbrains.kotlin.android`: AGP 9 compiles Kotlin itself and
    // refuses to start if that plugin is applied, the same as in `:app`.
    alias(libs.plugins.android.test)
    alias(libs.plugins.androidx.baselineprofile)
}

android {
    namespace = "com.webyar.operator.baselineprofile"
    compileSdk = 37

    defaultConfig {
        // The profile is generated by driving the app on a device; API 28 is
        // the floor for the macrobenchmark tooling, NOT the app's minimum.
        minSdk = 28
        targetSdk = 37
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    targetProjectPath = ":app"
}

baselineProfile {
    /**
     * Generated against the `minified` build, not `release`.
     *
     * A profile is a list of classes and methods BY NAME, and R8 renames
     * them. One generated against an unminified build names methods that do
     * not exist in the shipped one, and the installer silently drops every
     * rule it cannot resolve — leaving a profile that is present, valid and
     * completely inert. `minified` is R8'd exactly like release and is
     * installable, which is what makes it the one to profile.
     */
    // A connected device — the emulator on whatever machine is running this
    // — rather than a Gradle-managed one. A managed device downloads its own
    // system image on first use, which is a gigabyte nobody asked for on a
    // CI host with a 2GB ceiling.
    useConnectedDevices = true
}

dependencies {
    implementation(libs.androidx.test.ext.junit)
    implementation(libs.androidx.test.espresso.core)
    implementation(libs.androidx.test.uiautomator)
    implementation(libs.androidx.benchmark.macro.junit4)
}
