plugins {
    // NOT `org.jetbrains.kotlin.android`: AGP 9 compiles Kotlin itself and
    // refuses to start if that plugin is applied, the same as in `:app`.
    alias(libs.plugins.android.test)
    alias(libs.plugins.androidx.baselineprofile)
}

android {
    namespace = "com.webyar.operator.baselineprofile"
    compileSdk = 37

    defaultConfig {
        // The profile is generated by driving the app on a device; API 28 is
        // the floor for the macrobenchmark tooling, NOT the app's minimum.
        minSdk = 28
        targetSdk = 37
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    targetProjectPath = ":app"
}

baselineProfile {
    /**
     * The plugin builds its own `nonMinifiedRelease` variant to collect
     * against, and that is right rather than a compromise.
     *
     * A profile is a list of classes and methods BY NAME, and R8 renames
     * them — so a profile collected from an R8'd APK would name methods that
     * the NEXT R8 run, with one more class in the app, might call something
     * else. Collecting from unminified names and letting AGP map them
     * through the mapping file at package time is what keeps the profile
     * valid across builds. Getting this the other way round produces a
     * profile that is present, valid-looking and completely inert, because
     * the installer silently drops every rule it cannot resolve.
     */
    // A connected device — the emulator on whatever machine is running this
    // — rather than a Gradle-managed one. A managed device downloads its own
    // system image on first use, which is a gigabyte nobody asked for on a
    // CI host with a 2GB ceiling.
    useConnectedDevices = true

    /**
     * One profile in `src/main`, not a copy per variant.
     *
     * Without this the plugin writes the same 1.6MB of rules into
     * `src/release/generated` and `src/minified/generated` — two identical
     * files, in a repository, that a later run can update one of. `minified`
     * only exists so the R8'd build can be installed and looked at; it has no
     * business having its own idea of what to compile ahead of time.
     */
    mergeIntoMain = true
}

dependencies {
    implementation(libs.androidx.test.ext.junit)
    implementation(libs.androidx.test.espresso.core)
    implementation(libs.androidx.test.uiautomator)
    implementation(libs.androidx.benchmark.macro.junit4)
}
