import Foundation
import CallKit
import PushKit
import AVFoundation
import UIKit
import Observation

/// Makes the phone ring for a visitor's call, and answers it.
///
/// This is the whole point of the feature, so it is worth being precise about
/// what each piece is doing and why it cannot be done more simply:
///
/// **PushKit, not a normal notification.** A banner cannot ring a locked
/// phone, cannot wake a terminated app, and cannot be answered with one tap.
/// A VoIP push can do all three — at the price of a rule iOS enforces without
/// mercy: every single VoIP push must result in `reportNewIncomingCall` before
/// the completion handler runs, or the system kills the app and eventually
/// stops delivering pushes to it altogether. That rule is why the cancel path
/// below reports a call it is about to end rather than quietly ignoring the
/// push.
///
/// **CallKit, not an in-app screen.** CallKit is what makes this indis­tin­guish­able
/// from a phone call: full-screen on the lock screen, the caller's name, the
/// ringtone playing through the ringer with the phone's own vibration, answer
/// on the Apple Watch, and an entry in the Phone app's recents afterwards. An
/// in-app screen can do none of that when the app is not running.
///
/// **One call at a time.** An operator is one person. `maximumCallsPerCallGroup`
/// and `maximumCallGroups` are both 1, so a second visitor calling while the
/// first is connected does not produce a second ring the operator cannot
/// possibly take.
@MainActor
@Observable
final class CallCenterService: NSObject {

    /// The call currently on screen, if any — what the in-app call view shows
    /// once the operator has answered.
    private(set) var active: IncomingCall?
    /// True between answering and the server confirming.
    private(set) var isConnecting = false
    /// Set when the server refused the answer, so the UI can say why.
    private(set) var answerFailed = false

    /// Calls this app has told CallKit about, so a cancel for a call we never
    /// rang is reported first rather than dropped.
    private var known: Set<UUID> = []
    /// The calls we have answered, which decides whether ending one is a
    /// "decline" or a "hang up" as far as the server is concerned.
    private var answered: Set<UUID> = []
    private var ringing: [UUID: IncomingCall] = [:]

    private let provider: CXProvider
    private let controller = CXCallController()
    private var registry: PKPushRegistry?
    private let api: any WebyarAPI

    /// Set by the app so an answered call can reach the workspace it belongs
    /// to. Held weakly: the service outlives no one.
    weak var appState: AppState?

    override init() {
        self.api = Backend.current
        self.provider = CXProvider(configuration: Self.configuration)
        super.init()
        provider.setDelegate(self, queue: nil)
    }

    /// Everything about how the incoming call looks and sounds.
    private static var configuration: CXProviderConfiguration {
        var config = CXProviderConfiguration()
        config.supportsVideo = true
        config.maximumCallsPerCallGroup = 1
        config.maximumCallGroups = 1
        // `.generic` rather than `.phoneNumber`: a website visitor has a name
        // or a code, not a number, and telling iOS otherwise makes it offer
        // to call them back through the carrier.
        config.supportedHandleTypes = [.generic]
        config.includesCallsInRecents = true
        // A ringtone of our own rather than the phone's default, so an
        // operator can tell a work call from a personal one without looking.
        // Generated by scripts/ios/make-ringtone.py.
        config.ringtoneSound = "Ringtone.wav"
        if let icon = UIImage(named: "CallKitIcon")?.pngData() {
            config.iconTemplateImageData = icon
        }
        return config
    }

    // MARK: - Registration

    /// Starts listening for VoIP pushes.
    ///
    /// Called from `application(_:didFinishLaunchingWithOptions:)` and nowhere
    /// else: a registry created any later misses the push that launched the
    /// app, which is exactly the case that matters — the phone was in a
    /// pocket, the app was not running, and somebody called.
    func start() {
        guard registry == nil else { return }
        let registry = PKPushRegistry(queue: .main)
        registry.delegate = self
        registry.desiredPushTypes = [.voIP]
        self.registry = registry
    }

    /// The device's current VoIP address, once iOS has issued one.
    private(set) var voipToken: String? {
        didSet {
            guard voipToken != oldValue else { return }
            Task { await registerDevice() }
        }
    }

    /// Tells the server where to ring this phone.
    ///
    /// Re-sent on every token change and on every sign-in, because a token is
    /// only useful to a server that knows which operator it belongs to.
    func registerDevice() async {
        guard let voipToken, appState?.session.user != nil else { return }
        try? await api.registerPushDevice(
            voipToken: voipToken,
            deviceID: DeviceIdentity.current,
            deviceName: await UIDevice.current.name,
            appVersion: Bundle.main.shortVersion
        )
    }

    // MARK: - Ringing

    /// Rings the phone. Must be called synchronously from the push handler.
    private func reportIncoming(_ call: IncomingCall, completion: @escaping () -> Void) {
        let update = CXCallUpdate()
        update.remoteHandle = CXHandle(type: .generic, value: call.caller)
        update.localizedCallerName = call.caller
        update.hasVideo = call.hasVideo
        // A visitor call has no hold, no grouping and no keypad. Saying so
        // removes three buttons the operator could press to no effect.
        update.supportsHolding = false
        update.supportsGrouping = false
        update.supportsUngrouping = false
        update.supportsDTMF = false

        known.insert(call.id)
        ringing[call.id] = call
        provider.reportNewIncomingCall(with: call.id, update: update) { [weak self] error in
            if error != nil {
                // Do Not Disturb, an active phone call, or a blocked number:
                // iOS refused to ring. Telling the server keeps the call in
                // the queue for somebody who can take it.
                self?.forget(call.id)
                Task { [weak self] in await self?.reject(call, silently: true) }
            }
            completion()
        }
    }

    /// Stops a ring. Reports the call first when we never rang it, because a
    /// VoIP push that ends without a reported call is what gets an app killed.
    private func reportCancellation(_ cancellation: CallCancellation, completion: @escaping () -> Void) {
        let reason: CXCallEndedReason = switch cancellation.reason {
        case .answered: .answeredElsewhere
        case .declined: .declinedElsewhere
        case .cancelled, .timeout: .remoteEnded
        case .ended: .remoteEnded
        }

        if known.contains(cancellation.id) {
            provider.reportCall(with: cancellation.id, endedAt: Date(), reason: reason)
            forget(cancellation.id)
            completion()
            return
        }

        // The ring never arrived — a dead zone, or the cancel overtook it.
        // iOS still demands a call, so report one and end it in the same
        // breath. The operator sees a missed call, which is the truth.
        let update = CXCallUpdate()
        update.localizedCallerName = IncomingCall.unknownCaller
        provider.reportNewIncomingCall(with: cancellation.id, update: update) { [weak self] _ in
            self?.provider.reportCall(with: cancellation.id, endedAt: Date(), reason: reason)
            self?.forget(cancellation.id)
            completion()
        }
    }

    private func forget(_ id: UUID) {
        known.remove(id)
        answered.remove(id)
        ringing[id] = nil
        if active?.id == id {
            active = nil
            isConnecting = false
        }
    }

    // MARK: - Answering

    /// Hangs up from inside the app. Routed through CallKit rather than
    /// straight to the server so the system call UI ends at the same moment.
    func hangUp() {
        guard let active else { return }
        let action = CXEndCallAction(call: active.id)
        controller.request(CXTransaction(action: action)) { _ in }
    }

    private func accept(_ call: IncomingCall) async -> Bool {
        do {
            _ = try await api.acceptCall(callID: call.callID, workspaceID: call.workspaceID)
            return true
        } catch {
            return false
        }
    }

    private func reject(_ call: IncomingCall, silently: Bool = false) async {
        try? await api.rejectCall(callID: call.callID, workspaceID: call.workspaceID)
        if !silently { forget(call.id) }
    }

    private func end(_ call: IncomingCall) async {
        try? await api.endCall(callID: call.callID, workspaceID: call.workspaceID)
    }

    // MARK: - Audio

    /// CallKit owns the audio session's lifetime; the app only describes what
    /// it wants. Configuring it here and starting media in `didActivate` is
    /// the order Apple requires — doing it the other way round gives a call
    /// with no sound in one direction.
    private func configureAudioSession() {
        let session = AVAudioSession.sharedInstance()
        try? session.setCategory(
            .playAndRecord,
            mode: .voiceChat,
            options: [.allowBluetooth, .allowBluetoothA2DP]
        )
        try? session.setPreferredIOBufferDuration(0.005)
    }

    #if DEBUG
    /// Rings the phone with a made-up call.
    ///
    /// The simulator cannot receive a VoIP push at all, so without this there
    /// would be no way to see the ring, the lock-screen UI or the answer path
    /// until a signed build is on a real device with a real visitor waiting.
    /// Compiled out of Release entirely.
    func simulateIncomingCall(channel: CallChannel = .audio) {
        let id = UUID()
        let payload: [AnyHashable: Any] = [
            "event": "incoming",
            "call_id": id.uuidString,
            "workspace_id": appState?.selectedWorkspace?.id ?? UUID().uuidString,
            "workspace_name": appState?.selectedWorkspace?.name ?? "",
            "channel": channel.rawValue,
            "caller": "Maryam Hosseini",
        ]
        guard let call = IncomingCall(push: payload) else { return }
        reportIncoming(call) {}
    }
    #endif
}

// MARK: - PushKit

extension CallCenterService: PKPushRegistryDelegate {

    nonisolated func pushRegistry(
        _ registry: PKPushRegistry,
        didUpdate credentials: PKPushCredentials,
        for type: PKPushType
    ) {
        guard type == .voIP else { return }
        let token = credentials.token.map { String(format: "%02x", $0) }.joined()
        Task { @MainActor [weak self] in self?.voipToken = token }
    }

    nonisolated func pushRegistry(
        _ registry: PKPushRegistry,
        didInvalidatePushTokenFor type: PKPushType
    ) {
        guard type == .voIP else { return }
        Task { @MainActor [weak self] in self?.voipToken = nil }
    }

    /// The one method in this file with a hard deadline. Everything it does is
    /// either synchronous or explicitly completed, and the completion handler
    /// runs on every path.
    nonisolated func pushRegistry(
        _ registry: PKPushRegistry,
        didReceiveIncomingPushWith payload: PKPushPayload,
        for type: PKPushType,
        completion: @escaping () -> Void
    ) {
        guard type == .voIP else { return completion() }
        let dictionary = payload.dictionaryPayload

        Task { @MainActor [weak self] in
            guard let self else { return completion() }
            let event = CallPushEvent(rawValue: (dictionary["event"] as? String) ?? "") ?? .incoming

            switch event {
            case .incoming:
                if let call = IncomingCall(push: dictionary) {
                    self.reportIncoming(call, completion: completion)
                } else {
                    // A payload we cannot read is still a payload iOS wants a
                    // call for. Ring with what little we have rather than
                    // being killed for staying silent.
                    self.reportUnreadable(completion: completion)
                }

            case .cancel:
                if let cancellation = CallCancellation(push: dictionary) {
                    self.reportCancellation(cancellation, completion: completion)
                } else {
                    self.reportUnreadable(completion: completion)
                }
            }
        }
    }

    /// Last resort: report and immediately end a call we know nothing about,
    /// which satisfies iOS without lying to the operator for more than an
    /// instant.
    private func reportUnreadable(completion: @escaping () -> Void) {
        let id = UUID()
        let update = CXCallUpdate()
        update.localizedCallerName = IncomingCall.unknownCaller
        provider.reportNewIncomingCall(with: id, update: update) { [weak self] _ in
            self?.provider.reportCall(with: id, endedAt: Date(), reason: .failed)
            completion()
        }
    }
}

// MARK: - CallKit

extension CallCenterService: CXProviderDelegate {

    nonisolated func providerDidReset(_ provider: CXProvider) {
        // The system tore every call down — an audio reset, or the user
        // killing the app mid-call. Nothing to end server-side: those calls
        // are already gone.
        Task { @MainActor [weak self] in
            self?.known.removeAll()
            self?.answered.removeAll()
            self?.ringing.removeAll()
            self?.active = nil
            self?.isConnecting = false
        }
    }

    nonisolated func provider(_ provider: CXProvider, perform action: CXAnswerCallAction) {
        Task { @MainActor [weak self] in
            guard let self, let call = self.ringing[action.callUUID] else {
                action.fail()
                return
            }
            self.configureAudioSession()
            self.answered.insert(call.id)
            self.active = call
            self.isConnecting = true
            // Fulfilled straight away: CallKit gives a few seconds before it
            // assumes the app has hung, and the server round-trip is not
            // something to gamble that budget on. If it fails, the call is
            // ended below with a reason the operator can see.
            action.fulfill()

            if await self.accept(call) {
                self.isConnecting = false
                self.provider.reportOutgoingCall(with: call.id, connectedAt: Date())
            } else {
                self.answerFailed = true
                self.isConnecting = false
                self.provider.reportCall(with: call.id, endedAt: Date(), reason: .failed)
                self.forget(call.id)
            }
        }
    }

    nonisolated func provider(_ provider: CXProvider, perform action: CXEndCallAction) {
        Task { @MainActor [weak self] in
            guard let self, let call = self.ringing[action.callUUID] else {
                action.fulfill()
                return
            }
            // Ending a call that was never answered is a decline, and the two
            // are different server-side: a decline leaves the call in the
            // queue for somebody else, an end finishes it for everyone.
            if self.answered.contains(call.id) {
                await self.end(call)
            } else {
                await self.reject(call)
            }
            self.forget(call.id)
            action.fulfill()
        }
    }

    nonisolated func provider(_ provider: CXProvider, perform action: CXSetMutedCallAction) {
        Task { @MainActor in
            // No media engine yet: accepting the action keeps the system UI's
            // mute button honest about its own state.
            action.fulfill()
        }
    }

    nonisolated func provider(_ provider: CXProvider, didActivate audioSession: AVAudioSession) {
        // Where media starts once there is media to start.
    }

    nonisolated func provider(_ provider: CXProvider, didDeactivate audioSession: AVAudioSession) {
        // And where it stops.
    }
}

// MARK: - Device identity

/// A stable id for this install, so a rotating push token never creates a
/// second device row for the same phone.
///
/// `identifierForVendor` is the right primitive: stable while any app from
/// this vendor is installed, reset when they are all removed, and never a
/// hardware identifier Apple would reject the app for reading.
enum DeviceIdentity {
    private static let key = "device.identifier"

    @MainActor
    static var current: String {
        if let stored = UserDefaults.standard.string(forKey: key) { return stored }
        let value = UIDevice.current.identifierForVendor?.uuidString ?? UUID().uuidString
        UserDefaults.standard.set(value, forKey: key)
        return value
    }
}

extension Bundle {
    var shortVersion: String {
        (infoDictionary?["CFBundleShortVersionString"] as? String) ?? "0"
    }
}
