
ALTER TABLE widget_settings
  ADD COLUMN IF NOT EXISTS theme text DEFAULT 'modern',
  ADD COLUMN IF NOT EXISTS fab_icon text DEFAULT 'chat',
  ADD COLUMN IF NOT EXISTS fab_shape text DEFAULT 'circle',
  ADD COLUMN IF NOT EXISTS fab_label text,
  ADD COLUMN IF NOT EXISTS fab_scale integer DEFAULT 100,
  ADD COLUMN IF NOT EXISTS fab_icon_color text DEFAULT '#ffffff',
  ADD COLUMN IF NOT EXISTS fab_text_color text DEFAULT '#ffffff',
  ADD COLUMN IF NOT EXISTS fab_animation boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS secondary_color text,
  ADD COLUMN IF NOT EXISTS auto_open_delay integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS show_logo boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS offline_message text,
  ADD COLUMN IF NOT EXISTS placeholder_text text,
  ADD COLUMN IF NOT EXISTS greeting_message text,
  ADD COLUMN IF NOT EXISTS default_mode text DEFAULT 'chat',
  ADD COLUMN IF NOT EXISTS support_mode text DEFAULT 'human_first',
  ADD COLUMN IF NOT EXISTS widget_language text DEFAULT 'auto',
  ADD COLUMN IF NOT EXISTS mobile_behavior text DEFAULT 'bottom_sheet',
  ADD COLUMN IF NOT EXISTS fab_help_icon text DEFAULT 'help_circle',
  ADD COLUMN IF NOT EXISTS fab_chat_label text,
  ADD COLUMN IF NOT EXISTS fab_help_label text;
