INSERT INTO email_templates (workspace_id, slug, locale, subject, html_body, text_body, is_active) VALUES
(NULL, 'offline_message_received', 'en', 'New offline message from {contact_name}',
'<!DOCTYPE html><html lang="en" dir="ltr"><body style="margin:0;padding:0;background:#f4f5f7;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f4f5f7;"><tr><td align="center" style="padding:40px 20px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#fff;border-radius:12px;box-shadow:0 2px 8px rgba(0,0,0,.06);overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#3B82F6,#1E40AF);padding:24px 32px;color:#fff;"><h1 style="margin:0;font-size:18px;font-weight:600;">New offline message</h1></td></tr><tr><td style="padding:28px 32px;color:#334155;font-size:15px;line-height:24px;"><p style="margin:0 0 16px;">A visitor left a message while your workspace was offline.</p><table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;margin:0 0 16px;font-size:14px;"><tr><td style="padding:6px 0;color:#64748b;">From</td><td style="padding:6px 0;"><strong>{contact_name}</strong></td></tr><tr><td style="padding:6px 0;color:#64748b;">Email</td><td style="padding:6px 0;">{contact_email}</td></tr></table><div style="background:#f8fafc;border-left:3px solid #3B82F6;padding:14px 16px;border-radius:6px;color:#1e293b;font-size:14px;line-height:22px;white-space:pre-wrap;">{message_body}</div><p style="margin:24px 0 0;font-size:13px;color:#64748b;">Open this conversation in your inbox to reply.</p></td></tr></table></td></tr></table></body></html>',
'New offline message from {contact_name} ({contact_email}):

{message_body}

Open this conversation in your inbox to reply.', true),
(NULL, 'offline_message_received', 'fa', 'پیام آفلاین جدید از {contact_name}',
'<!DOCTYPE html><html lang="fa" dir="rtl"><body style="margin:0;padding:0;background:#f4f5f7;font-family:Tahoma,Segoe UI,Arial,sans-serif;direction:rtl;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f4f5f7;"><tr><td align="center" style="padding:40px 20px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#fff;border-radius:12px;box-shadow:0 2px 8px rgba(0,0,0,.06);overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#3B82F6,#1E40AF);padding:24px 32px;color:#fff;"><h1 style="margin:0;font-size:18px;font-weight:600;">پیام آفلاین جدید</h1></td></tr><tr><td style="padding:28px 32px;color:#334155;font-size:15px;line-height:26px;"><p style="margin:0 0 16px;">یک بازدیدکننده در زمان آفلاین بودن کارگاه شما پیامی ارسال کرده است.</p><table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;margin:0 0 16px;font-size:14px;"><tr><td style="padding:6px 0;color:#64748b;">از طرف</td><td style="padding:6px 0;"><strong>{contact_name}</strong></td></tr><tr><td style="padding:6px 0;color:#64748b;">ایمیل</td><td style="padding:6px 0;">{contact_email}</td></tr></table><div style="background:#f8fafc;border-right:3px solid #3B82F6;padding:14px 16px;border-radius:6px;color:#1e293b;font-size:14px;line-height:24px;white-space:pre-wrap;">{message_body}</div><p style="margin:24px 0 0;font-size:13px;color:#64748b;">برای پاسخ، این مکالمه را در صندوق ورودی باز کنید.</p></td></tr></table></td></tr></table></body></html>',
'پیام آفلاین جدید از {contact_name} ({contact_email}):

{message_body}

برای پاسخ، این مکالمه را در صندوق ورودی باز کنید.', true),
(NULL, 'offline_message_received', 'tr', '{contact_name} kişisinden yeni çevrimdışı mesaj',
'<!DOCTYPE html><html lang="tr" dir="ltr"><body style="margin:0;padding:0;background:#f4f5f7;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f4f5f7;"><tr><td align="center" style="padding:40px 20px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#fff;border-radius:12px;box-shadow:0 2px 8px rgba(0,0,0,.06);overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#3B82F6,#1E40AF);padding:24px 32px;color:#fff;"><h1 style="margin:0;font-size:18px;font-weight:600;">Yeni çevrimdışı mesaj</h1></td></tr><tr><td style="padding:28px 32px;color:#334155;font-size:15px;line-height:24px;"><p style="margin:0 0 16px;">Bir ziyaretçi, çalışma alanınız çevrimdışıyken bir mesaj bıraktı.</p><table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;margin:0 0 16px;font-size:14px;"><tr><td style="padding:6px 0;color:#64748b;">Gönderen</td><td style="padding:6px 0;"><strong>{contact_name}</strong></td></tr><tr><td style="padding:6px 0;color:#64748b;">E-posta</td><td style="padding:6px 0;">{contact_email}</td></tr></table><div style="background:#f8fafc;border-left:3px solid #3B82F6;padding:14px 16px;border-radius:6px;color:#1e293b;font-size:14px;line-height:22px;white-space:pre-wrap;">{message_body}</div><p style="margin:24px 0 0;font-size:13px;color:#64748b;">Yanıtlamak için bu konuşmayı gelen kutusunda açın.</p></td></tr></table></td></tr></table></body></html>',
'{contact_name} kişisinden yeni çevrimdışı mesaj ({contact_email}):

{message_body}

Yanıtlamak için bu konuşmayı gelen kutusunda açın.', true)
ON CONFLICT DO NOTHING;