// This file is automatically generated. Do not edit it directly.
//
// GOTRUE CUTOVER: Supabase Auth session machinery is intentionally OFF.
// Dashboard identity comes exclusively from the first-party HttpOnly
// `gs_session` cookie (server/routes/auth.ts + server/lib/workspaceAuth.ts).
// This client is used only as a database/realtime transport for
// intentionally public (anon-safe) reads. It must never persist, refresh
// or detect a Supabase Auth session — no `sb-*-auth-token` in storage,
// no `/auth/v1` traffic. If this file is ever regenerated, keep the
// `auth` block below exactly as-is.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdycuenbjztkgnaqonfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkeWN1ZW5ianp0a2duYXFvbmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwOTczODksImV4cCI6MjA5MTY3MzM4OX0.YDa2Gt-ZjADDmN5jpJZGaUiEsB152x4IsQG7yE0qiEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  }
});
