#!/bin/sh
# NOT generated by Coolify. Hand-written; see deploy/app-downloads/README.md.
# Mirrors the desktop apps' official releases onto each brand's site, so people
# and the installed apps get everything from that site's /downloads/:
#
#   WebYar  https://app.webyar.ai/downloads/   /data/app-downloads/webyar
#   RESPOK  https://app.respok.app/downloads/  /data/app-downloads/respok
#
# Per brand, people download each app as it is and as a zip (each name a symlink to
# the newest version's file):
#   <Prefix>-Setup.exe and <Prefix>-Windows.zip: the Windows installer, from the
#   brand's GitHub releases (CI: .github/workflows/desktop-native.yml);
#   <Prefix>-Mac.dmg and <Prefix>-Mac.zip: the DMG, from the brand's Sparkle
#   appcast (CI: .github/workflows/macos.yml);
#   <Prefix>-Android.zip: the APK the brand's frontend serves itself
#   (public/downloads/<Prefix>-Android.apk), checked against its sidecar's sha256.
# And windows/: the Velopack update feed the installed apps read (releases.win.json,
# RELEASES and the packages of the newest two releases), as published.
# Runs every 5 minutes (systemd timer app-downloads-sync). One brand failing
# (e.g. no release yet) never stops the other.
set -u
ROOT=${APP_DOWNLOADS_ROOT:-/data/app-downloads}

# brand  windows-releases-repo  setup-asset  mac-appcast  file-prefix  site
BRANDS='
webyar pc30cc/webyar-desktop-releases Webyar-Setup.exe https://raw.githubusercontent.com/pc30cc/mac-os/main/appcast.xml Webyar app.webyar.ai
respok pc30cc/respok-releases RESPOK-Setup.exe https://raw.githubusercontent.com/pc30cc/respok-releases/main/mac/appcast.xml RESPOK app.respok.app
'

fetch() { # name size url dest-dir   (size "-" = unknown: fetch once, keep)
  if [ -f "$4/$1" ]; then
    [ "$2" = - ] && return 0
    [ "$(stat -c %s "$4/$1")" = "$2" ] && return 0
  fi
  curl -fsSL --retry 2 "$3" -o "$TMP/$1" || { echo "download failed: $3" >&2; return 1; }
  if [ "$2" != - ] && [ "$(stat -c %s "$TMP/$1")" != "$2" ]; then echo "size mismatch for $1" >&2; return 1; fi
  mv "$TMP/$1" "$4/$1"
  echo "fetched $4/$1"
}

pack() { # file name-in-zip dir zip — writes dir/zip whole or not at all
  python3 - "$1" "$2" "$3/.$4.part" <<'PY' || { rm -f "$3/.$4.part"; echo "zip failed: $4" >&2; return 1; }
import sys, zipfile
with zipfile.ZipFile(sys.argv[3], "w", zipfile.ZIP_DEFLATED) as z:
    z.write(sys.argv[1], sys.argv[2])
PY
  mv "$3/.$4.part" "$3/$4"
  echo "zipped $3/$4"
}

prune() { # dir glob symlink — keep the symlink's target and the 2 newest others (by download time)
  target=$(readlink "$1/$3" 2>/dev/null || true)
  ( cd "$1" && ls -1t $2 2>/dev/null ) | grep -vxF "${target:-/}" | tail -n +3 | while read -r old; do rm -f "$1/$old"; done
}

windows() { # brand repo setup-asset prefix
  FILES=$ROOT/$1; FEED=$FILES/windows
  mkdir -p "$FEED"
  curl -fsSL "https://api.github.com/repos/$2/releases?per_page=6" -o "$TMP/releases.json" || { echo "$1: no releases from $2" >&2; return 1; }
  # The packages of the newest two stable releases: the newest one's index names only its own full
  # package and delta, and the one before stays a while for apps that are halfway through an update.
  python3 - "$TMP/releases.json" "$3" > "$TMP/plan.txt" <<'PY' || return 1
import json, sys
setup = sys.argv[2]
rels = [r for r in json.load(open(sys.argv[1])) if not r.get("draft") and not r.get("prerelease")]
for i, r in enumerate(rels[:2]):
    v = r["tag_name"].lstrip("v")
    for a in r.get("assets", []):
        n = a["name"]
        if n.endswith(".nupkg"):
            print("pkg", n, a["size"], a["browser_download_url"])
        elif i == 0 and n in ("releases.win.json", "RELEASES"):
            print("index", n, a["size"], a["browser_download_url"])
        elif i == 0 and n == setup:
            print("setup", v, a["size"], a["browser_download_url"])
PY
  # Packages first, then the index that lists them, so the feed never names a missing file:
  # if any package failed, the index stays as it was until a later run gets them all.
  rm -f "$TMP/pkgfail"
  grep '^pkg ' "$TMP/plan.txt" | while read -r _ n s u; do fetch "$n" "$s" "$u" "$FEED" || : > "$TMP/pkgfail"; done
  grep '^setup ' "$TMP/plan.txt" | while read -r _ v s u; do
    exe="$4-Setup-$v.exe"; zip="$4-Windows-$v.zip"
    fetch "$exe" "$s" "$u" "$FILES" || continue
    if [ ! -f "$FILES/$zip" ]; then pack "$FILES/$exe" "$4-Setup.exe" "$FILES" "$zip" || continue; fi
    ln -sfn "$exe" "$FILES/$4-Setup.exe"
    ln -sfn "$zip" "$FILES/$4-Windows.zip"
  done
  if [ -e "$TMP/pkgfail" ]; then
    echo "$1: a package is missing; the update index is left as it was" >&2
    return 1
  fi
  # Both index files, or neither: the packages below are pruned only once the index on disk
  # is this run's, so a failed download never leaves an index naming a removed package.
  rm -f "$TMP/idxfail"
  grep '^index ' "$TMP/plan.txt" | while read -r _ n s u; do
    { curl -fsSL --retry 2 "$u" -o "$TMP/$n.new" && [ "$(stat -c %s "$TMP/$n.new")" = "$s" ]; } || : > "$TMP/idxfail"
  done
  if [ -e "$TMP/idxfail" ]; then
    echo "$1: the update index did not download; it and the packages are left as they were" >&2
    return 1
  fi
  for n in releases.win.json RELEASES; do
    if [ -e "$TMP/$n.new" ]; then mv "$TMP/$n.new" "$FEED/$n"; fi
  done
  # Only the packages planned above stay: exactly what the index (and the one before) can name.
  for f in "$FEED"/*.nupkg; do
    [ -e "$f" ] || continue
    grep -q "^pkg $(basename "$f") " "$TMP/plan.txt" || rm -f "$f"
  done
  prune "$FILES" "$4-Windows-*.zip" "$4-Windows.zip"
  prune "$FILES" "$4-Setup-*.exe" "$4-Setup.exe"
}

mac() { # brand appcast prefix
  FILES=$ROOT/$1
  mkdir -p "$FILES"
  curl -fsSL "$2" -o "$TMP/appcast.xml" || { echo "$1: no appcast at $2" >&2; return 1; }
  # The newest stable item (no sparkle:channel): its version; the DMG sits beside the zip it names.
  python3 - "$TMP/appcast.xml" "$2" "$3" > "$TMP/mac.txt" <<'PY' || return 1
import sys, xml.etree.ElementTree as ET
S = "{http://www.andymatuschak.org/xml-namespaces/sparkle}"
appcast, prefix = sys.argv[2], sys.argv[3]
base = appcast.rsplit("/", 1)[0]
best = None
for item in ET.parse(sys.argv[1]).getroot().iter("item"):
    if item.find(S + "channel") is not None:
        continue
    build = int(item.findtext(S + "version") or 0)
    version = item.findtext(S + "shortVersionString") or ""
    if version and (best is None or build > best[0]):
        best = (build, version)
if best:
    v = best[1]
    print("%s %s/releases/%s/%s-%s.dmg" % (v, base, v, prefix, v))
PY
  read -r v url < "$TMP/mac.txt" || return 0
  dmg="$3-Mac-$v.dmg"; zip="$3-Mac-$v.zip"
  fetch "$dmg" - "$url" "$FILES" || return 1
  if [ ! -f "$FILES/$zip" ]; then pack "$FILES/$dmg" "$3-Mac.dmg" "$FILES" "$zip" || return 1; fi
  ln -sfn "$dmg" "$FILES/$3-Mac.dmg"
  ln -sfn "$zip" "$FILES/$3-Mac.zip"
  prune "$FILES" "$3-Mac-*.zip" "$3-Mac.zip"
  prune "$FILES" "$3-Mac-*.dmg" "$3-Mac.dmg"
}

android() { # brand site prefix
  FILES=$ROOT/$1
  mkdir -p "$FILES"
  # The frontend ships the APK and its sidecar (versionName, versionCode, sha256, sizeBytes).
  curl -fsSL "https://$2/downloads/$3-Android.json" -o "$TMP/android.json" || { echo "$1: no $3-Android.json on $2" >&2; return 1; }
  python3 - "$TMP/android.json" > "$TMP/android.txt" <<'PY' || return 1
import json, re, sys
j = json.load(open(sys.argv[1]))
v = "%s-%s" % (j["versionName"], j["versionCode"])
assert re.fullmatch(r"[0-9][A-Za-z0-9.\-]*", v), v
assert re.fullmatch(r"[0-9a-f]{64}", j["sha256"])
print(v, int(j["sizeBytes"]), j["sha256"])
PY
  read -r v size sha < "$TMP/android.txt" || return 1
  zip="$3-Android-$v.zip"
  if [ ! -f "$FILES/$zip" ]; then
    fetch "$3-Android.apk" "$size" "https://$2/downloads/$3-Android.apk" "$TMP/dl" || return 1
    [ "$(sha256sum "$TMP/dl/$3-Android.apk" | cut -d' ' -f1)" = "$sha" ] || { echo "$1: the APK does not match its sha256" >&2; return 1; }
    pack "$TMP/dl/$3-Android.apk" "$3-Android.apk" "$FILES" "$zip" || return 1
  fi
  ln -sfn "$zip" "$FILES/$3-Android.zip"
  prune "$FILES" "$3-Android-*.zip" "$3-Android.zip"
}


echo "$BRANDS" | while read -r brand repo setup appcast prefix site; do
  [ -n "$brand" ] || continue
  TMP=$(mktemp -d); mkdir "$TMP/dl"
  windows "$brand" "$repo" "$setup" "$prefix" || echo "$brand: Windows not mirrored" >&2
  mac "$brand" "$appcast" "$prefix" || echo "$brand: Mac not mirrored" >&2
  android "$brand" "$site" "$prefix" || echo "$brand: Android not zipped" >&2
  rm -rf "$TMP"
done
exit 0
