#!/bin/sh
# NOT generated by Coolify. Hand-written; see deploy/app-downloads/README.md.
# Mirrors the desktop apps' official releases onto each brand's site, so people
# and the installed apps get everything from that site's /downloads/:
#
#   WebYar  https://app.webyar.ai/downloads/   /data/app-downloads/webyar
#   RESPOK  https://app.respok.app/downloads/  /data/app-downloads/respok
#
# Per brand:
#   <Prefix>-Setup-<version>.exe (+ <Prefix>-Setup.exe -> the newest) and
#   windows/ — the Velopack update feed (releases.win.json, RELEASES and the
#   packages of the newest two releases),
#   from the brand's GitHub releases (CI: .github/workflows/desktop-native.yml);
#   <Prefix>-Mac-<version>.dmg (+ <Prefix>-Mac.dmg -> the newest), from the
#   brand's Sparkle appcast (CI: .github/workflows/macos.yml).
# Runs every 5 minutes (systemd timer app-downloads-sync). One brand failing
# (e.g. no release yet) never stops the other.
set -u
ROOT=${APP_DOWNLOADS_ROOT:-/data/app-downloads}

# brand  windows-releases-repo  setup-asset  mac-appcast  file-prefix
BRANDS='
webyar pc30cc/webyar-desktop-releases Webyar-Setup.exe https://raw.githubusercontent.com/pc30cc/mac-os/main/appcast.xml Webyar
respok pc30cc/respok-releases RESPOK-Setup.exe https://raw.githubusercontent.com/pc30cc/respok-releases/main/mac/appcast.xml RESPOK
'

fetch() { # name size url dest-dir   (size "-" = unknown: fetch once, keep)
  if [ -f "$4/$1" ]; then
    [ "$2" = - ] && return 0
    [ "$(stat -c %s "$4/$1")" = "$2" ] && return 0
  fi
  curl -fsSL --retry 2 "$3" -o "$TMP/$1" || { echo "download failed: $3" >&2; return 1; }
  if [ "$2" != - ] && [ "$(stat -c %s "$TMP/$1")" != "$2" ]; then echo "size mismatch for $1" >&2; return 1; fi
  mv "$TMP/$1" "$4/$1"
  echo "fetched $4/$1"
}

prune() { # dir glob symlink — keep the symlink's target and the 2 newest others (by download time)
  target=$(readlink "$1/$3" 2>/dev/null || true)
  ( cd "$1" && ls -1t $2 2>/dev/null ) | grep -vxF "${target:-/}" | tail -n +3 | while read -r old; do rm -f "$1/$old"; done
}

windows() { # brand repo setup-asset prefix
  FILES=$ROOT/$1; FEED=$FILES/windows
  mkdir -p "$FEED"
  curl -fsSL "https://api.github.com/repos/$2/releases?per_page=6" -o "$TMP/releases.json" || { echo "$1: no releases from $2" >&2; return 1; }
  # The packages of the newest two stable releases: the newest one's index names only its own full
  # package and delta, and the one before stays a while for apps that are halfway through an update.
  python3 - "$TMP/releases.json" "$3" "$4" > "$TMP/plan.txt" <<'PY' || return 1
import json, sys
setup, prefix = sys.argv[2], sys.argv[3]
rels = [r for r in json.load(open(sys.argv[1])) if not r.get("draft") and not r.get("prerelease")]
for i, r in enumerate(rels[:2]):
    v = r["tag_name"].lstrip("v")
    for a in r.get("assets", []):
        n = a["name"]
        if n.endswith(".nupkg"):
            print("pkg", n, a["size"], a["browser_download_url"])
        elif i == 0 and n in ("releases.win.json", "RELEASES"):
            print("index", n, a["size"], a["browser_download_url"])
        elif i == 0 and n == setup:
            print("setup", "%s-Setup-%s.exe" % (prefix, v), a["size"], a["browser_download_url"])
PY
  # Packages first, then the index that lists them, so the feed never names a missing file:
  # if any package failed, the index stays as it was until a later run gets them all.
  rm -f "$TMP/pkgfail"
  grep '^pkg ' "$TMP/plan.txt" | while read -r _ n s u; do fetch "$n" "$s" "$u" "$FEED" || : > "$TMP/pkgfail"; done
  grep '^setup ' "$TMP/plan.txt" | while read -r _ n s u; do fetch "$n" "$s" "$u" "$FILES" && ln -sfn "$n" "$FILES/$4-Setup.exe"; done
  if [ -e "$TMP/pkgfail" ]; then
    echo "$1: a package is missing; the update index is left as it was" >&2
    return 1
  fi
  # Both index files, or neither: the packages below are pruned only once the index on disk
  # is this run's, so a failed download never leaves an index naming a removed package.
  rm -f "$TMP/idxfail"
  grep '^index ' "$TMP/plan.txt" | while read -r _ n s u; do
    { curl -fsSL --retry 2 "$u" -o "$TMP/$n.new" && [ "$(stat -c %s "$TMP/$n.new")" = "$s" ]; } || : > "$TMP/idxfail"
  done
  if [ -e "$TMP/idxfail" ]; then
    echo "$1: the update index did not download; it and the packages are left as they were" >&2
    return 1
  fi
  for n in releases.win.json RELEASES; do
    if [ -e "$TMP/$n.new" ]; then mv "$TMP/$n.new" "$FEED/$n"; fi
  done
  # Only the packages planned above stay: exactly what the index (and the one before) can name.
  for f in "$FEED"/*.nupkg; do
    [ -e "$f" ] || continue
    grep -q "^pkg $(basename "$f") " "$TMP/plan.txt" || rm -f "$f"
  done
  prune "$FILES" "$4-Setup-*.exe" "$4-Setup.exe"
}

mac() { # brand appcast prefix
  FILES=$ROOT/$1
  mkdir -p "$FILES"
  curl -fsSL "$2" -o "$TMP/appcast.xml" || { echo "$1: no appcast at $2" >&2; return 1; }
  # The newest stable item (no sparkle:channel): its version; the DMG sits beside the zip it names.
  python3 - "$TMP/appcast.xml" "$2" "$3" > "$TMP/mac.txt" <<'PY' || return 1
import sys, xml.etree.ElementTree as ET
S = "{http://www.andymatuschak.org/xml-namespaces/sparkle}"
appcast, prefix = sys.argv[2], sys.argv[3]
base = appcast.rsplit("/", 1)[0]
best = None
for item in ET.parse(sys.argv[1]).getroot().iter("item"):
    if item.find(S + "channel") is not None:
        continue
    build = int(item.findtext(S + "version") or 0)
    version = item.findtext(S + "shortVersionString") or ""
    if version and (best is None or build > best[0]):
        best = (build, version)
if best:
    v = best[1]
    print("%s-Mac-%s.dmg %s/releases/%s/%s-%s.dmg" % (prefix, v, base, v, prefix, v))
PY
  read -r name url < "$TMP/mac.txt" || return 0
  fetch "$name" - "$url" "$FILES" && ln -sfn "$name" "$FILES/$3-Mac.dmg"
  prune "$FILES" "$3-Mac-*.dmg" "$3-Mac.dmg"
}


echo "$BRANDS" | while read -r brand repo setup appcast prefix; do
  [ -n "$brand" ] || continue
  TMP=$(mktemp -d)
  windows "$brand" "$repo" "$setup" "$prefix" || echo "$brand: Windows not mirrored" >&2
  mac "$brand" "$appcast" "$prefix" || echo "$brand: Mac not mirrored" >&2
  rm -rf "$TMP"
done
exit 0
